### ISSUE TITLE
"You must upload a watermark" warning is displayed "too early".

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#10]
Using 3.0, when "enable watermark" is selected on admin-gui (while creating a new theme), a red warning is automatically shown which displays "You must upload a watermark".

It seems this warning might be shown only on form validation, not when just enabling watermark.

**Comment by lkiesow** [comment]
The decision was made to not migrate to Github but stay with Bitbucket and Jira.
If this  issue still persists, can you please open a ticket at
https://opencast.jira.com
