### ISSUE TITLE
Elasticsearch can't index big ACLs

### ISSUE THREAD

**Issue by wsmirnow** [opencast/opencast#1089]
If you try to update the event or series ACL with a huge ruleset, at some point you will see a message like this in the log output:
`Document contains at least one immense term in field="access_policy" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.`
The ACL changes aren't shown in the admin UI. But if you run an index rebuild, you will see the same message againg and the event/series metadata will be empty.

The message does mean, that the elastic index field for access policy can contain at least 32766 byte values. You have exceed this limit. To index such a big ACLs we need to change the type of the `access_policy` field to `text`.

**Comment by smarquard** [comment]
Curious to know what the use-cases are for a very large ACL set. An event/series shared with a large number of individual users (ROLE_USER_XXX entries), or a very large number of groups or external roles?

**Comment by lkiesow** [comment]
We encountered the error when a lot of users were added to the ACL. But really, the access control should not break if users add a few more roles in the UI.

**Comment by staubesv** [comment]
@smarquard AFAIK, It is a large group of individual users where permissions are set per API by the learning management system ILIAS. As we talk about hundreds (vs. thousands or even millions). I agree with @lkiesow that "hundreds" really should not break Opencast.

**Comment by mtneug** [comment]
Is this not fixed by #1090?

**Comment by wsmirnow** [comment]
Yes, this issue can be closed as it is fixed by #1090
