### ISSUE TITLE
New documentation theme does not display properly on iOS

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1099]
**Describe the bug**
Per [Andy's Tweet](https://twitter.com/calisurf/status/1177668870288490497?s=20), the docs don't display correctly on iPad (iOS 13.1).
![EFfrmCEU8AAVOhH](https://user-images.githubusercontent.com/5639561/65801326-1519b280-e136-11e9-8e74-102a86fda4e7.jpeg)

**Comment by gregorydlogan** [comment]
Related to #1080 :)

**Comment by lkiesow** [comment]
Nor does this work on any other browser:
Hit the button to hide the menu and it seems to be broken.

**Comment by smarquard** [comment]
On the latest Chrome on Mac, you get a too-small serif font choice that's not great either:

![image](https://user-images.githubusercontent.com/5888197/65819361-ca726600-e21b-11e9-9763-662fd804840a.png)
