### ISSUE TITLE
Security XML configs are in inconsistent states

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1116]
We currently have a four separate security config files (`etc/security/*.xml`) which are in various states of disrepair.  These should be unified into a single config with all of the components necessary for CAS, Shibboleth, LDAP, and whatever else we support being present, but disabled.

**Comment by lkiesow** [comment]
By now, only CAS is left as a separate and somewhat broken external configuration. @miesgre, if I remember correctly, you are using CAS. Do you by any chance have the time to take a look at including CAS in the main configuration as well?

**Comment by miesgre** [comment]
> By now, only CAS is left as a separate and somewhat broken external configuration. @miesgre, if I remember correctly, you are using CAS. Do you by any chance have the time to take a look at including CAS in the main configuration as well?

I will take a look

**Comment by lkiesow** [comment]
Thanks.
