### ISSUE TITLE
Remove unnecessary ExceptionUtils.getStackTrace

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1119]
At a lot of places `ExceptionUtils.getStackTrace(…)` is used for logging which is completely unnecessary since Opencast's logger is already able to handle errors on its while being more efficient. 

So instead of

```java
logger.error("Some error happened somewhere: {}", ExceptionUtils.getStackTrace(e));
```

…the code should be just:

```java
logger.error("Some error happened somewhere", e);
```

Note that no `{}` may be used in the logger for the exception and the exception is the last parameter in the logger call.

**Comment by AdamMoas** [comment]
Hey, I could pick this up later today, if nobody else has.

**Comment by lkiesow** [comment]
So far, no one has. Feel free to work on this.

**Comment by alexmario74** [comment]
I would like to take this, if still free.

**Comment by AdamMoas** [comment]
I see you have a PR open for it. I'll un-assign myself.
