### ISSUE TITLE
Remove references to `org.opencastproject.db.ddl.generation`

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1125]
Via https://opencast.jira.com/browse/MH-12733

See discussion [on list](https://groups.google.com/a/opencast.org/forum/#!topic/dev/TE9lpqxXWTw).

Apparently this setting does not do anything anymore, but it still features prominently in the admin documentation.

EclipseLink apparently creates the necessary tables automatically, independent of this setting, if they are not already there. So the caveat about "please run the provided DDL script first to reap suchandsuch optimization benefits" still applies.

This would also be completely obsolete once #1105 is merged, even if it were being used by anyone right now.

**Comment by JoshLambertUW** [comment]
I'll work on this one.

**Comment by adamrmelnyk** [comment]
Hello, I've opened I small PR for this, let me know if there's anything else I can help with.
