### ISSUE TITLE
Name of newly created user does not appear in selection list

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1139]
Via https://opencast.jira.com/browse/MH-11526

Steps to reproduce (Users Page):
1. Create a new user.
2. After creation Press on the Filter icon in the filter bar.
3. Select Name in the drop down.
4. new user does not show up in the second filter selection drop down.

Actual Results:
The name of the new user does not show up in the second filter selection drop down.

Expected Results:
The name of the new user should show up in the filter drop down.

Workaround (if any):
Remove the filter by name - search is sufficient to find a user by name.

**Comment by sharath2106** [comment]
@gregorydlogan I would like to work on this. Please assign this to me.

**Comment by sharath2106** [comment]
@gregorydlogan I just got sometime to work on this issue. And I've some questions for you - 
On which module should I start working on? And also, how to run this in my local? I shall also add these instructions in the ReadME during my commit.

<img width="412" alt="Screenshot 2019-10-12 at 11 48 22 AM" src="https://user-images.githubusercontent.com/25933070/66696071-38239500-ece6-11e9-9745-efafd8dc5553.png">

**Comment by sharath2106** [comment]
@gregorydlogan Any updates? I would need to set the app in my local environment.

**Comment by gregorydlogan** [comment]
Hi @sharath2106, the issue in question lives in the `admin-ui` bundle, specifically in the `src/main/webapp` directory.  You probably want to start [here](https://docs.opencast.org/develop/developer/#modules/admin-ui/development/#live-working-with-a-running-opencast) in terms of UI development.  Building the backend is as easy as `mvn clean install -P dev` from the clone's directory.  See [here](https://docs.opencast.org/develop/developer/#development-environment/) for better instructions.

**Comment by staubesv** [comment]
@sharath2106 Happy to see that you are willing to help fixing this!

The symptom indicates that the Admin UI does not reload the filters after a new user has been created.

You can easily verify this by using the inspection feature of your web browsers feature that lists the HTTP requests. The request of question is GET /admin-ng/resources/{resource}/filters.json which loads all filters (including values) for the given page {resource}, e.g. GET /admin-ng/resources/users/filters.json on the page Organization->Users.
This happens whenever you change the page, but it seems not when you create a new user on the page Organization->Users.

The front-end code that runs when you add a new users is https://github.com/opencast/opencast/blob/develop/modules/admin-ui/src/main/webapp/scripts/modules/users/controllers/userController.js#L125.

Hope this helps and good luck!

**Comment by lkiesow** [comment]
Fixed by #1735
