### ISSUE TITLE
Quick-links in documentation

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1144]
It would be nice to have a way to quickly link a specific documentation header by clicking on a link next to it like this:

![Screenshot from 2019-10-12 21-29-00](https://user-images.githubusercontent.com/1008395/66706842-7cd81c00-ed38-11e9-8e17-91aedbe049e4.png)

This functionality shouldn't be hard to add to the documentation template in [opencast/docs/guides/admin/docs/javascript/extra.js](https://github.com/opencast/opencast/blob/develop/docs/guides/admin/docs/javascript/extra.js)

**Comment by dhrubo55** [comment]
hey @lkiesow  can i work on this?

**Comment by lkiesow** [comment]
Sure, go ahead.

The anchors should already be there – that's what the navigation on the left is using after all. So we would more or less just need some JavaScript attaching something like ¶ as link to the end of the headings (H1-H6(?)).

**Comment by lkiesow** [comment]
@dhrubo55, are you still working on this?

**Comment by lkiesow** [comment]
I guess the answer is no…
