### ISSUE TITLE
Workflow selection does not work

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1145]
1. On 8.x, go to “Add Event” → “Workflow” and select the first workflow from the drop-down menu
2. Try to select the second one: This does not work at all.
3. Select the first one again: The UI for the second one is selected.

This feels like someone messed up the index of the workflows picked from some list in the JavaScript. You can test this issue right now on [develop.opencast.org](https://develop.opencast.org). For development, it probably suffices to use the admin interface mockup:

-  [Admin Interface :: Live working with a Mockup
](https://docs.opencast.org/develop/developer/#modules/admin-ui/development/#live-working-with-a-mockup)

**Comment by darolfes** [comment]
Seems like this is already fixed. @lkiesow
