### ISSUE TITLE
Can't create an event with a wmv file

### ISSUE THREAD

**Issue by JamesUoM** [opencast/opencast#1152]
**Describe the bug**
A clear and concise description of what you see:
can't create a new event when uploading a *.wmv file

**To Reproduce**
Steps to reproduce the behaviour:
Add Event
Upload source and choose and wmv file
Complete the modul
Get "Error Can't Create Event"
response says "400: Provided file format video/x-ms-wmv not allowed." Note wmv is in the list of allowed extensions

**Environment Information**
 - OS: [Ubuntu 16.04
 - Browser: Chromium
 - Opencast version with minor release: develop

**Comment by gregorydlogan** [comment]
I imagine this will be fixed by #1141, but we'll see.

**Comment by lkiesow** [comment]
Closing this since #1152 has been merged. Please re-open if the bug persists.
