### ISSUE TITLE
No virsion of this software can be installed on any current operating system.

### ISSUE THREAD

**Issue by OpenExpert** [opencast/opencast#1155]
We are designating this abandoned and not usable.
Until such time as any one OS version and install instructions does work.

**Comment by gregorydlogan** [comment]
That's... Surprising. Please list the issue(s) you are seeing, including the relevant distributions.

**Comment by scottprovost** [comment]
On Ubuntu 19 it appears to install but will not start. On current centos it is missing two packages.
Put simply, in its current state, it installs on nothing. It is not surprising. It is obviously not being test installed by the maintainers. Most software does no survive distro upgrades without work. We are designating it abandoned. We will look for volunteers to fix and maintain a fork.

**Comment by gregorydlogan** [comment]
@scottprovost The Debian packages come unconfigured, as described [in the documentation](https://docs.opencast.org/develop/admin/#installation/debs/#install-opencast).  Both the CentOS and Debian packages are known to be working, and I've (re)verified today that all required packages are present in the repos.  I would suggest rereading the documentation and following the instructions more closely.

In terms of fork, by all means feel free.  We are ECL2 licensed, so we encourage forking.

**Comment by scottprovost** [comment]
Last metadata expiration check: 19:57:03 ago on Sun 20 Oct 2019 10:05:35 PM EDT.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides sox >= 14 needed by opencast22-allinone-2.2.4-1.el7.centos.noarch
  - nothing provides tesseract >= 3 needed by opencast22-allinone-2.2.4-1.el7.centos.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by lkiesow** [comment]
That pretty much looks like you did not activate EPEL. It's [the second step in the activate the repository docs](https://docs.opencast.org/r/7.x/admin/#installation/rpm-rhel-sl-centos/#activate-repository). Both sox and tesseract should be in EPEL:

> Add the Extra Packages for Enterprise Linux (EPEL) repository:
>
>     yum install epel-release
>
> If this package is not available, please enable this repository manually. For that, follow the [instructions in the EPEL documentation](https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F).

EDIT:
Also, you really shouldn't install Opencast 2.2. That's outdated and no longer supported for a few years now. The latest release is 7.4.

**Comment by OpenExpert** [comment]
Instructions were followed explicitly. Fix your instruction and I will follow them again.

**Comment by scottprovost** [comment]
The current release of Centos 7 Stream goes through the motions of installing epel-release.
But does not provide any packages. This is likely because or the release name not matching any available in the epel repo but it does not error leading people to believe they have installed epel.
I am trying with CentOS-8-x86_64-1905-dvd1.iso

**Comment by scottprovost** [comment]
No go on Ubuntu 19 or Centos 8. Why is this bug closed?

**Comment by OpenExpert** [comment]
They explained to me that because this software is known to work on old operating systems, while no current operating system can run it, they do not consider that a bug.
