### ISSUE TITLE
Set https cookies with Secure and HttpOnly

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1158]
Per https://opencast.jira.com/browse/MH-8659

**Description**
Cookie is set without flags e.g. 

JSESSIONID=hwh3algw3xyz;Path=/ 

Expected Results: 

If the session is https, cookie should set Secure and HttpOnly flags, e.g.: 

JSESSIONID=hwh3algw3xyz;Path=/; Secure; HttpOnly 

See https://www.owasp.org/index.php/Session_Management#Protect_Session_Identifiers and https://www.owasp.org/index.php/HttpOnly 

Via @JamesUoM 
```
Under Karaf with PAX web you can add following to etc/org.ops4j.pax.web.cfg:

org.ops4j.pax.web.session.cookie.httpOnly=true
org.ops4j.pax.web.session.cookie.secure=true

I don't know though if the secure flag requires jetty to be using HTTPS itself rather than setting behind a HTTPS proxy
```

**Comment by lkiesow** [comment]
It's just configuration and can already be done. See:

```
% curl -sI https://develop.opencast.org | grep set-cookie
set-cookie: JSESSIONID=node0mpkpzmk0zdrt6sl5kkdhlq0579905.node0;Path=/; HTTPOnly; Secure
```

**Comment by JamesUoM** [comment]
> curl -sI https://develop.opencast.org | grep set-cookie
NB use "grep -i set-cookie" as on my system it's Set-Cookie

**Comment by smarquard** [comment]
Is there a custom configuration for develop.opencast.org that sets these in org.ops4j.pax.web.cfg? I don't see them mentioned here:

https://github.com/opencast/opencast/blob/develop/etc/org.ops4j.pax.web.cfg

**Comment by JamesUoM** [comment]
Just about to suggest we add it the config to etc/org.ops4j.pax.web.cfg as no one is going to read the pax.web docs!
