### ISSUE TITLE
Search index does not include media size in mediapackage

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1169]
Via https://opencast.jira.com/browse/MH-8554

In order to make the UI more intuitive we would like to display media file sizes to users who may want to download published media. The media file size should be a property for each media track in the search/episode service i.e
../../search/episode.json?

**Comment by lkiesow** [comment]
I think this is what you are looking for:

https://github.com/opencast/opencast/blob/4e9e5f6f2c4ad286211f4b9b7adc7238b9417b94/modules/common/src/main/java/org/opencastproject/mediapackage/AbstractMediaPackageElement.java#L90-L92

**Comment by smarquard** [comment]
Looking at what ends up in the search index, the size isn't being set on the track at all so far:

https://develop.opencast.org/search/episode.json?id=f360a6f4-4c19-41e2-8fd0-7d51c727feb0

          "track": {
            "id": "337df29c-6391-48ca-8fa6-42bdd0c660d4",
            "type": "presenter/preview",
            "ref": "track:496ac8e3-eec5-4694-8264-7430d9fdfd78",
            "mimetype": "video/mp4",
            "tags": {
              "tag": [
                "atom",
                "default",
                "engage-download",
                "engage-streaming",
                "rss"
              ]
            },
            "url": "https://develop.opencast.org/static/mh_default_org/engage-player/f360a6f4-4c19-41e2-8fd0-7d51c727feb0/4730ef5e-a815-4c1b-b0d5-43e0c6daabb0/ToS_4k_1920.mp4",
            "checksum": {
              "type": "md5",
              "$": "a60bd3a066a4bec32d1328be4270764b"
            },

and curiously it's set for attachments but with size=0 (though I can't think of a use case for wanting to know attachment size in advance).

**Comment by lkiesow** [comment]
It's not being set, but you would only need to add this at some point in the workflow process. This could e.g. happen as part of the inspect operation. Once `size` is set, it should appear in the search results.
