### ISSUE TITLE
Security configuration file fails when logging is enabled

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#1213]
**Describe the bug**
When in the security configuration file you enable the logging, crashes the security configuration. 

**To Reproduce**

In the file `/etc/opencast/security/mh_default_org.xml` (could it be other tenant)
If you uncomment the mentioned lines:
```xml
 <!-- Do not use a request cache -->
  <bean id="requestCache" class="org.springframework.security.web.savedrequest.NullRequestCache" />

  <!-- Uncomment to enable logging interceptors -->
  <!-- bean class="org.springframework.security.access.event.LoggerListener" / -->
  <!-- bean class="org.springframework.security.authentication.event.LoggerListener" / -->

</beans>
```

To this:

```xml
 <!-- Do not use a request cache -->
  <bean id="requestCache" class="org.springframework.security.web.savedrequest.NullRequestCache" />

  <!-- Uncomment to enable logging interceptors -->
  <bean class="org.springframework.security.access.event.LoggerListener" />
  <bean class="org.springframework.security.authentication.event.LoggerListener" />

</beans>
```

Opencast appears this error in the log file:

> | ERROR | (`SpringSecurityConfigurationArtifactInstaller:102`) - Unable to refresh spring security configuration file `/etc/opencast/security/mh_default_org.xml`: {}
> `org.springframework.beans.factory.CannotLoadBeanClassException`: Cannot find class [`org.springframework.security.access.event.LoggerListener`] for bean with name `'org.springframework.security.access.event.LoggerListener#0'` defined in OSGi resource[`file:/etc/opencast/security/mh_default_org.xml|bnd.id=94|bnd.sym=opencast-kernel`]; nested exception is java.lang.ClassNotFoundException: `org.springframework.security.access.event.LoggerListener` not found from bundle [opencast-kernel]
> 

**Workaround**

To enable the logging can be use the opencast logger `org.ops4j.pax.logging.cfg` but this approach makes opencast very slow.

**Environment Information**
 - OS: CentOS 7
 - Browser Safari
 - Opencast 7.4

**Comment by mliradelc** [comment]
@lkiesow What is your opinion on this, actually you can log into if you use the logger, or that lines make another type of logger?

**Comment by lkiesow** [comment]
This probably once added a piece of code to the Spring filter chain logging the requests which dodes no longer exist. Hence, this shouldn't be in that configuration file. Will fix that.
