### ISSUE TITLE
Show build date

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1215]
Opencast lists its version and commit hash (if build from source). Having the build date a well would be really helpful, especially on the test servers:

![Screenshot from 2019-11-06 16-38-50](https://user-images.githubusercontent.com/1008395/68313099-53e74480-00b4-11ea-8610-f98291dd3e1b.png)

**Comment by mliradelc** [comment]
+1, Normally to look this (Kinda) I have to look the log files to know when it was this commit.

@lkiesow In the case the build is inconsistent, should show the build date also?
