### ISSUE TITLE
Opencast 9 cluster config: Unable to find a workflow handler for 'publish-engage'

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#1243]
**Describe the bug**
When Opencast 9 is configured as a Cluster, the publish-engage WOH fails with this message:

```java
Workflow operation 'operation:'publish-engage', position:29, state:'FAILED'' failed java.lang.IllegalStateException: Unable to find a workflow handler for 'publish-engage'
```

At the same time, the Engage and the worker nodes notify about dispatching Job issues even with the dispatcher in each worker turned off as describe in the documentation.

```java
Exception Description: The object [Job {id:3483, operation:START_OPERATION, status:DISPATCHING}] cannot be updated because it has changed or been deleted since it was last read.
```

**If it's installed as allinone, this doesn't happen.** Works without issues.

**To Reproduce**
1. Install as a cluster
2. Try to publish

**Environment Information**
 - OS: CentOS 7
 - Browser Safari
 - Opencast 9 [Develop branch as this time]

Develop group discussion: https://groups.google.com/a/opencast.org/forum/#!topic/dev/gmn5MiQ51wE

**Comment by gregorydlogan** [comment]
@mliradelc With the version of develop I'm about to push I'm no longer seeing it, whether that's a fix from #1226 (I'd be surprised) or not.

One thing to check: Develop changed the `dispatchinterval` key in the SR config file to `dispatch.interval`, and moved it from milliseconds to seconds.  You've made those changes to your configuration, correct?

**Comment by mliradelc** [comment]
Thanks Greg, I will look on it

Update: The error with the dispatcher disappeared with your suggestion ;), for the other I will wait for your PR

**Comment by gregorydlogan** [comment]
I don't have a PR to fix anything here, appears to have been a documentation issue.  I'll resolve this now, please reopen if I've missed something.
