### ISSUE TITLE
Inconsistent default value for `storage_id`

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1244]
@gregorydlogan, you set the `storage_id` in the ddl script to a default value which is not guaranteed if you use any other system of database set-up:

https://github.com/opencast/opencast/blob/a4019af192858a0dccda1ee89a1dae3752f632c2/docs/scripts/ddl/mysql5.sql#L382

Is this actually required? Opencast seems to work just fine without is (e.g. when running with the internal database). Can you take a look at this?

---

Same here:

https://github.com/opencast/opencast/blob/a4019af192858a0dccda1ee89a1dae3752f632c2/docs/scripts/ddl/mysql5.sql#L364

**Comment by gregorydlogan** [comment]
The [migration script](https://github.com/opencast/opencast/blob/develop/docs/upgrade/5_to_6/mysql5.sql) sets those values to their default, but you raise a good point that the dto class does not set the default.  I can specify the default on the column annotation, but I'm not sure how portable that will actually be.

Are you seeing situations where this column is still null, or just nit-picking on the mismatch?

**Comment by lkiesow** [comment]
It's actually more than nitpicking since our short-term goal is that we want to drop the ddl script. I don't think the defaults are necessary – otherwise, I would have expected to see issues e.g. on the test servers about this – but I assumed you added them to the scripts for a reason.

If they are an unnecessary mismatch, can you fix the scripts? I don't think there is an actual way if setting this default in JPA.

**Comment by gregorydlogan** [comment]
There is a way: `columnDefinition`.  Which takes the literal column definition, hence my assumption that it's not going to be terribly portable...

I'll file a PR removing the default from the creation script.

**Comment by lkiesow** [comment]
thanks
