### ISSUE TITLE
Presenter/creator field empty after processing scheduled event from Extron SMP 352

### ISSUE THREAD

**Issue by scharnkn** [opencast/opencast#1247]
When scheduling events with Extron SMP352, the creator field of the event metadata ("presenter" in the admin UI) turns empty right after ingesting is started from the Extron SMP. The event then has to be reprocessed for the field to be filled again. 

The problem does not occur with Adhoc-recordings from the Extron SMP.

This might be related to the changes described in https://opencast.jira.com/browse/MH-12930

1. Using the Admin UI, schedule an event with Extron SMP as capture agent, fill the meta data with the respective values, e.g. "ThePresenter" for the presenter
2. Wait until the event has finished recording and starts ingesting, the field "presenter" is now suddenly empty

**Environment Information**
- This bug occurs exclusively with following Opencast versions: 6.3, 6.4, 6.5, 6.6
- Version 6.2 is *not* affected, from version 7.0 upwards, the bug is also *not* present

**Additional infos**

The attached metadata catalogues are from two fully processed events using version 6.2 and 6.3 respectively, notice the empty "creator" field in version 6.3, as well as the missing "owner" field.
[oc6-3_342846af-43e3-4ad7-b978-ffffecf68da8.txt](https://github.com/opencast/opencast/files/3891144/oc6-3_342846af-43e3-4ad7-b978-ffffecf68da8.txt)
[oc6-2_a78845dc-8f36-45a2-8424-c5f0eda82868.txt](https://github.com/opencast/opencast/files/3891145/oc6-2_a78845dc-8f36-45a2-8424-c5f0eda82868.txt)

**Comment by lkiesow** [comment]
Closing this since Opencast 6 is no longer supported
