### ISSUE TITLE
solr search index rebuild uses excessive memory

### ISSUE THREAD

**Issue by smarquard** [opencast/opencast#1273]
**Describe the bug**

In a large production system with many mediapackages in oc_search, a rebuild of the solr search index may require additional java heap to succeed.

**To Reproduce**

Remove the solr search indexes, restart Opencast.

**Analysis**

In SearchServiceDatabaseImpl, getAllMediaPackages() happily reads every single mediapackage in oc_search into memory and returns an iterator to a linked list.

May need a similar solution to:

https://github.com/opencast/opencast/commit/fb112bbd818959477bebe109593086d54cdbcea4#diff-4156d2fcb5e91dbf060244b2df8601e5

to read these in batches. Related to https://github.com/opencast/opencast/pull/1272 which adds a method to get the number of items in storage.

**Comment by gregorydlogan** [comment]
Solr is dead with 16.0, long live Opensearch
