### ISSUE TITLE
Notification of Newer Opencast Version in Admin UI

### ISSUE THREAD

**Issue by rrolf** [opencast/opencast#1280]
There is a notification area in the Admin UI behind the bell. 

It would be nice to create a new notification, if a newer Opencast version exists then the version that its currently installed. Maybe even a link to the release docs would be nice.

The current version should be known as it is shown on the bottom of the admin UI.

New versions can be found in the Github tag list.

**Comment by lkiesow** [comment]
We can use [GitHub's API](https://developer.github.com/v3/repos/releases/#list-releases) to get the latest version.

`curl -s https://api.github.com/repos/opencast/opencast/releases/latest`
```json
{
  "url": "https://api.github.com/repos/opencast/opencast/releases/27564942",
  "assets_url": "https://api.github.com/repos/opencast/opencast/releases/27564942/assets",
  "upload_url": "https://uploads.github.com/repos/opencast/opencast/releases/27564942/assets{?name,label}",
  "html_url": "https://github.com/opencast/opencast/releases/tag/8.5",
  "id": 27564942,
  "node_id": "MDc6UmVsZWFzZTI3NTY0OTQy",
  "tag_name": "8.5",
  "target_commitish": "develop",
  "name": "Opencast 8.5",
  "draft": false,
  "author": {
    …
  },
  "prerelease": false,
  "created_at": "2020-06-15T16:30:15Z",
  "published_at": "2020-06-15T16:53:15Z",
  "assets": […],
  "tarball_url": "https://api.github.com/repos/opencast/opencast/tarball/8.5",
  "zipball_url": "https://api.github.com/repos/opencast/opencast/zipball/8.5",
  "body": "Changelog available in https://docs.opencast.org/r/8.x/admin/changelog/"
}
```

And the bundle info service to get Opencast's version:

`curl -s 'https://develop.opencast.org/sysinfo/bundles/version?prefix=opencast'`
```json
{
  "consistent": true,
  "version": "9.0.0.SNAPSHOT",
  "buildNumber": "228dcd7"
}
```

with `X...-SNAPSHOT > X.Y.0`
