### ISSUE TITLE
Add "localization in opencast" to contributing.md

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#13]
I haven't seen any references about how translations are managed/done in opencast, which files shall be edited (aka: en_us.json) and what role crowdin plays in all this.
It could be interesting to add a translation howto in contributing.md

**Comment by smarquard** [comment]
I believe you are looking for:

https://docs.opencast.org/develop/developer/localization/

**Comment by mostolog** [comment]
Then it's only about adding "please, apply changes on en_US to be automatically propagated to other localizations by crowdin". ;)
To be honest...I just overlooked developer guide.

**Comment by gregorydlogan** [comment]
That part is already there.  From the page Stephen linked:

The English translation (en-US) acts as source language that is translated to other languages using Crowdin.

**Comment by lkiesow** [comment]
I think @mostolog's point was more about adding a short notice to the [contributing.md](https://github.com/blog/1184-contributing-guidelines) (Github feature) as one item in a short bullet list rather than having a comprehensive guide.
