### ISSUE TITLE
Case mismatch for theodul allowedformats config value

### ISSUE THREAD

**Issue by smarquard** [opencast/opencast#1302]
In:

https://github.com/opencast/opencast/blob/develop/etc/ui-config/mh_default_org/theodul/config.yml#L25

we have allowedformats but it appears to be parsed as allowedFormats here https://github.com/opencast/opencast/blob/develop/modules/engage-theodul-core/src/main/resources/ui/js/engage/models/meInfo.js#L65

**Comment by lkiesow** [comment]
This has been fixed in #1508
