### ISSUE TITLE
NFSv4 can not delete workspace file during ingest checksum update, but NFSv3 can

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#1305]
**Describe the bug**

Ingest new mediapackages with the shared storage is mounted and hard links working on the shared storage using NFS versions 4 or 4.1 and ingest fails with logged error "Unable 
to create event" error within the Admin UI and the following errors are logged to the system log:

> 2019-05-13 12:19:43,889 | ERROR | (AbstractAssetManager:343) - An error occurred
Caused by: java.io.IOException: There is already a file/directory at 
/srv/opencast/workspace/mediapackage/fd30a6b5-85f1-4479-80d0-e84bbf5971b8/a080cf90-a5ac-4036-b9dd-d13c4b56f700/sintel_5min-f3b21166-8a44-4efb-9025-392abeab65e3.mp4
2019-05-13 12:19:43,920 | ERROR | (IndexServiceImpl:556) - Unable to create event: 
org.opencastproject.assetmanager.api.AssetManagerException: Cannot calculate checksum for media package element 
https://lectures.example.com/files/mediapackage/fd30a6b5-85f1-4479-80d0-e84bbf5971b8/a080cf90-a5ac-4036-b9dd-d13c4b56f700/sintel_5min.mp4
Caused by: java.io.IOException: There is already a file/directory at 
/srv/opencast/workspace/mediapackage/fd30a6b5-85f1-4479-80d0-e84bbf5971b8/a080cf90-a5ac-4036-b9dd-d13c4b56f700/sintel_5min-f3b21166-8a44-4efb-9025-392abeab65e3.mp4

Remounting the shared storage using NFSv3 alleviates the problems.

The Unity storage array is minimally configured - the NFS file share is pretty basically configured with both NFSv3 and NFSv4 enabled.

**To Reproduce**
1. Configure NFSv4 with mounts and hard linking
2. Ingest a mediapackage
3. Ingest fails with error in logs

**Environment Information**
 - OS:  Dell/EMC Unity 400
 - Opencast version 6.7 and version 7.5

**Comment by karendolan** [comment]
Appears to be related to https://github.com/opencast/opencast/blob/develop/modules/workspace-impl/src/main/java/org/opencastproject/workspace/impl/WorkspaceImpl.java#L389-L399

Possible troubleshooting threads:
- Opencast has an open file handle on the file that NFSv3 does not detect, but NFSv4 does.
- NFSv4 has stricter/different/additional mount permission config requirements than NFSv3.

Possible approach:
- Replace "FileUtils.deleteQuietly()" with File.delete() to catch exception and parse more details from the underlying issue (bad mount permission (NFS config), open file handle (OC bug), other?)

**Comment by smarquard** [comment]
Is this a single-server or a cluster issue, that is could it be related to NFS filesystem caching, or is it reproducible solely on the admin node?

**Comment by karendolan** [comment]
Hi @smarquard,

I created this issue based on Opencast User google groups post https://groups.google.com/a/opencast.org/forum/#!topic/users/_pJO_4mFC-U . I'm curious about debugging this issue because of past struggles with NFS (legacy system). 

I can't picture how NFS filesystem caching could enable NFSv3 to appear to have deleted a workspace file, but prevent NFSv4 from appearing to delete it.  NFSv4 is supposed to be better about client side caching.

**Comment by karendolan** [comment]
Update from discussion thread is that NFSv4.1 works on CentOS7. So issue is not Opencast.
