### ISSUE TITLE
Theodul player ignores URL parameters

### ISSUE THREAD

**Issue by majosch** [opencast/opencast#1320]
**Describe the bug**
Parameters appended to a theodul player URL are ignored. (see: https://docs.opencast.org/r/8.x/admin/#modules/player.url.parameter/)

**To Reproduce**
1. Go to https://stable.opencast.org and watch a published video
2. Add URL parameters to URL, e.g.:
https://stable.opencast.org/engage/theodul/ui/core.html?id=b76bce85-6eb1-4662-be92-04aa5294dfbd&mode=embed
3. URL parameters are ignored, player still loads with default values

This seems to affect 8.0 only.

**Comment by lkiesow** [comment]
Hi @majosch, you are absolutely right. That was a regression bug. I've submitted a patch that should fix the issue. I've you have time, maybe you can test the patch? If you do, please comment on the pull request.
