### ISSUE TITLE
Sorting by presenters column does not work

### ISSUE THREAD

**Issue by smarquard** [opencast/opencast#1324]
**To Reproduce**

Click on Presenters column in the events list in the Admin UI.

This endpoint:

https://stable.opencast.org/admin-ng/event/events.json?limit=10&offset=0&sort=presenters:ASC

returns a 400 bad request issue.

**Environment Information**
 - Opencast 8.0 (stable.opencast.org)

**Comment by smarquard** [comment]
2020-01-06T15:24:55,400 | WARN  | qtp88794095-30228 | (WebApplicationExceptionMapper:73) - javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
        at org.opencastproject.adminui.endpoint.AbstractEventEndpoint.getEvents(AbstractEventEndpoint.java:2192)

**Comment by smarquard** [comment]
Should be "sort=presenter:ASC" not "sort=presenters:ASC"

**Comment by mliradelc** [comment]
Hi stephen, Last october I submited this issue in the developers group https://groups.google.com/a/opencast.org/forum/#!topic/dev/KCsJKmddM8U 

And I filled a bug in Jira: https://opencast.jira.com/browse/MH-13686

Is still present in 8.0

**Comment by smarquard** [comment]
Thanks for the link @mliradelc. Seems like this should be a simple fix though the admin UI JS is not something I'm familiar with so will leave it for someone who knows that code better.

**Comment by mliradelc** [comment]
I will look into, it should be not so time-consuming fix this

**Comment by mliradelc** [comment]
I just fixed it, I will send the PR in the next hours
