### ISSUE TITLE
Sonatype moved to HTTPS - Opencast won't start anymore

### ISSUE THREAD

**Issue by outofrange** [opencast/opencast#1356]
This might be a major bug, affecting every Opencast instance (re?)started since yesterday!

When starting Opencast, I get the following error ([full log in gist](https://gist.github.com/outofrange/3108dc9dd9fe0910bd9258e5f764d567)):

`Run opencast_main_start
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720) [2:org.ops4j.pax.url.mvn:2.5.4]
java.io.IOException: Error resolving artifact org.ops4j.pax.url:pax-url-wrap:jar:uber:2.5.4: [Could not transfer artifact org.ops4j.pax.url:pax-url-wrap:jar:uber:2.5.4 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file: http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-wrap/2.5.4/pax-url-wrap-2.5.4-uber.jar. Return code is: 501 , ReasonPhrase:HTTPS Required.]`

This is caused by a change Sonatype made yesterday, 2020/01/15: [Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.](https://support.sonatype.com/hc/en-us/articles/360041287334)

I'm using Opencast's allinone Docker distribution and tried both 7.4 and 8.0.

Edit: It seems that this issue is rooted in Karaf itself, not Opencast (explains why I haven't found anything searching for the HTTP URL): https://issues.apache.org/jira/browse/KARAF-6599

**Comment by outofrange** [comment]
"[Already fixed (it will be included in 4.2.8).](https://issues.apache.org/jira/browse/KARAF-6599?focusedCommentId=17016605&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17016605)", as well as in 4.3.0.

**Comment by lkiesow** [comment]
This is possibly also fixed by #1339 since Opencast won't need to download `wrap` any longer. Nevertheless, this should be fixed as soon as possible.

**Comment by lkiesow** [comment]
- #1358 is a quick-fix for the problem without updating Karaf and dependencies (7x)
- #1339 also mitigates the issue since once applied, Opencast will not need to download any additional artifacts (8x)
- Updating Karaf still makes sense and I will look into it for 8x or develop (will see)

**Comment by lkiesow** [comment]
Not upgrading to Karaf 4.2.8/4.3.0 right now [since both versions have not been released yet](https://karaf.apache.org/download.html). Nonetheless, the pull requests linked above will fix the issue.

**Comment by gregorydlogan** [comment]
#1358 and #1339 have been merged.
