### ISSUE TITLE
nc: command not found

### ISSUE THREAD

**Issue by sgnd** [opencast/opencast#1366]
**Describe the bug**
After install opencast on ubuntu 18.04, success installed. But in systemctl status opencast, i got error "line 138: nc: command not found". 

```
Jan 17 15:49:28 node515-opencast.user-domain.cybermantra.xyz systemd[1]: Started Opencast.
Jan 17 15:56:26 node515-opencast.user-domain.cybermantra.xyz systemd[1]: Stopping Opencast...
Jan 17 15:56:26 node515-opencast.user-domain.cybermantra.xyz stop-opencast[20987]: /opt/opencast/bin/stop-opencast: line 138: nc: command not found
Jan 17 15:57:56 node515-opencast.user-domain.cybermantra.xyz systemd[1]: opencast.service: Stopping timed out. Terminating.
Jan 17 15:58:01 node515-opencast.user-domain.cybermantra.xyz systemd[1]: opencast.service: Failed with result 'timeout'.
Jan 17 15:58:01 node515-opencast.user-domain.cybermantra.xyz systemd[1]: Stopped Opencast.
Jan 17 15:58:01 node515-opencast.user-domain.cybermantra.xyz systemd[1]: Started Opencast.
Jan 17 16:04:14 node515-opencast.user-domain.cybermantra.xyz systemd[1]: Stopping Opencast...
Jan 17 16:04:14 node515-opencast.user-domain.cybermantra.xyz stop-opencast[24330]: /opt/opencast/bin/stop-opencast: line 138: nc: command not found
Jan 17 16:05:14 node515-opencast.user-domain.cybermantra.xyz systemd[1]: opencast.service: Main process exited, code=killed, status=9/KILL
```
How to install nc on ubuntu 18.04?
**Environment Information**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Opencast version with minor release: Opencast 9.0.0.SNAPSHOT - feb2e9a

**Comment by gregorydlogan** [comment]
@sgnd Did you install from source, or via package?  You're looking to `apt-get install netcat`.

**Comment by lkiesow** [comment]
Hi Sugeng,

  apt-get install ncat 

…is what you are looking for.

If you did install from the repositorx, that this is an error. In that
case , can you file a ticket on the GitHub issue tracker for Opencast?

Best regards,
Lars

**Comment by sgnd** [comment]
@gregorydlogan @lkiesow I already installed netcat on my server. But still not working. 

Opencast on admin dashboard like this 
![image](https://user-images.githubusercontent.com/15070585/72656356-4a8c2980-39cd-11ea-89ba-cc5b496cebf5.png)

If I want to create event the modal is blank
![image](https://user-images.githubusercontent.com/15070585/72656375-6bed1580-39cd-11ea-9372-2fc4aa10849d.png)

And if I edited the users "Opencast Project Administrator" to "Mejik". After logout and login back to admin, the name not change
![image](https://user-images.githubusercontent.com/15070585/72656650-5d9ff900-39cf-11ea-9d7f-98964deaba2f.png)

**Comment by gregorydlogan** [comment]
@sgnd Did you install and configure ActiveMQ?  And follow through with the rest of the configuration within Opencast?  The Debian packages do not come pre-configured.

**Comment by sgnd** [comment]
@gregorydlogan sure, I installed ActiveMQ, I just follow this documentation https://www.alibabacloud.com/blog/how-to-install-opencast-on-ubuntu-16-04_595198

![image](https://user-images.githubusercontent.com/15070585/72657121-e8cebe00-39d2-11ea-8c56-dc7f32a06868.png)

Is there anything I missed?

**Comment by gregorydlogan** [comment]
Ah, I just noticed that you're installing a develop (9.x) snapshot. Elastic search is also required for that branch and newer. Our documentation has only just recently been updated - and the Alibaba docs are very, very out of date. Try following the docs on docs.opencast.org!

**Comment by sgnd** [comment]
This is an error in console chrome 
![image](https://user-images.githubusercontent.com/15070585/72657807-a1006480-39db-11ea-8ab6-4e6883704d27.png)

![image](https://user-images.githubusercontent.com/15070585/72657815-b6758e80-39db-11ea-9bf2-db7f6cb3799f.png)

**Comment by lkiesow** [comment]
Hi Sugeng,
it's hard to tell what's the problem when looking at this error. The
best chances to find problems are to look for any kind of error in
Opencast's log which are usually located at

  <opencast-dir>/data/log/opencast.log

In general, I would recommend not using `develop` when starting right
now. Unless you want to start development, that is :-)

Here would be the documentation for the latest stable release:

  https://docs.opencast.org/r/8.x/admin/#installation/

–Lars

**Comment by lkiesow** [comment]
I guess the original issue has been solved now.
