### ISSUE TITLE
Error if build from source and using package from this repository

### ISSUE THREAD

**Issue by sgnd** [opencast/opencast#1367]
**Describe the bug**
Using opencast from release in this repository, opencast allinone 8.0.
In netstat -ntlp, i check not port 8080 is running.

![image](https://user-images.githubusercontent.com/15070585/72658661-8089d780-39e6-11ea-9d9c-b399fb854c0e.png)

![image](https://user-images.githubusercontent.com/15070585/72658897-f9d6f980-39e9-11ea-8883-ed7ab9291bf9.png)

**Environment Information**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Opencast version : opencast 8.0

**Comment by gregorydlogan** [comment]
@sgnd You've installed the packaged Opencast 8.0 from pkg.opencast.org right? #1356 affects these packages and (likely) prevents startup. This is probably what's causing your problem in the first image.

For the second image, have you retried the build? Frequently with errors in the admin ui a retry will fix the issue. Frequently, but not always :)

**Comment by sgnd** [comment]
@gregorydlogan I successfully install opencast, but if I check netstat -ntlp opencast not listen on port 8080.
![image](https://user-images.githubusercontent.com/15070585/73063194-d4a62780-3ed0-11ea-93c7-b6fa1e17ba42.png)

and this is opencast log https://pastebin.com/9Fkju7CL

**Comment by lkiesow** [comment]
But port 8080 is correct.
If you want to specify no port (default ports), I would suggest you to follow:
https://docs.opencast.org/r/8.x/admin/#configuration/https/nginx/
Which will guide you through the steps to enable HTTPS for Opencast.

**Comment by lkiesow** [comment]
Looking at the logs, it's the issue @gregorydlogan mentioned earlier. Try running this and then restart Opencast:

    sudo sed -i 's/http:/https:/' /etc/opencast/etc/org.ops4j.pax.url.mvn.cfg

**Comment by gregorydlogan** [comment]
Alternatively, update to the `8.0-3` package version, which natively contains the above fix.

**Comment by sgnd** [comment]
@gregorydlogan @lkiesow thank you for the comment, now I can access the opencast. but still loading on the admin panel. 

The error logs - line 1118 until 1119 (full logs here https://pastebin.com/bRs4Ai9q)
```
2020-01-25T02:01:46,009 | ERROR | (PaxLoggingServiceImpl$1ManagedPaxLoggingService:398) - bundle opencast-distribution-workflowoperation:8.0.0 (80)[org.opencastproject.workflow.handler.distribution.PublishAWSWorkflowOperationHandler(137)] : bind method [setSecurityService] not found; Component will fail
2020-01-25T02:01:46,010 | ERROR | (PaxLoggingServiceImpl$1ManagedPaxLoggingService:398) - bundle opencast-distribution-workflowoperation:8.0.0 (80)[org.opencastproject.workflow.handler.distribution.PublishAWSWorkflowOperationHandler(137)] : bind method [setSecurityService] not found
```
![image](https://user-images.githubusercontent.com/15070585/73114975-35c20f80-3f52-11ea-8b7a-133250b3d589.png)
![image](https://user-images.githubusercontent.com/15070585/73114983-47a3b280-3f52-11ea-95b1-bf6b61939445.png)
![image](https://user-images.githubusercontent.com/15070585/73115096-6dca5200-3f54-11ea-9552-042b66b0ea3f.png)

**Comment by gregorydlogan** [comment]
That's a very weird set of symptoms.  Your admin UI looks like ActiveMQ isn't running properly.  Your log looks like part of the system isn't starting, but there are no other obvious issues.  Are you following the rest of the [basic configuration steps](https://docs.opencast.org/r/8.x/admin/#configuration/)?

**Comment by lkiesow** [comment]
Seems like this should be resolved with the latest versions.
If not, please feel free to reopen this.
