### ISSUE TITLE
Split AdminUI in Java and JavaScript parts

### ISSUE THREAD

**Issue by isabellakutger** [opencast/opencast#1373]
This issue tracks #1373
Need to split the admin ui into two parts:
- the Java backend (remains at admin-ui)
- the JavaScript frontend (moved to admin-ui-frontend)

Purpose of this split is to facilitate migrating from AngularJS (1.x) to Angular (8+) in a new module in parallel to the current admin-ui.

**Comment by pascalseeland** [comment]
Closed by #1371
