### ISSUE TITLE
Opencast Paella player config for ariaLabel that also works in the control button popups.

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#1392]
**Describe the bug**
As an Openacast Paella player user, who does not required special accommodations, but who prefers keyboard commands to the mouse, it would make my life easier to be able to tab navigate and used keyboard control in the rewind, skip forward, captions, switch full screen mode, change resolution, help menu, and playback rate control buttons in the Paella player associated to Opencast.

I realize that adding the "ariaLabel" to the plugin configuration is not enough, because, it leaves some of the people who requie special accommodations into a situation where they cannot keyboard navigate  the control button popups.

It would be helpful to have a solution that works for both of us.

**Comment by mliradelc** [comment]
This seems to be fixed, please reopen if the issue still exists.
