### ISSUE TITLE
admin-ng/event Rest is broken

### ISSUE THREAD

**Issue by CGreweling** [opencast/opencast#1422]
**To Reproduce**
1. Go to 'https://develop.opencast.org/docs.html?path=/admin-ng/event'
**Environment Information**
Opencast Develop 20.02.2020

 - OS: [e.g. iOS 8.1, CentOS 7]
 - Browser [e.g. Safari, Chrome]
 - Opencast version with minor release [e.g. 7.0, 7.2, 7.x if using a branch]
![event-rest-broken](https://user-images.githubusercontent.com/3499600/74933249-e4d3f880-53e3-11ea-991c-4f74bcab1f38.png)

**Comment by lkiesow** [comment]
Likely a regression caused by #1287
