### ISSUE TITLE
opencast-admin-ui(-frontend) does not build on Debian 10

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1424]
**Describe the bug**
Attempting to build the admin UI on Debian 10 displayed errors at PhantomJS startup similar to the following
```
[INFO] 140164897451648:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory 
```

This can be resolved by removing the `openssl_conf = default_conf` line from `/etc/ssl/openssl.cnf`, or starting the build with `OPENSSL_CONF=asdf mvn install...`

**Environment Information**
 - Debian 10, but not Debian 9, or Ubuntu 16, or 18

**Comment by pascalseeland** [comment]
The same issue has appeard at https://github.com/bazelbuild/rules_closure/pull/353/files I like their solution of setting an empty openssl.conf file when running phantomjs during the test. I think this could done in the beginning of the Gruntfile.js where we set the locales ot a fixed value.

**Comment by gregorydlogan** [comment]
I'll give that a shot, thanks @pascalseeland
