### ISSUE TITLE
Translations for Admin Interfac are Missing

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1428]
The admin interface translations did not survive splitting the module:

- https://crowdin.com/project/opencast-community

**Comment by isabellakutger** [comment]
Do @pascalseeland and i need to take a look on that issue? When we committed the split, everything was working fine. The only other commit is from Crowdin Bot (https://github.com/opencast/opencast/commits/develop/modules/admin-ui-frontend/resources) that translated every translation key into english

**Comment by lkiesow** [comment]
This should be resolved by now
