### ISSUE TITLE
Entwine functional library looses List<Field> ordering when converting to JObject

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#1438]
**Describe the bug**
Not sure if this is a bug or an unadvertised feature. When entwine functional library converts a List<Field> to an ObjectJ, if the Field objects are key-value pairs, their iterative ordering from the original List is lost.

The "unadvertised feature" aspect is that the ObjectJ ensures there are no duplicate keys in the List<Field> set of key-values. The bug aspect is that the order of the items in List<Field> is changed when converted into an ObjectJ. Where "List" implies order to the items that is not expected to be lost on ObjectJ conversion.

**How to duplicate **
As an admin/developer, when I want a set of filter options in the Admin UI to display in a special order that cannot be accurately or easily achieved from the Admin UI javascript, I used a LinkedHashMap in my custom ListProvider to create the specific order of key-values in the List<Field>. The special order of the key-value Fields remains intact up until the line "filtersJSON.add(f(f.getName(), obj(fields)));".

The "obj(field)" takes an ordered List<Field> and converts it into a JObject for easy JSONification. While converting it to a JObject, the entwine library parses Field key-values into a common HashMap that does not maintain the order of the original input List.

The result is that the List<Field> intentional ordering is lost after being converted into a JObject. Also, the set of key-values converted into the JObject are not ordered in any way (i.e. not even alphabetically) when output to JSON.

**Comment by lkiesow** [comment]
This behavior absolutely makes sense. If you want to preserve order in JSON, you must use an array instead. From [RFC7159, The JavaScript Object Notation (JSON) Data Interchange Format](http://www.rfc-editor.org/rfc/rfc7159.txt):

> An object is an __unordered collection__ of zero or more name/value
> pairs, where a name is a string and a value is a string, number,
> boolean, null, object, or array.
>
> An array is an __ordered sequence__ of zero or more values.

So, when you use a JSON object, you can never be sure how things are ordered and you should never assume any particular order.

**Comment by karendolan** [comment]
> This behavior absolutely makes sense. If you want to preserve order in JSON, you must use an array instead. From [RFC7159, The JavaScript Object Notation (JSON) Data Interchange Format](http://www.rfc-editor.org/rfc/rfc7159.txt):
> 
> > An object is an **unordered collection** of zero or more name/value
> > pairs, where a name is a string and a value is a string, number,
> > boolean, null, object, or array.
> > An array is an **ordered sequence** of zero or more values.
> 
> So, when you use a JSON object, you can never be sure how things are ordered and you should never assume any particular order.

But, the Entwine lib "obj()" *is* (re)sorting the attributes of the object and it shouldn't be. It should leave the attributes in whatever order that they came in, as every other part of the code and JS does.

I'm Ok with wrapping this issue argument up with the JSON spec argument that all the Entwine library function objects, such as the "obj()" when fed a Java LIST,  adhere  RFC7159, in that LISTs of object attributes will be resorted in natural key ASC order before serializing the List of objects into a JSON string.

**Comment by lkiesow** [comment]
I agree that it doesn't make a lot of sense to resort the keys but it's technically okay to do so since according to the specification you can never assume any given order. Any JSON parser/serializer changing the order in any way is just fine and as a developer, you should assume that's what all these libraries do since that's fine according to the spec.

The same would not hold for JSON arrays since they are ordered according to the spec.
