### ISSUE TITLE
BigBlueButton Integration Needs Updating

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1472]
**Describe the bug**
BBB old docs: https://code.google.com/archive/p/bigbluebutton/wikis/MatterhornIntegration.wiki
BBB new docs: https://docs.bigbluebutton.org/

@lkiesow has looked most at this and says it likely needs a rewrite, which considering the vintage of the old docs is likely.

Needs:
* New integration
* OC docs?
* BBB docs
* Bug BBB to remove old docs

**Comment by lkiesow** [comment]
So…

- I have BigBlueButton
- I have Opencast
- I am a developer

…and here is a working integration of both tools:

  https://weblog.lkiesow.de/20200318-integrate-bigbluebutton-opencast/

It can certainly be extended further but will work just fine.

Best regards,
Lars

**Comment by lkiesow** [comment]
Apart from the already linked integration. we will publish additional integrations soon. But since they come with additional code, they will be published separately. Hence, I'm closing this.
