### ISSUE TITLE
Drop the beta label from Opencast Studio in 8.x

### ISSUE THREAD

**Issue by smarquard** [opencast/opencast#1481]
Not sure if this belongs here or in the Studio github.

Opencast Studio is now part of 8.x and in production I'm certain in quite a few sites (we deployed it today), so it would be good to drop the BETA label in the banner, top-left.

It's now released, plus beta feels a little old-fashioned in the age of continuous updates.

**Comment by lkiesow** [comment]
Opencast just includes Studio as-is. Studio ist still marked as beta. Please report the issue in the Studio issue tracker.

**Comment by smarquard** [comment]
https://github.com/elan-ev/opencast-studio/issues/503

**Comment by lkiesow** [comment]
thanks
