### ISSUE TITLE
Error when encoding video with odd pixel count in height

### ISSUE THREAD

**Issue by t-schroeder** [opencast/opencast#1486]
**Describe the bug**
When I upload a video with an odd height, e.g. 1063px it is successfully encoded to 360p, 480p and 720p, but encoding to 1080p fails with:

> \[libx264 @ 0x64b4140\] height not divisible by 2 (1890x1063)
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or heigh

This causes the entire workflow to fail.

**To Reproduce**
Upload a video with an odd height using the default "schedule-and-upload" workflow and select at least one encoding profile that would produce a video with height larger than that of the original video.

**Environment Information**
 - OS: CentOS 7
 - Opencast: 8.1, 8.2

**Comment by t-schroeder** [comment]
This can be fixed by conditionally adding 1px of padding or cropping by 1px as shown here: https://stackoverflow.com/a/20848224

Padding:
```
pad='width=ceil(iw/2)*2:height=ceil(ih/2)*2'
```

Cropping:
```
crop='floor(iw/2)*2:floor(ih/2)*2'
```

I noticed this has already been fixed for another encoding profile in #1269 through cropping. So should we use cropping here as well?

**Comment by gregorydlogan** [comment]
@t-schroeder if the fix in the stackoverflow link fixes it for you I don't see why it wouldn't be the right solution.  A pixel or two in either direction probably isn't the end of the world.  Can you file a pull request altering the appropriate encoding profiles?

**Comment by t-schroeder** [comment]
I've made a pull request.
