### ISSUE TITLE
Deal with series with the same title consistently

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/opencast#1493]
The admin UI lets us create two series with the same title, but then we can only select one of them (basically a random one) in the series combo box in the meta tab of the (new) event details modal.

I'm not sure where the bug here is, but at least this behavior is inconsistent. I think we should enforce unique titles across series, but another possibility would be to fix the wizards, i.e. let them show both series while also making them distinguishable somehow. (Just listing the same title twice is no more useful than what we have now IMO.)

**Comment by karendolan** [comment]
HI @JulianKniephoff our site has been using the course title for the Opencast series title for some years now. The series Id is unique `<academic-year><academic-term-code><course registrar number>` but the series title is the same across terms. I wonder if other sites do this as well. Enforcement of a unique series title would cause us trouble to work around.

We get around the series dropdown issue in the admin UI with a custom "extended-series-name" list provider that puts the series title plus its academic term in the value and the series id as the key. The dropdown shows the same series title, but, it has the academic term next to it to distinguish which term.

That seems very specific to us. I don't know where other  sites store the equivalent of the academic term in the series metadata (creation date?).

**Comment by mliradelc** [comment]
This is the same as the bug #3600
