### ISSUE TITLE
Featurerequest: tag WOH should handle *-flavors as target flavor

### ISSUE THREAD

**Issue by wsmirnow** [opencast/opencast#1513]
Currently the [tag WOH](https://docs.opencast.org/develop/admin/#workflowoperationhandlers/tag-woh/) can handle multiple source flavors with the `source-flavors` option by setting `*` as flavor type, subtype or separate it by a collon. But you can not use the same sheme in `target-flavor` option. I would like to have an `target-flavors` option, that can handle the `*`-flavors.  Let me give you an example:

```
<operation
      id="tag"
      description="Tagging source videos for processing">
      <configurations>
        <configuration key="source-flavors">*/source</configuration>
        <configuration key="target-flavors">*/work</configuration>
        <configuration key="copy">true</configuration>
      </configurations>
    </operation>
```

**Comment by mtneug** [comment]
We have used the `clone` operation for this. But I agree that `tag` should be able to handle this.

**Comment by wsmirnow** [comment]
The tag operation should also handle target flavor wildcards in sub type, like this example:

```
<operation
  id="tag"
  description="Tagging source videos for processing">
  <configurations>
    <configuration key="source-flavors">security/*</configuration>
    <configuration key="target-flavors">security-drop/*</configuration>
  </configurations>
</operation>
```
