### ISSUE TITLE
PaellaPlayer with HLS broken on iOS/MacOS

### ISSUE THREAD

**Issue by t-schroeder** [opencast/opencast#1527]
**Describe the bug**
Since upgrading to Opencast 8.2 HLS hasn't been working with the PaellaPlayer on iOS and macOS devices.

**To Reproduce**
1. Configure HLS as the only streaming protocol in the Paella config.
2. Try to watch a video on an iOS or MacOS device.

=> The loading animation just keeps spinning forever.

**Environment Information**
 - OS: iOS 12.4.5, iOS 13.3.1, macOS 10.15.3
 - Browser: [I don't know. I let others test this as I don't have an Apple device on hand. They didn't say which browser they used.]
 - Opencast: 8.2, 8.3

**Comment by t-schroeder** [comment]
On the Paella Player demo page the HLS video works on iOS apparently. So looks like it's not an issue in the player.

**Comment by mliradelc** [comment]
Hi, can you show what the developer console in your browser shows when you load the paella player?

**Comment by t-schroeder** [comment]
Sorry, forgot to update this: It's fixed since Opencast 8.4, it was only broken on 8.2 and 8.3 apparently. Unfortunately I don't have an iOS/MacOS device myself to analyze the problem further. Neither do I have access to the filesystem on our Opencast server. So it could theoretically also just have been something with the config files.

Anyway, since it works now (in 8.4 and 8.5) I'm going to close this.
