### ISSUE TITLE
Docs ask for openjdk-8-jdk which does not exist on modern Linux distros

### ISSUE THREAD

**Issue by alevchuk** [opencast/opencast#1529]
**Describe the bug**
I'm on debian Stretch trying to follow https://docs.opencast.org/r/8.x/admin/#installation/source-linux/#install-dependencies

The doc explicitly said to install:
* java-1.8.0-openjdk-devel.x86_64 / openjdk-8-jdk

Are later versions supported (e.g. openjdk-11-jdk)

**Environment Information**
 - OS: Linux opencast 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
 - Opencast version with minor release 8.3

**Comment by lkiesow** [comment]
We just discussed this. @gregorydlogan, I'm assigning this to you.

**Comment by gregorydlogan** [comment]
@alevchuk The installation from Debian packages docs have been updated to get the right bits for JDK 8 in place.  Opencast does not currently support JDK 11, but will with Opencast 9, currently planned for December.

Installation from source is generally an experts only deal - if you're going to all the trouble of building from source you probably already know that JDK 8 is quite old, and thus are expecting to have to jump through some hoops to get it installed.

**Comment by lkiesow** [comment]
@gregorydlogan, do you want to keep this open to reminf you about the debian packages?
Because this is already fixed in Opencast itself since `develop` can run just fine with current JCM versions.

**Comment by gregorydlogan** [comment]
Yep, I'm working on this.

**Comment by lkiesow** [comment]
Seems like this [is now documented](https://docs.opencast.org/r/8.x/admin/#installation/debs/).
Therefore, I'm closing this issue.
