### ISSUE TITLE
Remove/Unpublish attachment (captions file)

### ISSUE THREAD

**Issue by NgoniChoga** [opencast/opencast#1537]
**Feature request**
We currently do not have the ability to remove or unpublish an attachment such as a captions file.
None of the current [workflow operations](https://docs.opencast.org/r/8.x/admin/#workflowoperationhandlers/) seem to be able to achieve this goal. See question on the [google group](https://groups.google.com/a/opencast.org/forum/#!topic/users/iqYCPJBQNfQ).

**To Reproduce**
1. Go to admin ui.
2. Click on open event details action.
3. Click on the assets tab, then "add asset"
4. Add a Captions WebVTT file.

There is then no way to remove this file after the fact, in the UI or using a workflow operation.

**Comment by wsmirnow** [comment]
Hhi @NgoniChoga ,
you can remove the archive tag and make a snapshot using the workflow. This two operations will do it for you: [tag WOH](https://docs.opencast.org/r/16.x/admin/#workflowoperationhandlers/tag-woh/) and [snapshot](https://docs.opencast.org/r/16.x/admin/#workflowoperationhandlers/snapshot-woh/).

**Comment by mtneug** [comment]
As @wsmirnow said, you can write a workflow to create a snapshot that does not contain the elements you no longer want. Note that old snapshots will still contain the elements you removed. You may want to use the [`asset-delete`](https://docs.opencast.org/r/16.x/admin/#workflowoperationhandlers/asset-delete-woh/) operation to remove old snapshots.
