### ISSUE TITLE
Adding write access parameter to Events endpoint and Series endpoint

### ISSUE THREAD

**Issue by otti-ssystems** [opencast/opencast#1541]
There have to be the possibility to pass a write access parameter to the Events endpoint and the Series Endpoint.
If passed, the Events endpoint and the Series Endpoint should only response results with permission "write access".

**Environment Information**
- opencast 8.3

Ticket is related to :
https://github.com/opencast/opencast/pull/1063
and
https://github.com/opencast/opencast/pull/209

**Implementation**

EventsEndpoint.java

- Adding the parameter "onlyWithWriteAccess" to the Events Endpoint getEvents(...)
- when parameter is passed as true we are querying with Permissions.Action.WRITE

_**Attribut**_
isRequired = false 
description = "Whether only to get the events to which we have write access." 
type = Type.BOOLEAN

- additional function deserializeMetadataList for deserialize and mapping the catalogs json to a list

further :

SeriesEndpoint.java

- Adding the parameter "onlyWithWriteAccess" to the Series Endpoint getSeriesList(...)
- when parameter is passed as true we are querying with Permissions.Action.WRITE

Merge Request in Progress...

I think you will categorize as feature?
So request should go into develop or should i offer the request to 8.3 / 8.x?

Greetz

Otti

**Comment by gregorydlogan** [comment]
This, to me, sounds like a minor feature.  @KatrinIhler, @mliradelc thoughts?

**Comment by KatrinIhler** [comment]
What endpoints are we talking about here? If it's the api, this would probably also require a new api version.
Either way, yeah, I think that's a feature and should go into develop.

**Comment by otti-ssystems** [comment]
Hi.
Yes, we are influencing the endpoints of the external api.
I already created the pull request locally, but i need a branch with the reference number to commit.

Can you please tell me how to do it, then you can have a look at the request.

THX a lot

**Comment by gregorydlogan** [comment]
@otti-ssystems if you have the code, follow along at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.  File it against `opencast/opencast`'s `develop` branch.

**Comment by otti-ssystems** [comment]
@gregorydlogan thank you. Thats what i was looking for

**Comment by LukasKalbertodt** [comment]
~~#1541~~ #1548 seems to close this issue?

An open question is whether we want to backport this to 8.x. [This Studio PR](https://github.com/elan-ev/opencast-studio/pull/570) depends on this new API feature to work. Studio targets 8.x right now, so we can't really add this feature to Studio without this API landing in 8.x. I don't really care either way.

@KatrinIhler @gregorydlogan any opinions?

**Comment by gregorydlogan** [comment]
@LukasKalbertodt... This ticket is 1541? :D

Re: back porting to 8.x, I don't have strong opinions since this is additive only, but if #1615 has to go into develop I have to think this should too. That being said, the final decision belongs to the RMs

**Comment by LukasKalbertodt** [comment]
@gregorydlogan Oopsie, I fixed my comment now :P

**Comment by KatrinIhler** [comment]
@LukasKalbertodt I don't have a strong opinion right now either, maybe bring this up at the next technical meeting?

**Comment by LukasKalbertodt** [comment]
We (including @rrolf) discussed this internally and decided against backporting this to 8.x. Adding a new parameter to the external API would require a new API version which is not something we want to do in minor version bumps. 

So this issue can be closed and the Studio PR/feature has to wait till 9.x.

**Comment by mtneug** [comment]
This is not only relevant for Studio! Why not leave it open for 9.x?

**Comment by mtneug** [comment]
Ups, missed #1548 🤦‍♂️
