### ISSUE TITLE
Workflow progress reporting

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/opencast#1545]
Since we have the upload progress now, I hear more and more people wondering why we can't report on the progress of a workflow. Of course, this is a much more difficult problem; in a sense it's even [impossible](https://www.youtube.com/watch?v=LyS6CGJA0eI), but there might be some practical approximations we might want to investigate.

**Comment by mtneug** [comment]
Is this a duplicate of #1533? (thank for linking to my talk by the way 😄).

**Comment by JulianKniephoff** [comment]
Oh, you're right, thanks. Admittedly I didn't really look whether a corresponding issue already existed. Closing as duplicate. :sweat_smile:
