### ISSUE TITLE
studio can not upload videos if upload.acl=false and user is not an ADMIN

### ISSUE THREAD

**Issue by miesgre** [opencast/opencast#1556]
**Describe the bug**
If `upload.acl=false`, the `/ingest/ingect` call will fail if the user is not an admin.

**To Reproduce**
You can test it in online opencast servers creating a regular user with `ROLE_STUDIO` and try to record a video with that user and `upload.acl=false`
You can pass the parameter in the url to force it: https://develop.opencast.org/studio/?`upload.acl=false`

**Environment Information**
 - OS: OSX
 - Browser: Chrome, Safari
 - Opencast version with minor release: 8.x

**Comment by lkiesow** [comment]
This is not a bug. If your user has no access to the event, operations that do need access will fail. If you do not provide an ACL, the global default will be used. The global default allows access for `ROLE_ADMIN` only.

**Comment by LukasKalbertodt** [comment]
I guess I can clarify that in the studio docs. Something like "If you set `acl=false`, you have to make sure your series ACL will grant appropriate rights to all studio users. Otherwise users won't be able to ingest from Studio." or something like that.

**Comment by miesgre** [comment]
So @LukasKalbertodt, If I use `upload.acl=false` and upload a video to the `SERIES_1` series `upload.seriesId=SERIES_1` and user has write permissions on that series. The user can call to `/ingest/ingest` without problems?

**Comment by LukasKalbertodt** [comment]
@miesgre As far as I know yes. I could be wrong tho :/ Will find out and answer here again in a few hours, unless Lars is quicker and explains this to us ^_^

**Comment by lkiesow** [comment]
The metadata of an event (series is event metadata) has nothing to do with being able to access `/ingest/*`. That's unrelated.  It's the same for ACLs.

However, once you persist your access rules (e.g. using the asset manager) these rules will be enforced. If you give no access to the user executing the workflow and the workflow tries to access those data again later: Access will be denied.

**Comment by LukasKalbertodt** [comment]
Ok apparently I was wrong. The workflow operation will indeed fail if the user is not admin, as the series ACL is only applied within the workflow. So yes, `acl=false` will lead to only admins being able to upload stuff correctly. I will add a note to the Studio configuration docs.
