### ISSUE TITLE
Basic Authentication for external API not working when CAS enabled

### ISSUE THREAD

**Issue by Meridiana** [opencast/opencast#1579]
I have a working CAS configuration (from security_sample_cas.xml-example).
I have a working "Basic" configuration (mh_default_org.xml).

With CAS configuration every API request gets redirected to CAS. So I uncommented basic authentication as described in the documentation https://docs.opencast.org/r/8.x/admin/#configuration/external-api/#authentication
Now CAS authentication ist working fine but every API access returns "Bad credentials".

After switching to the "Basic" configuration, my API requests are working fine, but I have no CAS authentication for my users.

**To Reproduce**
1. copy the CAS Example, enter your CAS URLs, uncomment <ref bean="basicAuthenticationFilter" />
2. Restart opencast
3.  curl --user user:secret -L http://<server>/api/info/me
4. See error: Bad credentials

**Environment Information**
 - OS: Ubuntu 18.04
 - Opencast version with minor release 8.3.0

**Comment by lkiesow** [comment]
> copy the CAS Example, enter your CAS URLs, uncomment 

You can't just copy and uncomment the CAS example. You need to merge the regular security configuration and the CAS configuration example manually. It is not kept current with the main configuration file.

Please re-open this if the file was properly merged and the issue still pops up.
