### ISSUE TITLE
Write permission removal for Non Admin Users on ACL Templates

### ISSUE THREAD

**Issue by urzbs** [opencast/opencast#1616]
University of Heidelberg here,

We want to inform you that there is a critical bug messing with our Users:
When a non admin user selects an ACL template for his own Event, the User loses his own write permissions to this specific event. Loosing the permission to even further configure their own event. (Because it disappears from admin-ui)

**To Reproduce**

0. Use a non admin user, upload a video.
1. Go to 'event-details:access policy'
2. Click on 'template' and select any ACL Template
3. See Problem

**Environment Information**
 - OS: [CentOS 7]
 - Browser [all]
 - Opencast latest

**Comment by lkiesow** [comment]
I can confirm this happens on stable.opencast.org.
Likely an admin interface issue.
