### ISSUE TITLE
Google speech transcription service keeps generating errors when mediapackage deleted

### ISSUE THREAD

**Issue by tyfranck** [opencast/opencast#1664]
Currently when a mediapackage with a scheduled transcription job is deleted before the transcription job ends (transcript attached to the mediapackage), the service will indefinitely generate errors as it is not able to find the mediapackage.

Correct behaviour: transcription should stop trying to attach transcript to mediapackage if it doesn't exist and inform the user.

[Issue reported by Carter Wallace. ](https://groups.google.com/a/opencast.org/forum/#!topic/users/hKsO26lLTuE)

**Comment by karendolan** [comment]
fixed in develop branch via commit c87ef69.
