### ISSUE TITLE
External API user password does not work when created via the admin interface

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#1669]
When you create a new user via the admin UI, to use with the external api, the user gets it's password encrypted via the new security mechanism ( bcrypt ? ) and this does not work using the external api. 

You can however change the password directly in the DB and use the old MD5('password{username}') mechanism and this works when using the external API. 

**Environment Information**
 - Opencast version 8.x ( latest build )

**Comment by lkiesow** [comment]
Checked this and could not reproduce this.
Most likely, you have an invalid security configuration.
Among other things, make sure you have a proper password encoder configuration:

https://github.com/opencast/opencast/blob/0cc396ffc5ecb0bd75fb2c3367a512dfff5bfd12/etc/security/mh_default_org.xml#L702-L707

**Comment by kristofkeppens** [comment]
Correct, my apologies. My security config didn't include these changes.
