### ISSUE TITLE
External api search filter can't handle 

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#1672]
**Describe the bug**
A clear and concise description of what you see:
*When I click on X I get an error message that looks like Y instead of …*

**To Reproduce**

**Environment Information**
 - OS: [e.g. iOS 8.1, CentOS 7]
 - Browser [e.g. Safari, Chrome]
 - Opencast version with minor release [e.g. 7.0, 7.2, 7.x if using a branch]

**Comment by lkiesow** [comment]
I'm assuming this was an attempt at creating #1673.
Closing this.
