### ISSUE TITLE
Ubuntu Repository ist missing Packets for worker node (cover-image)

### ISSUE THREAD

**Issue by CGreweling** [opencast/opencast#1682]
**Describe the bug**
A clear and concise description of what you see:
*When I click on X I get an error message that looks like Y instead of …*

**To Reproduce**
1. Install Opencast via Repository on Ubuntu
2. Install a distributed system
3. Start the standard Workflow with a video
4. coverimage operation fails

**Environment Information**
 - OS: Ubuntu
 - Opencast version 8.5 worker node

**Workaround**

- sudo apt-get install openjdk-8-jre 
  -- only openjdk-8-headless is installed
- then you get ``` Error handling operation 'Generate': java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWra ```

- edit  /etc/java-8-openjdk/accessibility.properties
``` 
sudo vim /etc/java-8-openjdk/accessibility.properties
 Comment out the following line:
assistive_technologies=org.GNOME.Accessibility.AtkWrapper
```
as descirbed here ``` - https://github.com/microsoft/vscode-arduino/issues/644
```

**Comment by lkiesow** [comment]
The OS was Ubuntu 18.04, correct?

**Comment by gregorydlogan** [comment]
Sigh.  This is a recent change that I thought I had tested.  It's present in 7.7-2, 8.4-2, and 8.5-2.  Will fix shortly, fix will appear in 7.7-3, 8.5-3.

**Comment by gregorydlogan** [comment]
Fixes pushed, will try and test tomorrow. @CGreweling if you can confirm as well that would be good!

**Comment by gregorydlogan** [comment]
Verified to be working locally.
