### ISSUE TITLE
Removing a series from an event does not work

### ISSUE THREAD

**Issue by ebbertd** [opencast/opencast#1721]
**Describe the bug**
Given that an event is part of a series. Removing the series does not work.

**To Reproduce**
1. Create a series in Opencast
2. Upload an event and choose the previously created series, wait for processing
3. Go to the metadata tab and edit the series, choose in the drop down menu: -- No option selected --
4. Wait for the green checkmark
5. Close the event details
6. The event should now be without a series, however, the previous series is still assigned to the event

**Environment Information**
 - OS: Arch Linux
 - Browser: Firefox 78
 - Opencast 8 (stable.opencast.org at 29.07.2020)

**Comment by lkiesow** [comment]
Transferred data looks fine.
The problem is somewhere in the backend:

set:
```json
[{
"flavor":"dublincore/episode",
"title":"EVENTS.EVENTS.DETAILS.CATALOG.EPISODE",
"fields":[
   {"translatable":false,"readOnly":false,
    "id":"isPartOf",
    "label":"EVENTS.EVENTS.DETAILS.METADATA.SERIES",
    "collection":{"Blender Foundation Productions":"63517a94-473a-4e7d-a66f-ff62a5c097cf","Testing":"de2fe0e3-fd48-49c5-a6ea-3c84db3dd58f"},
    "type":"text",
    "value":"de2fe0e3-fd48-49c5-a6ea-3c84db3dd58f",
    "required":false,
    "tabindex":8}]}]
```

delete:
```json
[{
"flavor":"dublincore/episode",
"title":"EVENTS.EVENTS.DETAILS.CATALOG.EPISODE",
"fields":[
   {"translatable":false,
    "readOnly":false,
    "id":"isPartOf",
    "label":"EVENTS.EVENTS.DETAILS.METADATA.SERIES",
    "collection":{"Blender Foundation Productions":"63517a94-473a-4e7d-a66f-ff62a5c097cf","Testing":"de2fe0e3-fd48-49c5-a6ea-3c84db3dd58f"},
    "type":"text",
    "value":null,
    "required":false,
    "tabindex":8,
    "saved":true}]}]
```

---

_Unrelated: Why are we sending the collection to the backend. That doesn't make no sense_

**Comment by ituneslmu** [comment]
Can confirm this bug; happening on our instance as well (also on opencast 8)

**Comment by mliradelc** [comment]
@ebbertd Seems to be fixed, should I close it?

**Comment by ebbertd** [comment]
This has been fixed.
