### ISSUE TITLE
roles in User details appear twice

### ISSUE THREAD

**Issue by mheyen** [opencast/opencast#1723]
**Describe the bug**
When I edit `User details `-> `Roles`, and scroll down the list of roles, I encounter a bug. 
When I scroll down, the list resets and I start on top again. 
Roles which are already assigned to that user are not filtered anymore. 
They occur twice (under `Roles` and `Selected roles`). 
When I add the role again, it appears twice under `Selected roles`. 
When I submit the changes, the role appears only once (as intended). 

**To Reproduce**
_(this only works with roles rather at the end of the list, probably because the list has to reset first after scrolling down)_
1. Go to `Organization`
2. Click on `+ Add user` (insert details, e.g. Username, etc.)
3. Click on `Roles` 
4. Add role  e.g. "ROLE_UI_USERS_VIEW" (last role in the list)
5. Submit user
6. Edit User and go to `Roles` 
7. Scroll down to e.g. "ROLE_UI_USERS_VIEW"
4. See error (the role appears twice)

![Issue](https://user-images.githubusercontent.com/23011761/88779223-d0add780-d189-11ea-9b27-d956faeabeca.png)

**Environment Information**
 - OS: Ubuntu 20
 - Browser: Firefox 78
 - Opencast r/8.x (stable.opencast.org at 29.07.2020)
   (I could _not_ reproduce this bug under develop.opencast.org, 29.07.2020)

**Comment by gregorydlogan** [comment]
IIRC someone (@KatrinIhler?) changed something in that modal in develop. Probably worth seeing what can be back ported if this doesn't happen in develop.

**Comment by KatrinIhler** [comment]
@gregorydlogan I did make some major changes to the way roles are loaded for the admin UI in develop, mostly contained in #1046 and #1032.

Probably one of these also fixed the bug described here. But as they were bigger changes, I didn't feel confident to point them at 8.x. And it might be hard to extract the relevant bits (if that's even possible).

@mheyen Maybe you could check if those changes fix your problem?

**Comment by lkiesow** [comment]
Seeing that this is fixed in `develop` and no one really seems to complain so far, I'll close this. Feel free to re-open this if necessary.
