### ISSUE TITLE
One place for streaming configuration

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1799]
Most of the streaming configuration lives in `org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.cfg` except for a few bits which continue to be in `custom.properties. If possible, all of the configurations should be at one place though:

https://github.com/opencast/opencast/blob/4f538f328d0974001fa97e477c097a6b70fb6cbd/etc/custom.properties#L88-L98

**Comment by pankajanand26** [comment]
@lkiesow How do I get to know about the project more and setup in order to contribute to the issue. This is my first attempt at contributing to open source so I will need some help. Please guide. Thanks

**Comment by gregorydlogan** [comment]
@pankajanand26 take a look at https://docs.opencast.org/develop/developer/

At minimum you need JDK8, ffmpeg, and maven to build.  Runtime needs activemq and elasticsearch as well.  The two config files Lars mentions live in `etc`, the code lives in `modules/distribution-service-adaptive-streaming-wowza`.

**Comment by pankajanand26** [comment]
@gregorydlogan  I was checking this code from this wowza module and the custom properties file , do you want to directly read from `karaf.data` system property in the streaming-wowza module and remove streamin directory property from custom.properties file?

**Comment by lkiesow** [comment]
My complaint was that most streaming related configuration live in a specific service related configuration file (which makes sense, so that not a million different options live in the global one) but there are still a few left in the global `custom.properties`.
They should all go into `etc/org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.cfg`.

Note that `…streaming.formats` is used by `PublishEngageWorkflowOperationHandler` though it always has an OSGi connection to the streaming distribution service. Hence, exposing that Option means slightly adjusting the service's API.

In the end, use you own judgement. If it seems an unreasonable overhead to move one of the options. That's okay.
