### ISSUE TITLE
Ingested mediapackage name is null

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#18]
Running OC 3.0, during ingestion log displays:

2017-06-28 09:56:19,394 | INFO | (IngestServiceImpl:520) - Ingesting mediapackage 8570483592947531776 is named 'null'

Although we scheduled the event with a title:
> {id:'title',label:'EVENTS.SERIES.DETAILS.METADATA.TITLE',type:'text',value:'dummytext'}

As @smarquard commented on list:
> We see that on our 2.3.x ingest servers, so it’s at least expected if a little misleading.
>
> Probably the ingest code has not loaded the mediapackage Dublin Core from episode.xml so the title is null at that point.
>
> Probably the log line should be changed to just remove the title. There isn’t much value in having it in the ingest node logs.

**Comment by lkiesow** [comment]
The decision was made to not migrate to Github but stay with Bitbucket and Jira.
If this  issue still persists, can you please open a ticket at
https://opencast.jira.com
