### ISSUE TITLE
Broken logging in OpencastLdapAuthoritiesPopulator

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1835]
LDAP generates nonsensical logs like this

```
2020-09-11 20:26:41,660 | DEBUG | (OpencastLdapAuthoritiesPopulator:383) - (493427089) user attributes for user {}:
        {}
2020-09-11 20:26:41,660 | DEBUG | (OpencastLdapAuthoritiesPopulator:383) - (493427089) Looking for attribute name '{}'
2020-09-11 20:26:41,663 | DEBUG | (OpencastLdapAuthoritiesPopulator:383) - (493427089) Returning user {} with authorities:{}
```

This is caused by custom logging functions with non-matching log messages:

https://github.com/opencast/opencast/blob/d653bfe7b17dc2390333ee331bc6f8388880a6d0/modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/OpencastLdapAuthoritiesPopulator.java#L331-L333

We should just remove the custom functions and simply use the default logger like we do everywhere else.

**Comment by haridevelops** [comment]
Can I work on it?
If so please assign it to me.

**Comment by gregorydlogan** [comment]
Sure thing. Be aware that if this isn't done by end of October it will likely be unassigned as part of the cleanup after Hacktoberfest

**Comment by haridevelops** [comment]
Sure. @gregorydlogan

**Comment by lkiesow** [comment]
@haridevelops, if you want to test this and need a public LDAP server to use, here is a working configuration for the current state of `develop`:

- https://data.lkiesow.io/opencast/ldapconfig/develop-2020-09-11/

It provides a few users to test with. For example `jmacy` with password `password`.

EDIT: We are also planning a review day this Friday. So probably lots of developers in the IRC channel (see docs.opencast.org landing page for details) of Opencast to talk to if you want.
