### ISSUE TITLE
Wrong capture agents selected in the admin UI for new events

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast#1845]
**Describe the bug**

When creating a new event in the admin UI, the capture agent dropdown in the scheduling tab appears to be broken:

- Sometimes the capture agent you pick out isn't the one that's actually set.
- Sometimes a capture agent can't be picked, instead there's an error in the console: "Uncaught TypeError: this.form_field.options[a.options_index] is undefined". This appears to be the case if you pick the last capture agent in the list.

Both errors only occur if you change your mind _after_ you've already picked a capture agent once; the first time works just fine.

This seems to be a similar error as #1357 and can most likely be fixed in a similar way.

**To reproduce**
- Add a new event via the admin UI
- Choose "Schedule Single" or "Schedule Multiple" in the source tab
- In the scheduling tab, change capture agent selection more than once (!) via the dropdown menu
- Watch the conflicts requests in the network tab of your developer tools to see which capture agent is _actually_ chosen
- Or watch the console for errors
- You need to have at least two capture agents available to reproduce this bug

**Not affected**
- The scheduling tab in Event Details is not affected, most likely because the dropdown menu seems to be reset after each selection.
- Edit Scheduled Events is likewise not affected - though there is another bug that makes this tricky to test (see #1847).

**Environment Information**
 - OS: Ubuntu 20.04
- Browser: Firefox
 - Only 8.x and develop are affected, this bug does _not_ exist in 7.x

**Comment by gregorydlogan** [comment]
Fixed with 7054d34
