### ISSUE TITLE
[Confirmed][BLOCKER BUG] Endpoint /search/add crashes in presenter Node

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#1860]
**Describe the bug**
From the last 3 weeks, I found a very nasty bug when I was reviewing a PR using a cluster with 3 nodes (Admin, worker, presenter).

The bug appears when the endpoint /search/add is used, this is the error message:

```
> (InjectionUtils:568) - Parameter Class org.opencastproject.mediapackage.MediaPackageImpl has no constructor with single String parameter, static valueOf(String) or fromString(String) methods
```

I tried again using a fresh install of Opencast from the development branch (Using the default security and configuration for nodes) and I had the same problem.

Trying to use the debbuger doesn't works because this error comes before calling the lines of the search/add endpoint  

**To Reproduce**
1. Install opencast 'develop' as a cluster
2. Try to upload a new video

Will fail in the publish-engage step

*Alternatively:*
1. Enter to the presenter mode
2. Go to the search endpoint webinterface
3. Try the `search/add` endpoint with the default example.

Normally should give a 400 error (Bad request), But instead gives a 500 error (Internal server error).

**Environment Information**
 - OS: CentOS 7 (3 Servers in the same network)
 - Opencast develop branch
- Run and built with Java OpenJDK Runtime Environment (build 1.8.0_262-b10)

**Linked OC groups thread:** https://groups.google.com/a/opencast.org/g/dev/c/3dhlEbXtNKo

**Comment by mliradelc** [comment]
Hello?

**Comment by karendolan** [comment]
Hi @mliradelc I'll take a peak at this. The fact that it only happens in a cluster deploy implies that something is going on with a remote to impl, or the Engage node is missing a critical module deploy. 
- Remote endpoints tend to be a stripped down version of their Impl endpoint and are sometimes is missing critical pieces. 
- Likewise, when modules are renamed and re-arranged, node deploy profiles might miss an update or get a typo on the new module name. 
These are the 2 areas I'll look at.

**Comment by karendolan** [comment]
I think I found it, the SearchRestService is missing jaxb annotation for the MediaPackageImpl on that POST endpoint (and might need to provide a package-info.java ). I'm testing locally...

**Comment by mliradelc** [comment]
Thanks for the commit, I'm trying right now :)

**Comment by mliradelc** [comment]
I'm having problems to build and try because an error from the Spring repository that doesn't allow to download some dependencies (Error 401) https://groups.google.com/a/opencast.org/g/dev/c/J7SU8zsM5SA I will answer again when I will have results :)

**Comment by gregorydlogan** [comment]
@mliradelc You're seeing this on develop only?  Or does this also happen in r/8.x?  Looking through the commits I don't see anything obvious in terms of what might have cause this that's not *also* in 8.x, which makes me wonder if this is also present there.  I have trouble believing that though, since adopters would be screaming - this isn't exactly an uncommon operation for a prod OC cluster!

I strongly suspect @karendolan's fix will work - this kind of wonkyness was common a long time ago (1.x era), but I haven't seen it in a long time so it didn't occur to me that this could be the cause.

**Comment by mliradelc** [comment]
> @mliradelc You're seeing this on develop only? Or does this also happen in r/8.x? 

Only in develop I'm seeing this, that's why I asked for confirmation.  8.x works solid as a rock.

**Comment by mliradelc** [comment]
@karendolan Unfortunately, does not work, I have the same problem using clusters. In allinone there is no problem with the publish-engage WOH. Now I made more tests and I found the same error when you try the search endpoint manually in the all in one version.

You can check here https://develop.opencast.org/docs.html?path=/search#add-1, if you use the default example and click submit it gives you error 500. but if you go to the actual release https://stable.opencast.org/docs.html?path=/search#add-1 it gives you error 419. 

I looked into the logs from the allinone when you submit manually in the /search/endpoint and I found the same problem that is in cluster. 

```xml
2020-09-29 11:41:05,854 | ERROR | (InjectionUtils:568) - Parameter Class org.opencastproject.mediapackage.MediaPackageImpl has no constructor with single String parameter, static valueOf(String) or fromString(String) methods
```


Normally with a test scheme it should at least show you error 400 (Bad request), in the case of 8.x is 419.

**Comment by mtneug** [comment]
> You can check here https://develop.opencast.org/docs.html?path=/search#add-1, if you use the default example and click submit it gives you error 500. but if you go to the actual release https://stable.opencast.org/docs.html?path=/search#add-1 it gives you error 419.

Is this still happening? I cannot replicate with the test instances.

**Comment by mliradelc** [comment]
> > You can check here https://develop.opencast.org/docs.html?path=/search#add-1, if you use the default example and click submit it gives you error 500. but if you go to the actual release https://stable.opencast.org/docs.html?path=/search#add-1 it gives you error 419.
> 
> Is this still happening? I cannot replicate with the test instances.

You have right!, I'm testing right now and I will let you know, both say now error 419 so should be fixed.

**Comment by mliradelc** [comment]
@mtneug Unfortunately is still Happenning the error in the presenter node.

Please, anyone! can anyone test opencast 9.x in node config, to confirm or discard this bug. We are less than a few weeks for the release of Opencast 9.x.
