### ISSUE TITLE
long comments in Admin-UI fail silently

### ISSUE THREAD

**Issue by ziegenberg** [opencast/opencast#1862]
**Describe the bug**
When I add a comment in the Admin-UI (/admin-ng/) with a length of more than 256 characters, the POST to /admin-ng/event/[UUID]/comment fails silently with a 500 Server Error. There is no error message shown to the user.

**To Reproduce**
1. Go to Admin-UI (/admin-ng/)
2. Click on the comment bubble for a ingested recording
3. Fill in a comment with more than 256 charachters
4. Select a reason
5. Click "submit"
4. See no error / no message / no warning

**Environment Information**
 - OS: Windows 20.04
 - Browser: tested with FF, Chrome
 - Opencast 8.5.0

**Comment by ziegenberg** [comment]
Not reproducible on https://stable.opencast.org/admin-ng 😒

**Comment by lkiesow** [comment]
Not being reproducible points to an internal problem. In any case, since it's not reproducible, we probably cannot do much about this. Especially without a stack trace. If you manage to reproduce it, feel free to re-open this issue and past the accompanying Java stack trace
