### ISSUE TITLE
Workflow condition parser does not handle floats

### ISSUE THREAD

**Issue by phoebem** [opencast/opencast#1870]
When a condition has a decimal value, eg: framerate returned by analyze-tracks, the parser treats it as a string

**To Reproduce**
Steps to reproduce the behavior, first write or update a workflow.
1. Add a workflow that uses <operation id = "analyze-tracks"> with
<configuration key="source-flavor">*/work</configuration>
2. follow with an operation, say 
<operation id="tag" if "${presenter_work_framerate} == 25)">
3. Run the workflow with a video with framerate=25
4. The tag operation will be skipped.

The problem is in workflow-condition-parser/.../WorkflowConditionInterpreter.java:93
It should be a Float.parseFloat instead of a Int.parseInt.

**Comment by lkiesow** [comment]
Fixed by #1871
