### ISSUE TITLE
Docs: Navigation Links still active when Sidebar is hidden

### ISSUE THREAD

**Issue by peculiarPrince** [opencast/opencast#1899]
When the navigation bar has been hidden using the 
![image](https://user-images.githubusercontent.com/38320410/94932647-a8b05c80-04c9-11eb-9c3b-72a9ea8dbd11.png) 
button top right, all links in the sidebar on the lefthand side of the page are still clickable and active, even though they are not shown.

**Comment by gregorydlogan** [comment]
Resolved with #1964
