### ISSUE TITLE
"Start Task" does not work

### ISSUE THREAD

**Issue by rrolf** [opencast/opencast#1907]
Within the admin UI: when you mark one or more events in the events table and then select "Start Task" from the "Actions" menu, within the first page of the assistant you cannot press "Next" anymore

**To Reproduce**

1. Go to 'the admin UI's event table and select an event'
2. Click on 'Actions -> Start Task'
3. Try to press "Next" in the new dialog
4. The Next-button is greyed out and you are not continuing to the next page in the dialog.

Reproducible on `develop` from 2020-10-04

**Comment by Rillke** [comment]
![grafik](https://user-images.githubusercontent.com/2311611/96354040-372ffb00-10d2-11eb-88b3-53770992233a.png)
