### ISSUE TITLE
Editor in AdminUI not available in spite of the cut (scissors) symbol

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#1975]
**Describe the bug**
No editor controls are available when opening an event for editing by clicking on the scissors in the AdminUI events table.

Additionally there is the following error logged to the JS console:
```
TypeError: can't assign to property "waitToPlay" on 4: not an object
    play playerAdapterFactoryDefault.js:161
    play playerDirective.js:181
    fn bower.c0eaa6c3.js line 1 > Function:4
    Angular 4
    jQuery 2
angular.js:15635:40
    Angular 4
    jQuery 2
```

**To Reproduce**
1. Go to https://develop.opencast.org/admin-ng/index.html#!/events/events
2. Click on <img width="27" alt="Screenshot 2020-10-18 at 01 05 02" src="https://user-images.githubusercontent.com/2311611/96355077-fb029780-10dd-11eb-91a6-49613948aace.png">
3. The editor opens but there are no editor controls:
<img width="1236" alt="Screenshot 2020-10-18 at 01 07 21" src="https://user-images.githubusercontent.com/2311611/96355099-4a48c800-10de-11eb-9ae5-d53c56200701.png">

**Environment Information**
 - Browser Firefox
 - Opencast version with minor release `Opencast 10.0.0.SNAPSHOT` (`develop`)

**Comment by gregorydlogan** [comment]
Does the same thing happen on stable.opencast.org?

**Comment by Rillke** [comment]
> Does the same thing happen on stable.opencast.org?

No, but stable says it's still `Opencast 8.0.0.SNAPSHOT - e39d54e`. There is a layout glitch with the end time broken into a new line and wrong translatio for `start time` but that's going into a new issue.

<img width="1203" alt="Screenshot 2020-10-18 at 08 34 21" src="https://user-images.githubusercontent.com/2311611/96360349-bcd89880-111c-11eb-8c78-2bc5bcce64da.png">

**Comment by lkiesow** [comment]
It's a 9.x issue
