### ISSUE TITLE
Admin UI events date filter converts timeZone date to "YYYY-MM-DD" back to UTC

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#1987]
**Describe the bug**

When I am in a timezone location to the West of UTC,  and I chose a start and end time period filter from the Admin UI events filter area, it always shows one day prior to the day I chose for start and end date.

The jQuery date Timepicker plugin  (jqueryui-timepicker-addon) retrieves my desired start and end date selection for my time zone. Then, the  jQuery date Timepicker plugin converts the timezoned Date objects into "YYYY-MM-DD" date strings.

Opencast's "tableFilterDirective"  then reconverts the "YYYY-MM-DD" into a Date object (defaults to UTC because the string has no zone context) and changes the UTC hour and minutes to near midnight in the morning and night.

Midnight UTC is the day before in half the worlds timezones. It is 8PM the day before in my time zone US EST.

``` 
               if (filter.period.to && filter.period.from) {
                    var from = new Date(new Date(filter.period.from).setHours(0, 0, 0, 0));
                    var to = new Date(new Date(filter.period.to).setHours(23, 59, 59, 999));
```

**To Reproduce**
1. Change your computers time zone to a zone west of UTC.
2. Go to https://develop.opencast.org or https://stable.opencast.org
3. Select a start date period filter from the events filter box.
4. See the day before the day you selected.
5. See the events filter selection is also off a day

**Comment by gregorydlogan** [comment]
Closed with #1988
