### ISSUE TITLE
Agent status not translated

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#20]
It seems a few source files refer "idle" as text for capture agents status, instead of enum or translatable keys.
Also, on recorder location view, it may show "capturing" instead of the localized string.
This strings should be parametrized/localized to allow agent status being translated into UI language.

**Comment by lkiesow** [comment]
The decision was made to not migrate to Github but stay with Bitbucket and Jira.
If this  issue still persists, can you please open a ticket at
https://opencast.jira.com
