### ISSUE TITLE
Emails sent by Opencast are missing the "Date" header

### ISSUE THREAD

**Issue by Snakel** [opencast/opencast#2010]
**Describe the bug**
When Opencast sends a mail as part of a workflow, e.g. https://docs.opencast.org/r/8.x/admin/#workflowoperationhandlers/send-email-woh/ , the email is missing the "Date" header. If the email gateway is not adding missing headers automatically, the email client may have problems correctly sorting/displaying the email.

**To Reproduce**
1. Create a workflow
2. Send a mail as part of the workflow
3. Outgoing mail does not have the "Date" header, but your mail gateway may add the header automatically. (E.g. Postfix before 2.6 added the headers automatically, Postfix 2.6 and later only adds the missing headers, if the "always_add_missing_headers" flag is "yes" and the sending client is matching in "local_header_rewrite_clients".)

**Environment Information**
 - OS: CentOS 7
 - Opencast version: 8.5

**Possible fix**
I think it should be enough to call `message.setSentDate(new Date())` in the `send` method in `modules/kernel/src/main/java/org/opencastproject/kernel/mail/BaseSmtpService.java`:

```java
  public void send(MimeMessage message) throws MessagingException {
    message.setSentDate(new Date());
    if (!productionMode) {
      logger.debug("Skipping sending of message {} due to test mode", message);
      return;
    }
    Transport t = getSession().getTransport(mailTransport);
    [...]
  }
```

See also https://javaee.github.io/javamail/docs/api/javax/mail/internet/MimeMessage.html#setSentDate-java.util.Date-

_EDIT(Lars): Fixed misspelled Opencast ;-)_

**Comment by lkiesow** [comment]
@Snakel, this looks about right. Can you create a pull request for that?
