### ISSUE TITLE
Studio Input breaks Video Editor

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2021]
Opening a recording from Studio in the editor does not work:

1. The editor UI is broken. The last segment is missing.
2. The end Time is set to NAN
3. Trying to process the event results in an error in the toolös endpoint since the frontend sends `Na:Na:Na:Na` as end time stamp

![Screenshot from 2020-10-22 17-16-34](https://user-images.githubusercontent.com/1008395/97738096-2e7df280-1ade-11eb-9078-f3aae14382fb.png)

##### To Reproduce
0. Configure `studio-upload` to push things to the editor
1. Go to studio and record something
2. Make sure to set cut marks in Studio
3. Once it's processed, go to the editor

This happens on `8.x` and newer.

##### Possible workflow fix:

This does not seem to happen when ´schedule-and-upload` is used. It would make the whole workflow a lot simpler if `studio-upload` would just do the preprocessing, and then call `schedule-and-upload`

##### Possible Editor fix

Allow the last segment to have no end which would just translate to whatever the length of the video is or in terms of showing it in the user interface to wherever the right edge is.

**Comment by marwyg** [comment]
After a recording in opencast studio, you can define a start and end point, where you want to trim your video. If you only choose a start point, the end point will be set to `Number.MAX_VALUE` (https://github.com/elan-ev/opencast-studio/blob/f00586f7fae0e178c606bf5c4242ded7054e4f36/src/opencast.js#L357). This leads to the described error. Maybe it should be changed there too.

**Comment by lkiesow** [comment]
Fixed by #2049
