### ISSUE TITLE
Upright/Portrait mode videos with parallel encoding using Studio default Workflows causing ffmpeg OOM

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#2024]
**Describe the bug**
When recording a Full-HD camera video with Opencast Studio using a recent smartphone in Portrait mode, processing fails at the encode step. Additionally, the ffmpeg error is not properly captured.

<img width="1234" alt="Screenshot 2020-11-01 at 12 34 09" src="https://user-images.githubusercontent.com/2311611/97801658-98151280-1c3e-11eb-99f9-4ebf18ae3ea5.png">

**To Reproduce**
1. Go to https://legacy.opencast.org with an Android smartphone
2. Log in
3. Open Opencast Studio (Camera symbol on the top)
4. Make to hold your smartphone in portrait mode and proceed
5. Select the back facing camera and at least FullHD quality

**Environment Information**
 - OS: Android 11 (latest stable) on Google Pixel 4a
 - Browser: Firefox
 - Opencast version with minor release 8.x

**Analysis**
The Studio workflows automatically select the number of qualities by video height.

This works fine for landscape videos. For high resolution portrait mode videos, it triggers parallel [encoding](https://github.com/opencast/opencast/blob/812f0d7da28ec870fb98fa4f89fc54853823467f/etc/encoding/adaptive-streaming-movies.properties#L100) of almost all qualities at once, resulting in an OOM.

Here are the ffmpeg logs:
```
INFO  | (EncoderEngine:461) - x264 [error]: malloc of size 135750144 failed
INFO  | (EncoderEngine:461) - Video encoding failed
INFO  | (EncoderEngine:461) - [aac @ 0x5a3ca40] Qavg: 9435.340
INFO  | (EncoderEngine:461) - [aac @ 0x5a3ca40] 2 frames left in the queue on closing
INFO  | (EncoderEngine:461) - [aac @ 0x5948300] Qavg: 2082.879
INFO  | (EncoderEngine:461) - [aac @ 0x5948300] 2 frames left in the queue on closing
INFO  | (EncoderEngine:461) - [aac @ 0x592e7c0] Qavg: 2082.879
INFO  | (EncoderEngine:461) - [aac @ 0x592e7c0] 2 frames left in the queue on closing
INFO  | (EncoderEngine:461) - [aac @ 0x59376c0] Qavg: 1185.690
INFO  | (EncoderEngine:461) - [aac @ 0x59376c0] 2 frames left in the queue on closing
INFO  | (EncoderEngine:461) - [aac @ 0x5911400] Qavg: 1099.754
INFO  | (EncoderEngine:461) - [aac @ 0x5911400] 2 frames left in the queue on closing
INFO  | (EncoderEngine:461) - Conversion failed!
WARN  | (EncoderEngine:233) - Error while encoding {video=/data/opencast/workspace/mediapackage/b935d30e-67ec-41be-b4ab-376238c9d661/573de4e1-0a9f-4a61-8f62-63956cc9548d/XXXX.mp4}  using profile 'studio.adaptive-parallel.http'
```

Encoding the lowest 3 qualities locally/manually allocates >4G in memory.

Interesting point here is that the [encoding profiles consider](https://github.com/opencast/opencast/blob/812f0d7da28ec870fb98fa4f89fc54853823467f/etc/encoding/adaptive-streaming-movies.properties#L121L122) the video's height and then produce a fixed width:

profile.studio.adaptive-parallel.http.ffmpeg.command.if-**height**-geq-**900** = \
-filter:v scale=**w=**1920:h=trunc(1920/dar/2)*2,setsar=1,fps=25 \

**Comment by Rillke** [comment]
This was discussed in the [Opencast Users](https://groups.google.com/a/opencast.org/g/users/c/eA9G1Wt7J1k/m/Yahyc4L0BwAJ) group.

**Comment by lkiesow** [comment]
If it checks the height, it should also set the height.

**Comment by JFD23** [comment]
I do also have issues with portrait/upright videos. 
on stable.opencast.org my two attempts with different WF (Studio Upload and Process upon upload and schedule) failed. On our installation, processing succeeded but created ridiculous resolutions like 6431p (which can not be replayed at all in recent firefox on windows or could be replayed on other plattforms and browsers but with poor performance)

[portrait error .pdf](https://github.com/opencast/opencast/files/6662441/portrait.error.pdf)

attached the error reports of my test on friday. 

this comment is based on OC 9.5

**Comment by lkiesow** [comment]
Should be fixed by #2573

**Comment by Rillke** [comment]
[workaround](https://github.com/opencast/community-workflows/blob/master/8.x/de.unihalle/workflows/studio-upload.xml#L262) for r/8.x

**Comment by wsmirnow** [comment]
May be fixed by https://github.com/opencast/opencast/pull/5548

**Comment by mtneug** [comment]
I would assume this is fixed now.
