### ISSUE TITLE
Edit Scheduled Events Modal does not allow specifying minutes (only hours)

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#2025]
**Describe the bug**
When I would like to change the start- or end time or the duration of a scheduled event in the Admin UI, I can only change the hour, not the minute.

<img width="1187" alt="Screenshot 2020-11-01 at 15 13 00" src="https://user-images.githubusercontent.com/2311611/97805216-12509180-1c55-11eb-8614-fbc48bc5bc2e.png">

**To Reproduce**
1. Go to https://stable.opencast.org/ and schedule an event for later today
2. Click on a <img width="29" alt="blue hamburger menu on event" src="https://user-images.githubusercontent.com/2311611/97805236-301df680-1c55-11eb-8de2-5cbc1e53b7b2.png"> belonging to a scheduled event
3. Switch to the "Scheduling" tab
4. See there is only a way for changing the hour but not the minute

**Environment Information**
 - OS: macOS Catalina 10.15.7
 - Browser Firefox 81.0.2
 - Opencast version with minor release `r/9.x` (Opencast 9.0.0.SNAPSHOT - 72347dc)

**Comment by mtneug** [comment]
Opencast 8 did not have that problem.
