### ISSUE TITLE
Matomo tracking plugin activation issue

### ISSUE THREAD

**Issue by kelvin-ling** [opencast/opencast#2070]
**Describe the bug**

Following the Matomo Tracking doc, I tried to activate the plugin with the following steps:
> nano /etc/opencast/org.opencastproject.organization-mh_default_org.cfg
```
prop.player.matomo.server=https://mydomain.matomo.cloud
prop.player.matomo.site_id=2
prop.player.matomo.heartbeat=30
prop.player.matomo.track_events=play
```

**To Reproduce**

1. Open Media Module
2. Login as user
3. Play video
4. Visit Matomo web dashboard
5. Matomo webpage shows "No data has been recorded yet"
6. Matomo webpage shows URL and site ID as installation guide, which are the same values as in the cfg file
7. No error displayed on Chrome console and Opencast log

> cat /var/log/opencast/opencast.log | grep matomo
```
2020-11-13T05:23:11,090 | INFO  | (BundleInfoLogger:110) - Bundle opencast-engage-theodul-plugin-custom-matomo, id 87, version 8.7.0, build number 75dc61f
```

**Environment Information**

 - OS: [Server: Ubuntu 20.04 using nginx as self-signed HTTPS proxy for Opencast]
 - Browser: [Chrome]
 - Opencast version with minor release [8.7]

**Documentation**

[https://docs.opencast.org/r/8.x/admin/#modules/player.matomo.tracking/](url)

**Comment by lkiesow** [comment]
That seems to be incorrect documentation. A while ago, the configuration for the Theodul player has been moved to
https://github.com/opencast/opencast/blob/7be29a23d0f5cbc1431324c1bba6c35f225074cf/etc/ui-config/mh_default_org/theodul/config.yml#L151-L181

Can you check if it works if you make the changes there?

**Comment by kelvin-ling** [comment]
Thanks @lkiesow. Glad to report it is working as intended by modifying the config.yml:

```
matomo:
  server: https://mydomain.matomo.cloud
  site_id: 2
  heartbeat: 10
  notification: true
  track_events: ["play", "pause", "seek", "ended"]
```

![image](https://user-images.githubusercontent.com/41847906/99108267-10f27200-2622-11eb-852d-f30ac0f61655.png)

**Comment by kelvin-ling** [comment]
Regarding the tracking plugin, is there a way to forward Opencast Media Module user login name to Matomo? From the (legacy) user statistics docs, looks like enabling the following can do the trick:

> nano org.opencastproject.usertracking.impl.UserTrackingServiceImpl.cfg

`org.opencastproject.usertracking.log.user=true`

[https://docs.opencast.org/r/8.x/admin/#configuration/user-statistics.and.privacy/#user-statistics-and-privacy](url)

I can see on Matomo dashboard it shows a visitor's IP address with a random visitor ID generated, but username was not forwarded:

![image](https://user-images.githubusercontent.com/41847906/99111667-83b21c00-2627-11eb-8c17-d588f154d869.png)
![image](https://user-images.githubusercontent.com/41847906/99111740-9e849080-2627-11eb-93f2-cb8b7156306f.png)

**Comment by lkiesow** [comment]
Great to hear that it worked.
Do you by any chance have time to update the docs?
They live in this GitHub repository at:
https://github.com/opencast/opencast/blob/develop/docs/guides/admin/docs/modules/player.matomo.tracking.md

Unfortunately, I don't know if submitting the username is possible (I've never actually used the Matomo plugin myself)
