### ISSUE TITLE
Movable and resizeable video overlay

### ISSUE THREAD

**Issue by xcelina** [opencast/opencast#2105]
Currently, when using separate presentation- and presenter-videos in overlay mode, the smaller videos is always shown in the bottom left corner at a fixed size. However, depending for example on the layout of the slides, it might be necessary to move the overlay to a different position, and/or to resize it.

**Comment by lkiesow** [comment]
This is not true for Opencast's default player in the latest stable:

![oc-player-layout](https://user-images.githubusercontent.com/1008395/100652179-cfaed180-3346-11eb-9455-ce1595a28db4.png)

Are you using another player?

**Comment by lkiesow** [comment]
Closing this for now due to lack of response. If this is still an issue, please feel free to re-open this.
