### ISSUE TITLE
Elasticsearch install missing from User (admin) docs

### ISSUE THREAD

**Issue by peculiarPrince** [opencast/opencast#2117]
As per the OC 9.x [Release Notes](https://docs.opencast.org/develop/admin/#releasenotes/#opencast-9-release-notes) `Opencast now requires an external Elasticsearch server to function`, but there is no mention of installing Elasticsearch in any doc of the Install documentation.
Current `elasticsearch` mentions in the user docs:
- The [Upgrade doc](https://docs.opencast.org/develop/admin/#upgrade/#install-and-configure-a-standalone-elasticsearch-node) says that it should be installed when upgrading from 8.x to 9.x, but only links to the [conf doc](https://docs.opencast.org/develop/admin/#modules/searchindex/elasticsearch/) describing how to configure it,
- The [Basic Configuration](https://docs.opencast.org/develop/admin/#configuration/basic/#step-5-elasticsearch-configuration) includes a link to the config in its steps, 
- And there is a short [config doc](https://docs.opencast.org/develop/admin/#modules/searchindex/elasticsearch/).

>Note: Since PR #1710, the [developer](https://docs.opencast.org/develop/developer/#installation/source-linux/#install-dependencies) docs includes Elasticsearch as one of OC's required services and describes how to [install it using Docker](https://docs.opencast.org/develop/developer/#installation/source-linux/#install-and-start-elasticsearch-and-activemq-with-docker)

**Comment by gregorydlogan** [comment]
I'll handle the deb docs since the repo is also being restructured. I'll let @lkiesow handle the rpms, or let him delegate to you :-) The question is who will handle the rest...

**Comment by gregorydlogan** [comment]
@mtneug Can you verify that the docker compose files for 9.x will have the appropriate bits to support ES?

**Comment by lkiesow** [comment]
I can:

https://github.com/opencast/opencast-docker/blob/0ef9bc1a77b1864902a603db5ed6b54833aaaf72/docker-compose/docker-compose.allinone.h2.yml#L34-L39

**Comment by mtneug** [comment]
@gregorydlogan sorry, I missed the ping :/
