### ISSUE TITLE
Videogrid Remote fails with BadMessageException

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast#2137]
**Describe the bug**
When trying to process a video conference recording with ~50 webcam videos, the video grid remote throws an exception, causing the videogrid WOH to fail:

```
2020-12-10T17:43:33,445 | WARN  | (HttpChannel:579) - /videogrid/videogrid org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
```
My suspicion is that the bug is caused by the way the Videogrid WOH sends ffmpeg commands to the Videogrid Service. Currently, the WOH generates all necessary commands and sends them as to the service as a single argument.

**To Reproduce**
1. Have an Opencast setup with at least two servers (e.g. admin-presentation and worker).
2. Ingest a new mediapackage. Use /ingest/addPartialTrack to add a ton of videos that all start at different times and whose duration overlaps.
3. Start a workflow on the mediapackage that runs the Videogrid WOH on the ingested videos.

**Environment Information**
 - OS: Fedora 31
 - Opencast 9.x

**Comment by gregorydlogan** [comment]
There's definitely a maximum character length for the arguments, not sure if that's configurable. There's probably a max number of arguments too, but I suspect you'll likely be under that for any reasonable number of streams.

**Comment by Arnei** [comment]
The PR that solves this issue is merged, closing.
