### ISSUE TITLE
Magnifying or minifying a video in Paella on Engange using 🔍 will also start/stop the video

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#2157]
**Describe the bug**
A clear and concise description of what you see:
*When opening a published video on https://stable.opencast.org and clicking the 🔍 with a + or -, the video is magnified or minified but the playback state is also toggled (i.e. a playing video stops and a stopped video starts playing)*

**To Reproduce**
1. Go to https://stable.opencast.org 
2. Click on a published dual-stream video (Published: Yes -> Engange) <img width="959" alt="Screenshot 2020-12-16 at 01 11 53" src="https://user-images.githubusercontent.com/2311611/102287909-b0fe2c80-3f3b-11eb-8663-29c74d86b736.png">
3. Start the video pressing the big play button ▶
4. Click the magnifying glass 🔍 on one video <img width="883" alt="Screenshot 2020-12-16 at 01 12 50" src="https://user-images.githubusercontent.com/2311611/102288024-e276f800-3f3b-11eb-8c6e-d4ad3cfb562d.png">
5. The video stops if it was playing, or starts if it was not playing

Expected: Maginifcation/ minification without playback toggle

**Environment Information**
 - Browser: Firefox 83.0 (64-Bit)
 - Opencast 9.0.0.SNAPSHOT - 547d9ef
 - Paella 6.4.3

**Comment by Rillke** [comment]
This issue is reproducable on https://paellaplayer.upv.es/demos/ and on r/8.x (paella 6.2.7), but on r/8.x the issue occurs only once (i.e. even if you press the magnification glass multiple times after loading the page, the playback state is only toggled once)

**Comment by Rillke** [comment]
A related issue: Pressing the magnifying glass twice may toggle the browser's full-screen state.

**Comment by Rillke** [comment]
Upstream report: https://github.com/polimediaupv/paella/issues/649

**Comment by lkiesow** [comment]
Has been fixed in https://github.com/polimediaupv/paella/commit/5d80f3d1fccd94e259f15622da81f69d5ed97d0b (probably Paella 6.4.6)

**Comment by mliradelc** [comment]
This seems to be fixed, please reopen if you think that is needed
