### ISSUE TITLE
Remove Elasticsearch from basic cofiguration docs

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2205]
New adopters installing Opencast should usually follow the steps:

- Select an installation type
- Follow the installation guide (e.g. Install via CentOS 8 Packages)
- Go through basic configuration (since all install guides link to it)

So, you have a reading flow like this:

```

                                    +--> RPM Installation -----+
                                    |                          |
New User on docs --> Installation --+--> Debian Installation --+--> Basic Configuration --> ...
                                    |                          |
                                    +--> Install from Source --+
```

The basic documentation are not very useful for old installations, upgrades, advanced users, … and will likely be used only in this context. In addition to that, users will _always_ have installed Opencast before going through the basic configuration guide.

That is why I think [Step 5: Setting up Elasticsearch](https://docs.opencast.org/r/9.x/admin/#configuration/basic/#step-5-setting-up-elasticsearch) doesn't make any sense in there. There is no configuration to do and the installation should be done. Linking back to where the user likely just came from is not helpful and will probably just confuse users: Do I need anything more? No. Why should I go back? No real reason.

@gregorydlogan, @peculiarPrince: Any thoughts on why we would want to keep this?

This is related to #2134

**Comment by gregorydlogan** [comment]
It was mainly added as a second check to make sure that users have definitely installed Elasticsearch - the Debian packages don't explicitly depend on the package being installed for example.

I suspect longer term we might want more config (auth), but for now there really isn't a ton of point in that piece of documentation.  Doubly so because it's a circular reference: The basic config references the install docs, which reference the basic config.  If you want to remove it I won't fight it.

**Comment by mliradelc** [comment]
I understand what you mean Lars, but the if we delete that step we need to add to the dependencies list 

I checked and each guide for RPM/Debian/Source, have different dependencies, we should add each guide the command for Elastic search to install it. 😃

**Comment by gregorydlogan** [comment]
Oh, what I would give for a good technical writer... :)
