### ISSUE TITLE
Edit button doesn't work in LTI tool

### ISSUE THREAD

**Issue by Gao-Jun** [opencast/opencast#2207]
**Describe the bug**
The edit button in LTI tool doesn't work. 
If an user want to change the tilte of an episode, an error message shows up.
After digging the source code, I found the LTI tool trys to start a `republish-metadata` workflow.
Yet, this workflow seems only apply to an event in `working` state according to IndexServiceImpl.java#updateWorkflowInstance
So, technically, this edit button won't finish the function.

I'm curious that why Opencast will forbid user to edit metadata of a successed event? And is there any way to change this behavior?

Or, if only working event is allowed to change its metadata, the edit button should be removed from the LTI tool.

**To Reproduce**
1. Create a new event with LTI upload tool. LTI show tool is config with `edit=true`
2. Wait for process
3. Goto the show view of LTI tool, an edit button is shown next to the episode, click the edit button
4. Change the title of the episode and save
5. Fail warning shows up

**Environment Information**
 - OS: [Debian 10]
 - Browser [Chrome]
 - Opencast version with minor release [9.x]

**Comment by kristofkeppens** [comment]
@Gao-Jun I can confirm that there is something wrong with the edit functionality in the LTI module ( for opencast  9.x ). I'm even unable to get to the edit form, as soon as I select the edit button I get an error on the /lti-service-gui/*****/metadata endpoint being unavailable. We'll have a look at what's going on.

**Comment by Gao-Jun** [comment]
Fixed in `r/10.x` branch
