### ISSUE TITLE
NullPointerException when accessing series details

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2218]
When accessing the series details in the admin interface with the default configuration, a `NullPointerException` is being logged:

```
2021-01-17 14:33:05,938 | ERROR | (FeedEndpoint:74) - Could not get /feeds request in FeedEndpoint. java.lang.NullPointerException
```

Happens on `r/9.x`

**Comment by gregorydlogan** [comment]
Resolved with https://github.com/opencast/opencast/commit/f9a1090a2ab4764a9e090be423491b168d4c1a15
