### ISSUE TITLE
Series Modal does not display feeds

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#2254]
**Describe the bug**
Follow up for #2218, the series modal does not display any feed data.  The backend request succeeds, but the modal shrinks down to the tab bar and does not display any feed data.  This behaviour is present in `r/9.x` but not `r/8.x`.

**To Reproduce**
1. Go to stable.opencast.org
2. Click into a series metadata pane
3. Click on feeds

**Environment Information**
Present on stable.opencast.org but not on legacy.opencast.org.  Tested in Chrome.

**Comment by lkiesow** [comment]
The issue is not limited to feeds. You see the same in the theme and statistics tabs. Likely the same issue we have seen in the video editor when we upgraded angular and it reacted less nice to (already) broken HTML. I will take a look.
