### ISSUE TITLE
Admin UI has a maximum of 10000 entries per table

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#2280]
We just upgraded to opencast 9.1 and notice that the Admin UI is limited to 10000 entries per table. For instance the series tab show 10000 rows, while we have a lot more series. Same for the events where each table is limited to the same 10000 entries.

**Comment by gregorydlogan** [comment]
... What was the previous behaviour? A 10k limit doesn't sound surprising to me, which makes me think you're seeing the result of a fix for something.

**Comment by lkiesow** [comment]
Can you provide a few more details?

- Are the total numbers in the admin interface correct?
- What do you mean by _in one table_? You probably do not have a single page with 10000 entices. Does the pagination end at 100 pages with 100 entries each?
- Did the problem appeared with 9.1? Or did you only just notice?

**Comment by kristofkeppens** [comment]
* Total numbers or not correct, having a limit at 10000 would be fine if at least the totals would be correct. 
* It looks like that there is a limit to 10000 for each query to the elasticsearch database. So for instance our Finished items in the Admin UI are now exactly 10000 ( which is not correct ) . Same for the series. Total number of rows is reported as 10000 as well, but there are a lot more ( you can retrieve all via the series endpoint, or looking at the elasticsearch index directly ).
* We are coming from the latest 8.x release and this behaviour was not present then.  Maybe a result of the elasticsearch version upgrade ?

**Comment by lkiesow** [comment]
@flyapen, can you test if  #2299 fixes the issue?
