### ISSUE TITLE
Standard workflow fails when resizing ultra-wide input video because resolution is not divisible by 2

### ISSUE THREAD

**Issue by LukasKalbertodt** [opencast/opencast#2297]
**Describe the bug**
Uploading an ultra wide (roughly 2.4:1), high resolution (2048x858) video results in a workflow processing error. The workflow runs this ffmpeg command:

```
ffmpeg -nostdin -nostats -i Spring.webm -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart -filter:v scale=1280:-2:force_original_aspect_ratio=decrease,fps=25 -c:a aac -b:a 64k -ac 1 -f mp4 out.mp4
```

In particular, see `scale=1280:-2:force_original_aspect_ratio=decrease`. The `scale=1280:-2` means: width of 1280 pixels, height such that the aspect ratio stays and make sure it is divisible by 2. So in this case: 2048/1280 = 1.6; 858/1.6 = 536.25, which would be rounded to 536. That would be a good output resolution, BUT the `force_original_aspect_ratio=decrease` now leads to the width being decreased to 1279 because 1279/536 is closer to the original aspect ration than 1280/536 is. But now the width is not divisible by 2 which means the codec will throw an error. 

From my understanding, the `force_original_aspect_ratio` does not make sense here because in this setup, if it gets active, it would most of the time lead to a odd width or height. That's because if it gets active, it would usually decrease the width by only 1. @lkiesow made me aware of [the `force_divisible_by` parameter](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20190708154340.26514-1-lkiesow@uos.de/). Which would make sense here I guess?

**To Reproduce**
1. Download this awesome Blender movie: https://upload.wikimedia.org/wikipedia/commons/a/a5/Spring_-_Blender_Open_Movie.webm
2. Go to stable.opencast.org
3. Upload video with "Process upon upload and schedule" workflow and with output 720p resolution
4. Notice how the WF fails

**Environment Information**
 - Opencast version: 9.1

**Comment by lkiesow** [comment]
I agree. This makes no sense and defeats the purpose of the `-2`.

- Either just use `scale=1280:-2`
- Or use `scale=1280:1280:force_original_aspect_ratio=decrease:force_divisible_by=2`

While the former is simpler, the latter gracefully handles portrait mode video which could otherwise have the side-effect of being blown up. For example, a 720p portrait mode video would end up being 1280x2276 since only the horizontal size is taken into account.

Hence, my suggestion for the command is:

```
ffmpeg
  -nostdin -nostats
  -i Spring.webm
  -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p
  -x264opts keyint=25:min-keyint=25:no-scenecut
  -movflags +faststart
  -filter:v scale=1280:1280:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25
  -c:a aac -b:a 64k -ac 1
  -f mp4 out.mp4
```

Documentation can be found at http://ffmpeg.org/ffmpeg-all.html#Options-85

**Comment by LukasKalbertodt** [comment]
That second option sounds good to me. Though that would be technically incorrect when we still label the video as "720p". For reference, I just picked [a random potrait YouTube video](https://www.youtube.com/watch?v=FoMlSB6ftQg) and checked what resolutions their labels result in:

2160p -> 2160x4096
1080p -> 1140x2160
720p -> 760x1440
480p -> 570x1080

While this is strange on its own, they have higher resolutions than what your suggestion would result in that more closely fits the "<number-of-lines>p" description. Just something to keep in mind. 
But I would probably say that your command has the more useful behavior. Like, if I have a phone that I know has a FullHD screen, I would click on the 1080p video option for a portait video, expecting a 1080*1920 video. \</rambling>

**Comment by lkiesow** [comment]
> Though that would be technically incorrect when we still label the video as "720p".

I think that the label is technically incorrect as soon as you are not using a 16:9 aspect ratio.
But given that it was coined for specifying a maximum resolution I find it more unexpected to exceed that resolution.

Also, users are probably confused if you label it as “decrease to 720x720 pixels bounding box”.

Will you create a pull request?

**Comment by LukasKalbertodt** [comment]
I have a patch ready, but it fails for me locally because my ffmpeg does not know the `force_divisible_by=2` option yet. What is Opencast's policy on ffmpeg versions? What versions are supported? Is there usually an ffmpeg bundled with Opencast?
