### ISSUE TITLE
episode search endpoint fails for sname values containing lots of uppercase characters.

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#2308]
**Describe the bug**
Solr search fails for specific serie titles. For instance when you have a series with as title a name that contains a lot of uppercase letters ( TestSeriesWithUpperCaseLetters ) and you use the /search/episode.json with this title as series name you get 0 results back. Looking at the query in SOLR I noticed that this gets cast to lowercase when doing the search. In most cases this works fine, but when there are a lot of uppercase characters SOLR seems to think that this is too much for a match. 

Is there a reason why everything gets cast to lowercase before doing the search? I removed this for the title field and this seems to work fine for us, but it might have unforeseen consequences. 

This is using opencast  9.1.

**Comment by lkiesow** [comment]
I don't remember a reason, @gregorydlogan, @rrolf, do you?

**Comment by gregorydlogan** [comment]
Not a clue. Perhaps at some point the indexing was done on all lower case, and that has since been lost? Regardless, it sounds like a bug to me now.

**Comment by lkiesow** [comment]
@flyapen, if you have code, will you create a pull request?

**Comment by kristofkeppens** [comment]
Yes sure, at the moment I've only changed the title field, should all fields preserve the case sensitivity ?

**Comment by Gao-Jun** [comment]
According to the doc, Solr will be replaced in the future.
Currently, Solr is still remain at an outdated version. It's not a good solution to keep some data in Solr and some data in ElasticSearch.
Are there any plan to migrate Solr functions?

**Comment by gregorydlogan** [comment]
Long term yes, since the current Solr version has some fairly major deficiencies. Short term it's unclear.

All of us would love to have Solr removed in favour of Elasticsearch, but no institutions have come forward with the work, or the financing to hire someone to do the work. If this is something your institution wants to take on please let us know - it's a fairly major piece of work, so it makes sense to coordinate efforts to avoid duplicate work.

Edit: tagging @Gao-Jun so he definitely see this :)

**Comment by Gao-Jun** [comment]
@gregorydlogan Thank you for your reply.
Recently, I meet some problems of Opencast. After some debug work, I think functions depend on Solr cause these problems.
Maybe my institution would do something to get rid of Solr in the future. If that happens, I will let you know.
