### ISSUE TITLE
Check for presence of maven dependency plugin 

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2334]
Git commit a444adcde4fd45a9b3d35707bcdfc3c32a754863 removed the check for the presence of the maven dependency plugin in all modules with a few exceptions. I'm not sure why. I think it would still make a lot of sense to check if new modules include the plugin and wouldn't have removed it.

**Comment by gregorydlogan** [comment]
IIRC it was causing errors when I removed it, but reverting that commit doesn't seem to break anything.  I'll give it a push in a bit.

**Comment by gregorydlogan** [comment]
Better fix with 6a1c87ae2d.
