### ISSUE TITLE
Worklow CleanupScanner won't delete all Jobs

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#2357]
**Describe the bug**
The workflow cleanup scanner does not delete all the Jobs that meet the criteria, when in an Event is manually deleted a workflow using (DELETE /workflow/{id})

If you execute the WorkflowCleanupScanner after your event was ingested, all the Jobs are deleted correctly.

**To Reproduce**
1. Ingest a new event and publish
2. Go to the Database and in the OC_JOBS table take a note about the jobs made.
3. Delete the finished workflows with (DELETE /workflow/{id}).
4. Look again the DB in the OC_JOBS table and take note what Jobs were left. Normally are only the "Track" Jobs from the event (The ones that were use for to ingest are left).
5. Enable the workflow cleanup scanner `org.opencastproject.workflow.impl.WorkflowCleanupScanner.cfg` and set the criteria for testing.
6. After it is executed go again to the DB and you will find that still those jobs are still there.

**To make the test easier**
Use this configuration in  `org.opencastproject.workflow.impl.WorkflowCleanupScanner.cfg`, this configuration will make the Cleaner work every time.

```bash
# Enable or disable the workflow cleanup scheduler
# default = false
enabled = true
# Set a cron expression which will be used to schedule the workflow cleanup job
#
# See http://www.quartz-scheduler.org/api/1.8.5/org/quartz/CronExpression.html
# for more information about cron expressions
cron-expression =  * * * * * ?

# Set the buffer to give succeeded jobs (in days) before removing them
buffer.succeeded = 1

# Set the buffer to give failed jobs (in days) before removing them
buffer.failed = 1

# Set the buffer of stopped jobs (in days) before removing them
buffer.stopped = 1

# Set the buffer of parentless jobs (in days) before removing them
buffer.parentless = 1

```
**WARNING** This will delete any workflow that meet the criteria

The only problem is because the way the methods are made, the minimum wait time is one day, so to try this you do the steps 1 to 4 **the day before** for the testing.

**Environment Information**
 - OS: ANY
 - Opencast version: 8.x, 9.x

**Comment by lkiesow** [comment]
Do you really see this as a bug? I would not. The __workflow__ cleanup scanner is supposed to clean up workflows, is it not? You actually _deleted__ that workflow. So, how is the scanner supposed to pick up the sub jobs? They do not belong to any workflow any longer after all.

**Comment by lkiesow** [comment]
Closing this for now due to lack of response. For a reason why I do not see this as a bug, see the post above. Feel free to re-open this if you disagree.
