### ISSUE TITLE
OC 9.2 Ubuntu 18.04 - Admin site angular.js exceptions

### ISSUE THREAD

**Issue by relecand** [opencast/opencast#2358]
**Describe the bug**

- I installed OC 9.2 (c0594fa) with this guide: https://docs.opencast.org/r/9.x/admin/#installation/debs/ 
- allinone
- mariadb 
- nginx as proxy

When I log in with the admin account I get angular.js exceptions.

**To Reproduce**
1. Log in as admin
2. Open console
3. See error

![grafik](https://user-images.githubusercontent.com/5286499/108992405-8f3ac780-7699-11eb-8c8a-feaca2c3b497.png)

Logs
```
2021-02-24T11:50:49,963 | ERROR | (R6LogServiceLogger:50) - bundle opencast-distribution-service-download:9.2.0 (87)[org.opencastproject.distribution.download.DownloadDistributionServiceImpl(183)] : The activate method has thrown an exception
2021-02-24T11:50:49,965 | ERROR | (EventDispatcher:881) - FrameworkEvent ERROR
2021-02-24T11:50:49,968 | ERROR | (EventDispatcher:881) - FrameworkEvent ERROR
```

**Environment Information**
 - Ubuntu 18.04
 - Browser: FF 85.0.2, Chrome 88.0.4324.182 
 - Opencast 9.2 c0594fa

All the best,

Christian

**Comment by relecand** [comment]
More detailed logs

[opencast.log](https://github.com/opencast/opencast/files/6037348/opencast.log)

**Comment by lkiesow** [comment]
```
2021-02-24T16:57:44,632 | INFO  | (ServiceRegistryJpaImpl:1221) - Host https://opencast.example.com unregistered
```

Did you actually use opencast.example.com as your hostname in your configuration or did you replace all the occurrences in the logs?

**Comment by relecand** [comment]
Hi Lars,

thank you for your response. I replaced the hostname in the logs.

**Comment by relecand** [comment]
Also CentOS 7 and Opencast 9.2 do not work. The same issues.

**Comment by jojoob** [comment]
Hey, I'm working with @relecand on the same problem.

Tried with openJDK 8 and 11, same problems with both. Opencast 8 works

**Comment by jojoob** [comment]
The problem was caused by Elasticsearch not running. Didn't saw the Elasticsearch error messages in the great amount of other java errors. Still a lot of error messages in the [opencast.log](https://github.com/opencast/opencast/files/6042659/opencast.log). But the basic functions I tested seem now to work.

**Comment by jojoob** [comment]
After we had overcome a few more obstacles we have Opencast now running on Ubuntu 18.04.

Some behavior was unexpected and the flood of error messages not clear. Lessons learnt:

* Elasticsearch from Opencast repo is not enabled by default (`systemctl enable elasticsearch; systemctl start elasticsearch`)
* server.url setting is used for internal communication of the all-in-one installation -> valid certificate or adjusting java truststore required when using https. But seems also to work with the default value (http://localhost:8080) even when accessing opencast via https per NGINX reverse proxy.
* minimum memory for an all-in-one test installation ~8GB (had OOM exceptions with 4GB while processing a 5 second video)

It would be helpful if these things were mentioned by the documentation.

**Comment by gregorydlogan** [comment]
The Debian packaging is mine, and behaves slightly differently than the RPMs in regard to starting services by default.  I'll get to this eventually, in the meantime if you want to file PRs to fix some of this feel free.

**Comment by lkiesow** [comment]
RPMs are expected to not start a service, so you can configure it properly. While that's generally the case, it's also documented in the RPM install guide which explains how to install, start and enable Elasticsearch.

If that is also the case for Debian packages, and it is currently missing from the docs, it would be great if you could create a pull request to suggest an addition to the docs. You can find the docs at: https://github.com/opencast/opencast/blob/r/9.x/docs/guides/admin/docs/installation/debs.md

**Comment by gregorydlogan** [comment]
So the only major issue I see here is ES not starting itself, which I've filed a PR to fix.  The rest is addressed elsewhere, or was been addressed since this was filed.
