### ISSUE TITLE
Documentation Graphs broken in r/8.x

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2386]
Commit 84e009588faafd227456208ffc750d5b5617cb61 breaks the documentation builds and Graphviz graphs are not rendered any longer. The commit caused merge conflicts and thus I dropped it in the 9.x merge. Still, 8.x remains broken.

- broken
    - https://docs.opencast.org/r/8.x/developer/#development-process/#git-repository-branching-model
- okay
    - https://docs.opencast.org/r/9.x/developer/#development-process/#git-repository-branching-model

**Comment by gregorydlogan** [comment]
I'm.... very confused here.  There's a bug in that `graphviz` isn't installed in `r/8.x`, but even once it's installed it's generating incorrect inline pngs.  For example:

```
<p><img alt="branching-simple.png" src="data:image/png;base64,b" title="iVBORw0KGgoAAAANSUhEUgAAApkAA...
```

rather than

```
<img alt="branching-simple.png" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAABrCAYAAA...
```

Even better, looking at the raw documentation I see *no* reason why 8.x would be incorrectly adding a title tag.

**Comment by gregorydlogan** [comment]
Even betterer, I can't reproduce this on Debian 10, but I can on Ubuntu 20.04 and 18.04...

**Comment by lkiesow** [comment]
If I use `pip` to install the dependencies one after another, it works. I left it at that and ignored it. That's why I never committed a `requirements.txt` for the documentation stuff.

**Comment by lkiesow** [comment]
Seems like I was correct after all in #2415 and the pull request  #2409 did vreak this again.
Will fix this.
