### ISSUE TITLE
Series with identical names not distinguishable when scheduling in UI

### ISSUE THREAD

**Issue by AndreasUrra** [opencast/opencast#2393]
**Describe the bug**
When scheduling events in the Opencast UI it is not possible to
distinguish between identically named series. The dropdown list "Series" in
the scheduling dialogue will only show a single entry for all series that
are named identically.

**To Reproduce**
1. Make sure you have two series in Opencast with identical names
2. Click on 'Add Event'
3. Try to select the series
4. See error: only one entry for both series

**Environment Information**
 - OS: CentOS 7
 - Browser Chrome
 - Opencast version 8.3.0 and 8.10.0

Discussion: Even if there were two entries, they probably woul be indistinguishable in the list. There should be a way, e.g. adding the 'organizer' field in the list (ILIAS Course) to further describe them for the user.

**Comment by lkiesow** [comment]
This is still broken in `develop`.
The problem is that names are used as keys and the ids as value.
https://develop.opencast.org/admin-ng/event/new/metadata

```json
  …
  {
    "translatable": false,
    "readOnly": false,
    "id": "isPartOf",
    "label": "EVENTS.EVENTS.DETAILS.METADATA.SERIES",
    "collection": {
      "Wiki Commons Content": "ID-wiki-commons",
      "Blender Foundation Productions": "ID-blender-foundation",
      "AV-Portal Content": "ID-av-portal",
      "Asterisk": "4fee16ab-adb4-4a79-a984-d50b10bc73b9"
    },
    "type": "text",
    "value": "",
    "required": false
  },
  …
```

(Two series with name `Asterisk` exist)
