### ISSUE TITLE
The lti-service-remote bundle is missing its endpoint definitions

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#2442]
**Describe the bug**
As reported by a user on Matrix: 
`Hey, does anybody know a reason why deleting an event from the LTI series view on the presentation node redirects to /login as if the user is not authenticated, which then returns a '405 not allowed', while doing exactly the same from an admin node works perfectly?`

In investigating why the 405 was being returned, I noticed that *[the entire endpoint class is missing the endpoint annotations](https://github.com/opencast/opencast/blob/develop/modules/lti-service-remote/src/main/java/org/opencastproject/lti/endpoint/LtiServiceRemoteImpl.java#L166)*, hence the 405 since the endpoint doesn't exist without them.  Looks like they were never present, and this was missed during code review.

**Comment by lkiesow** [comment]
This might be related to #2180
