### ISSUE TITLE
Stand-alone editor is stuck in animation "Generating Waveform" for videos without audio track

### ISSUE THREAD

**Issue by geichelberger** [opencast/opencast#2491]
Uploading a video without an audio track causes an exception in the stand-alone editor ui which leads to the "Generating Waveform" animation not being stopped.

Browser-Console Error: 
`DOMException: The buffer passed to decodeAudioData contains an unknown content type.  waveform.js:46:26`

1. Upload video without audio track.
2. Open the stand-alone editor
3. "Generating Waveform" animation never stops

**Environment Information**
 - OS: Fedora 33
 - Browser Firefox,Chrome
 - Opencast 10-SNAPSHOT

**Comment by lkiesow** [comment]
This seems like a duplicate of https://github.com/elan-ev/opencast-editor/issues/254 and this might already be fixed with https://github.com/elan-ev/opencast-editor/pull/236

**Comment by lkiesow** [comment]
Fixed in https://github.com/elan-ev/opencast-editor/pull/236
Will be resolved with the next editor update
