### ISSUE TITLE
GitGuardian alerts

### ISSUE THREAD

**Issue by LinqLover** [opencast/opencast#2545]
Since I have forked opencast a few months ago for a small [PR](https://github.com/opencast/opencast/issues?q=LinqLover), GitGuardian is now spamming me with token alerts. Most likely you already checked these out, but I wanted to be sure that you are not leaking any critical secrets 😅

- https://github.com/opencast/opencast/commit/47eb508ee80f2cc8f5d92a5acfa60d2b4f77bfe6#diff-808409c53a4ab0124f2c0d3ed8dbeca4cdcce1f2443dc2f0dc733b07e00d515fR6
- https://github.com/LinqLover/opencast/commit/daa44ba8dfb7983b11f8efca5067d69193c8fae8#diff-8ca03ec3b775e5d185e031f01794655e8ef9ee38d0fc329428efcb876619f722L27
- https://github.com/LinqLover/opencast/commit/7c952410bd7c7697df918a581898c6641e884018#diff-796635b80dcbf415ee5a79b9437d675241257f3cf8a648ff9833fcb3cf994ed8R26
- https://github.com/opencast/opencast/commit/8b117672fd03cd234376e28aa258f246c499b343#diff-655338038a1bd0cfe96b37053c7fd8290eb1590ff361a5c1a6dc5dd7314c7073L4

Note that I only posted one link per commit, there were also a few other incidents. If required, you can scan your repositories yourself using GitGuardian.

**Comment by lkiesow** [comment]
Quickly went through them. The first three are clearly marked as dummy keys. The last one was an actual past incident which was quickly resolved back then.
