### ISSUE TITLE
Paella play button may hide content

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2570]
The paella player has a massive play button as overlay in the center of the player. This helps to identify this as a video player but may hide important content when pausing the video. While administrators can completely deactivate the button:

https://github.com/opencast/opencast/blob/7fa03bcd717fea74e0f42eae1532e63abc01fe73/etc/ui-config/mh_default_org/paella/config.json#L226-L228

…it would be nice to have it _only_ when the player has not been started yet.

**Comment by miesgre** [comment]
I haven't tried it, but I think you can add the `showOnPause` property to the config

https://github.com/polimediaupv/paella/commit/cd941b335ed0e3bbcc0ba8c0942c76d8e917da47
