### ISSUE TITLE
Ingest Service should only trigger a series metadata update when the metadata has actually changed

### ISSUE THREAD

**Issue by sinhote** [opencast/opencast#26]
#### Steps to reproduce:
1. Make sure the property `org.opencastproject.series.overwrite` in the file `org.opencastproject.ingest.impl.IngestServiceImpl.cfg` is set to `true`
2. Ingest a certain number of mediapackages belonging to the same series and containing a series metadata catalog containing the exact same metadata. Make sure the workflow run after the ingestion archives the mediapackage. 
 
#### Actual Results:
 Each time a new mediapackage is ingested, each archived mediapackage belonging to the same series is archived again to, in theory, store the updated series metadata --even though the series metadata is actually exactly the same and does not require to be updated at all.
 
#### Expected Results:
 Before triggering a potentially expensive update (series may have a large number of mediapackages which are all re-archived), the system should make sure that the ingested series metadata catalog *does* modify the current series metadata.
 
#### Workaround (if any):
 Either remove the series metadata catalog from the mediapackage or set the `org.opencastproject.series.overwrite` property to `false`.

**Comment by karendolan** [comment]
I can't recall if this is merged, but if you want to ensure that an ingested series (versus series updated via the series update REST endpoint, which is a totally different approach ) updates series metadata be careful to compare for when values are removed from a catalog versus just when they are added to a catalog.

**Comment by sinhote** [comment]
@karendolan The thing is, looking at the code (that is, connecting a debugger and adding a breakpoint in the "addInternal" method of the archive service, then looking at the stack to see exactly where the call was originated), the update is triggered after a certain type of message is sent through the ActiveMQ, and the handler does not bother at all to check whether or not the metadata is changed. It just checks the property `org.opencastproject.series.overwrite` and triggers the bulk archival without further ado.

But of course, what you mention is absolutely correct. Update is not only a change in a existing metadata value or the addition of a new parameter, but also the removal of one (or several!)

**Comment by lkiesow** [comment]
The decision was made to not migrate to Github but stay with Bitbucket and Jira.
If this  issue still persists, can you please open a ticket at
https://opencast.jira.com
