### ISSUE TITLE
[Feature Request] User-configurable Picture-in-Picture, Side-by-Side and No-Floating-Head ?

### ISSUE THREAD

**Issue by zenny** [opencast/opencast#2613]
Hi,

I am curious to know whether OpenCast Studio captures the video streams separately and renders in the default video player separately so that the user can select either Picture-in-Picture (PiP), Side-by-Side (SbS) or No-Floating-Head (NFH) with resizable options?

I just noticed the above video player features reportedly been implemented in Kaltura in this presentation (https://www.youtube.com/watch?v=PjoxQmNkGBI&t=9m15s). I have no idea if there would be any lags due to latency?!

Cheers, and stay safe,
/z

**Comment by zenny** [comment]
> Hi,
> 
> I am curious to know whether OpenCast Studio captures the video streams separately and renders in the default video player separately so that the user can select either Picture-in-Picture (PiP), Side-by-Side (SbS) or No-Floating-Head (NFH) with resizable options?
> 
> I just noticed the above video player features reportedly been implemented in Kaltura in this presentation (https://www.youtube.com/watch?v=PjoxQmNkGBI&t=9m15s). I have no idea if there would be any lags due to latency?!
> 
> Cheers, and stay safe,
> /z

Just came across fine prints of the Kaltura Player at https://corp.kaltura.com/video-content-management-system/player-studio/
github repo in https://github.com/kaltura/kaltura-player-js, fyi. The repo appears to be something desirable to be forked to fit in with OpenCast. Just a wishful thinking. ;-)

**Comment by lkiesow** [comment]
Hi @zenny,
Studio already captures the streams separately, and you can use them in the player however you like. Both Opencast players also allow users to place the video streams. Here is a dual-stream example recorded with Studio:

- Paella player: https://develop.opencast.org/paella/ui/watch.html?id=ID-dual-stream-demo
- Theodul player: https://develop.opencast.org/engage/theodul/ui/core.html?id=ID-dual-stream-demo

What they don't currently support is to freely move one stream around. That's a good idea for the new version of Paella. Since you already created an issue for that in the Paella repository, I'm going to close this one. Tracking this at two places will just lead to miscommunication.

**Comment by zenny** [comment]
> Hi @zenny,
> Studio already captures the streams separately, and you can use them in the player however you like. Both Opencast players also allow users to place the video streams. Here is a dual-stream example recorded with Studio:
> 
>     * Paella player: https://develop.opencast.org/paella/ui/watch.html?id=ID-dual-stream-demo
> 
>     * Theodul player: https://develop.opencast.org/engage/theodul/ui/core.html?id=ID-dual-stream-demo
> 
> 
> What they don't currently support is to freely move one stream around. That's a good idea for the new version of Paella. Since you already created an issue for that in the Paella repository, I'm going to close this one. Tracking this at two places will just lead to miscommunication.

@lkiesow Impressed by demos! Wonderful! The PiP in the demos overlapped like in Kaltura. In addition, I did see the Paella player has an option to choose a display mode with the presentation only without floating head which should be in the engage player, too.

However both of the demo first loaded the presentation (not floating head) first, but went blackscreen I chose PiP. See screenshots below (could be a bug)

![pic-selected-210518-1313-14](https://user-images.githubusercontent.com/1653166/118642725-f7520300-b7db-11eb-95cb-68504eec1044.png)


![pic-selected-210518-1313-24](https://user-images.githubusercontent.com/1653166/118642838-1c467600-b7dc-11eb-97ed-6ecb6434b1d9.png)

Cheers,
/z

**Comment by lkiesow** [comment]
Interesting. It works fine if you use the players PIP mode but it seems that at least Firefox has its own PIP mode which pops one video out of Firefox and leaves the black frame where the video was. With the players PIP mode, it looks like this:

![Screenshot from 2021-05-19 00-14-22](https://user-images.githubusercontent.com/1008395/118730213-8809fc80-b837-11eb-99e8-449bd90aebe7.png)
