### ISSUE TITLE
Inspect WOH fails if mediapackage contains HLS manifests

### ISSUE THREAD

**Issue by mtneug** [opencast/opencast#2618]
**Describe the bug**

Running the `inspect` WOH will fail for a mediapackage containing HLS manifests. This is because the references to the segments / variant manifests point to files that are not present at the workspace location. The composer service does run an `inspect` job after encoding for HLS, but it properly rewrites the references and puts all relevant files into a collection. The `inspect` WOH does not do that.

**To Reproduce**

1. Ingest a file using an HLS workflow
2. Run a workflow only containing the `ingest` operation (all flags can be set to `false`)

**Environment Information**

Opencast r/9.x

**Comment by rute-santos** [comment]
Hi @mtneug ,
Did you try adding the _sanitize-adaptive_ woh to your workflow? It's supposed to be used in this case to fix the references.

**Comment by mtneug** [comment]
@rute-santos thanks for your comment! `sanitize-adaptive` indeed fixes the problem. I noticed that this seems also necessary before (re-)publishing. Can you confirm that an `ingest-download` before `sanitize-adaptive` is also required? I noticed that dynamically loading HLS manifests from the asset manager will still lead to wrong manifests after publishing as the manifest files are stored in a different location.

**Comment by rute-santos** [comment]
Yes, _ingest-download_ is required when re-publishing. The urls from the asset manager are not "real"ones so _sanitize-adaptive_ doesn't work with them directly. We had the same issue here :)

**Comment by mtneug** [comment]
Thanks! Thought so and it's all working now :)
