### ISSUE TITLE
Searching LTI resource content item inside LMS needs improvement

### ISSUE THREAD

**Issue by RaiG6** [opencast/opencast#2664]
**Describe the bug**
When embedding Opencast video in Sakai LMS, search functionality is not great. Many videos show up which are not related to the search terms, and it can be very difficult to find the correct video.

**To Reproduce**
1. Open Lesson page
2. Add content
3. Add learning app
4. Opencast Video
5. Launch External Tool Configuration
6. Search

![image](https://user-images.githubusercontent.com/49396348/120202732-398d3280-c227-11eb-9e75-a355ea47b670.png)

**Environment Information**
 - OS: Windows 10
 - Browser: Chrome
 - Opencast version 8
 - Sakai 20

**Comment by lkiesow** [comment]
Hi @RaiG6, this does not look like any tool which Opencast provides. Is it a custom tool?

**Comment by RaiG6** [comment]
Hi @lkiesow, thanks for looking into this.

This is Sakai 20, the URL for the search looks like this:

`https://media.uct.ac.za/ltitools/deeplink/index.html
    ?data={"remember":"always+bring+a+towel","flow":"lessons"}
    &consumer_key=consumerkey
    &content_item_return_url=
        https://vula.uct.ac.za/portal/tool/f8af731e-21ee-4b27-9c05-cd14498d9670/sakai.basiclti.admin.helper.helper
            ?eventSubmit_doSingleContentItemResponse=Save
            &flow=lessons&sakai.session=fc340d82-f701-4029-8474-9d5533801dd1.vula105a
            &returnUrl=https://vula.uct.ac.za/portal/site/00b295b1-fe85-44a8-b92d-89d72c7f125e/tool/8dc7fc0d-19cb-4831-a812-cdafaaa85c00/BltiPicker
                ?73540
                &itemId=-1
                &addBefore=
                &panel=PostContentItem
                &tool_id=228
                &sakai_csrf_token=109ec906003597dda7b14c11007eb573f3dc7ec7658eca27210590083e0847fe` 
                
The content_item_return_url is populated with whatever the LMS expects in return after a selection is made on the page that Opencast returns.

**Comment by lkiesow** [comment]
That seems to be custom code of yours. If you take a look at the current `develop` version of Opencast, there is no https://develop.opencast.org/ltitools/deeplink/index.html. So, it's a local issue and doesn't concern Opencast itself. We can't really help with that. Sorry.
