### ISSUE TITLE
Opencast Studio Download Prompt Improvement

### ISSUE THREAD

**Issue by RaiG6** [opencast/opencast#2690]
**Describe the bug**
After an Opencast Studio recording, users often forget to download a backup copy of their recording, or assume that the download is done automatically. Adding wording as shown in the image below may assist with this issue, and encourage users to download a backup copy of their recording.

![image](https://user-images.githubusercontent.com/49396348/120987870-51f8d200-c77e-11eb-9c5f-b542c7e1e498.png)

**Comment by lkiesow** [comment]
Hi @RaiG6, Studio has its own issue tracker. Can you move this suggestion to https://github.com/elan-ev/opencast-studio/issues ?

**Comment by RaiG6** [comment]
Hi @lkiesow, Thanks and apologies, I have moved the issue over.

**Comment by lkiesow** [comment]
No worries. It's not really obvious if you don't know about it.
