### ISSUE TITLE
Input type=range not recognized as configField in admin UI

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#2703]
**Describe the bug**
Opencast Workflows can contain configuration panels. Fields marked as `configField` (although documentation for that is missing altogether) should be evaluated and used for setting workflow variables. However, not all input types are are considered equally, for instance, the input[type=range] is not.

**To Reproduce**
1. Create a workflow with config field
2. Add an `<input id="audioVolume" name="audioVolume" type="range" min="0" max="100" step="1" class="configField" value="100">` to the config field
3. Go to the Admin UI and start a new WF
4. Slide the audioVolume volume slider to any position
5. No workflow variable `audioVolume` is set

**Environment Information**
 - OS: does not depend on OS
 - Browser does not depend on Browser but [Firefox 23+](https://caniuse.com/input-range) can render an input[type=range] properly
 - Opencast version with minor release 9.4 (9.x branch)
 
**Additional information**

* https://github.com/opencast/opencast/blob/729fecb21a932466e7ed70af1c6de68b8bd9cde9/modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/processing.js#L161 checks if an input/element is ether "textual" or a boolean type. There is no code path to cover other elements/inputs. They are skipped.
* https://github.com/opencast/opencast/blob/729fecb21a932466e7ed70af1c6de68b8bd9cde9/modules/admin-ui-frontend/app/scripts/shared/services/wizards/new-event/processing.js#L151 defines what a textual input is: input[type=range] does not belong to it.

**Comment by Rillke** [comment]
Note to myself:

* PR should have unit test: https://github.com/opencast/opencast/blob/729fecb21a932466e7ed70af1c6de68b8bd9cde9/modules/admin-ui-frontend/test/test/unit/shared/services/wizards/new-event/proccessingSpec.js#L86
* PR should target 9.x
* redmine 7374

**Comment by lkiesow** [comment]
The whole handling of inputs is extremely limited in the current admin interface. Much more was possible in the original interface. But since the next iteration of the admin interface is being worked on, it makes me wonder if we want to redo how the configuration works there. It would also be a good opportunity to leave the horrible HTML + JS snippets behind.

**Comment by Rillke** [comment]
> It would also be a good opportunity to leave the horrible HTML + JS snippets behind.

WF config is neglected by some plugins anyway.

> Much more was possible in the original interface. 

I never had to work with the original interface, I think. You are referring to Version 1's interface?

**Comment by lkiesow** [comment]
> I never had to work with the original interface, I think. You are referring to Version 1's interface?

Yes, I do
