### ISSUE TITLE
"Next" button of the Media Module decreases the page number instead of increasing it

### ISSUE THREAD

**Issue by saraheee** [opencast/opencast#2711]
**Describe the bug**
The "Next" button on the "Series" tab of the Media Module decreases the page number instead of increasing it. 
If page 1 is open, and the "Next" button is clicked, the page number in the url is decreased by 1 (therefore p = 0, -1, -2..). Instead, it should be increased by 1 (thus p = 2, if called from page 1).
The buttons "First", "Previous", and "Last" work correctly. The bug only occurs in the "Series" tab. In the "Episodes" tab the button works correctly.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Create at least 19 series if the number of existing series is less than 19.
2. Add to each of the series at least one video so that the series shows up in the Media Module.
3. Click on the "Series" tab in the Media Module: https://develop.opencast.org/engage/ui/index.html?s=1&p=1
4. Click on the "Next" button on the bottom right.

_Expected behaviour:_
Page number 2 is shown.

_Current behaviour:_
The number in the url is decreased to page 0 and the same page (number 1 in this case) is shown again.

**Environment Information**
 - OS: Windows 10 20H2
 - Browser: Chrome  91.0.4472.101 (Official Build) (64-bit) || Firefox 89.0 (64-Bit)

_Additional notes to related discoveries:_
* In case that only 18 series are available, that all fit on one page, the "Next" and "Last" buttons are shown and the "Last" button forwards the user to an empty page. Instead, both buttons should be grayed out, as there is no "Next" or "Last" page to show in this case.
* After deleting an existing series, it is still shown in the Media Module. Only the videos inside it are removed from the view.

**Comment by ziegenberg** [comment]
I assume, this is one of the problems: https://github.com/opencast/opencast/blob/a2fe06665efacac77b8eace5814f15e0d66bfcce/modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js#L304

And this also doesn't look right: https://github.com/opencast/opencast/blob/a2fe06665efacac77b8eace5814f15e0d66bfcce/modules/engage-ui/src/main/resources/ui/js/app/engage-ui.js#L797
On page `0` this evaluates to `offset=-18`.
