### ISSUE TITLE
Clarify that recordings archived with "fast" workflow cannot be used with other Opencast workflows

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#2733]
**Describe the bug**
I ingest a recording with the "fast" workflow. Once it archives, I attempt to run another Opencast workflow on it and it fails because there are no prepared tagged tracks.

**To Reproduce**
1. Ingest a recording using the "fast" testing workflow
2. Once it archives, run an edit workflow on the archived event
3. See that the edit workflow fails because of no source "prepare" tagged tracks

**Environment Information**
 - Opencast version's after commit https://github.com/opencast/opencast/pull/956

Reference comments in https://github.com/opencast/opencast/pull/1861 regarding making fast compatible with production workflows. Creating replacement pull containing textual warnings that fast archived recordings are not compatible with production workflows.

**Comment by lkiesow** [comment]
They can now.
