### ISSUE TITLE
Series access policy rules not disabled for viewers

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#2792]
**Describe the bug**
When a user with view-only permissions on a series or view-only permissions on series ACLs views a series access policy, they can still tick check boxes and get a message "The access rules have been saved".

**To Reproduce**
1. Create a user with VIEW ROLEs on all admin UI actions, notably `ROLE_ADMIN_UI ROLE_UI_SERIES_DETAILS_ACL_VIEW ROLE_UI_SERIES_DETAILS_METADATA_VIEW ROLE_UI_SERIES_DETAILS_VIEW ROLE_UI_SERIES_VIEW ROLE_UI_EVENTS_VIEW`
2. Create a new series, grant user created in step 1 view permissions in the access policy step
3. Log in as the new user, switch to "series", open the details of the created series and switch to "Access policy"
4. Tick the "write" checkbox for the role of your user and get the message "The access rules have been saved" in spite of a 400 error returned by the server

![Screenshot from 2021-07-03 11-55-26](https://user-images.githubusercontent.com/2311611/124350779-f4c63400-dbf6-11eb-8b56-33af087646ad.png)

**Environment Information**
 - OS: n/a
 - Browser: Firefox
 - Opencast version with minor release 10.x (develop.opencast.org), 8.x (legacy.opencast.org)

N.b. trying to reproduce this on stable.opencast (9.x) caused the system to only report 500 errors after step 4 for events and series in admin UI. Sorry for breaking this system :-(

**Comment by gregorydlogan** [comment]
Resolved by #2793
