### ISSUE TITLE
Index Update Issues

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast#2831]
University of Cologne is reporting issues updating the series and asset manager index on a testing cluster with OC 10, especially with users that aren't admins, though not exclusively so.

Example:
- After a workflow started by a non-admin is concluded, the amount of media files in the assets tab of the event-details modal is 0. This could be the case if the asset manager didn't update the index when creating a snapshot, since during that it sets fields in the index that are later used to decide where to query the media package from. If it still asks the workflow service instead of the asset manager, the amount of media can be 0.
- Sometimes a series does not show up in the table after having been created.
- 
Both issues are fixed by a partial index rebuild. Timing could be in play here, since both the Asset Manager and the Series Service are still using the message queue to trigger the index update, while most other services now do that directly.

I'm gonna look into this further with @mliradelc  to figure out if this is something that could affect other users or if there's something wrong with that specific instance.

**Comment by mliradelc** [comment]
Seems to be solved with #2743 (On research right now)

**Comment by ruthlang1** [comment]
After a restart also of the presentation node everything works as expected, including our workflows. The backport of PR #2742/2743 **is needed** for a distributed OC 10 system.

**Comment by gregorydlogan** [comment]
Fixed with #2743 in 10.1
