### ISSUE TITLE
Embedding codes default to localhost if config option is not set

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast#2883]
The property `prop.org.opencastproject.engage.ui.url` in the organization configuration file (org.opencastproject.organization-mh_default_org.cfg) defaults to `http://localhost:8080` when not set. Therefore, the embedding codes in the Admin UI will also point to `http://localhost:8080`, which makes them not useful.

This is for example annoying in installations where you don't strictly need to set `engage.ui.url`, such as in AllInOne installations. In such a case, it might be better to default to the Admin URL instead of localhost. Or add some documentation on which values need to be configured for embedding codes to work.

**Comment by lkiesow** [comment]
As documented, things which depend on this should default to the server URL.:

https://github.com/opencast/opencast/blob/cc31f1c361c7f9f1626f906575fc0a69836aefa3/etc/org.opencastproject.organization-mh_default_org.cfg#L146-L147

**Comment by lkiesow** [comment]
I just realize, we talk about the embed codes. I would probably use `window.location` as a fallback if `prop.org.opencastproject.engage.ui.url` is unset.

**Comment by mtneug** [comment]
> I just realize, we talk about the embed codes. I would probably use `window.location` as a fallback if `prop.org.opencastproject.engage.ui.url` is unset.

Why? We should always use the publication URL.

**Comment by lkiesow** [comment]
Seems to be fixed by now:
![Screenshot from 2022-02-21 12-51-02](https://user-images.githubusercontent.com/1008395/154950088-3767f227-ee5a-4da4-a4bc-ad46e691f4f8.png)
