### ISSUE TITLE
Moodle Plugin opencast - Video record with Opencast Studio will send back in moodle as invisible for users - that changed

### ISSUE THREAD

**Issue by ahlgrimma** [opencast/opencast#2911]
When you record an video with Open Studio by click "Record Video" in the opencast block plugin in moodle, it will be send back as invisible for the users in moodle. That changed with an update. We don´t know which one, a user told us this days. Now it´s necessary to click on visibility for each single video to alter visibility.

**To Reproduce**

1. in Moodle Block "Opencast Videos" click on "Record Video"
2. in Opencast Studio record any video 
3. after recording set a title and a presenter, then click on "Upload to Opencast"
4. go back to moodle to the Moodle Block "Opencast Videos" and click "Go to overview..."
5. when video proccessing ended the visibility of the new video is invisible

**Environment Information**

 - OS: Ubuntu 18.04.5, Java 11.0.9.1, MariaDB 10.1.47
 - Opencast 8.10 AllInOne installation
 - Opencast 9.7 Debian packages from repo
 - Moodle 3.10.1
 - Moodle Plugins: 
       Opencast Videos [block_opencast] | v3.11-r1
       Opencast [filter_opencast] | 2018031902
       Opencast API [tool_opencast] | v3.9-r1
       Opencast Videos [repository_opencast] | 2018052301

**Comment by lkiesow** [comment]
Studio hasn't changed in a while.
The last change that comes to mind is the configuration change between Opencast 8 and 9:
`git diff r/8.x..r/9.x -- etc/ui-config/mh_default_org/studio/`

```diff
diff --git a/etc/ui-config/mh_default_org/studio/settings.json b/etc/ui-config/mh_default_org/studio/settings.json
deleted file mode 100644
index 71cf595d92..0000000000
--- a/etc/ui-config/mh_default_org/studio/settings.json
+++ /dev/null
@@ -1,9 +0,0 @@
-{
-  "opencast": {
-    "serverUrl": "/",
-    "loginProvided": true
-  },
-  "upload": {
-    "workflowId": "studio-upload"
-  }
-}
diff --git a/etc/ui-config/mh_default_org/studio/settings.toml b/etc/ui-config/mh_default_org/studio/settings.toml
new file mode 100644
index 0000000000..fd9a6178e7
--- /dev/null
+++ b/etc/ui-config/mh_default_org/studio/settings.toml
@@ -0,0 +1,9 @@
+# See https://github.com/elan-ev/opencast-studio/blob/master/CONFIGURATION.md
+# for more information on possible configuration values.
+
+[opencast]
+serverUrl = "/"
+loginProvided = true
+
+[upload]
+workflowId = "studio-upload"
```

Did you maybe not update your configuration?

**Comment by ahlgrimma** [comment]
The new file /etc/ui-config/mh_default_org/studio/settings.toml is present. But also the old file (settings.json) is present too. But can this be the reason for the invisibility?
There was an update for the _Opencast Videos_ moodle plugin in may 2021 that we installed and now i see there is a new one from june 2021 (v3.11-r2). Can the reason found there? In the the release notes i didn´t find any hint on this point.

**Comment by lkiesow** [comment]
It could be the reason because you can specify an access control list template in the Studio configuration. If you did before (in the JSON file) but never moved that configuration to the new toml file, that could be exactly the behavior.

**Comment by lkiesow** [comment]
Closing for lack of feedback. Feel free to re-open if the issue persists.
