### ISSUE TITLE
Zooming in or out in the Paella player affects the control of the video

### ISSUE THREAD

**Issue by saraheee** [opencast/opencast#2927]
**Describe the bug**
The two buttons for zooming the video in and out are placed on top of the video in the Paella player. When one of these zooming buttons is clicked, then also the video is started/stopped at the same time. 

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to the media module and open any episode with the Paella player.
2. Click on the zoom in button on top of the video.

_Expected behaviour:_
The video is zoomed in and the video control is **not** affected.

_Current behaviour:_
The video is zoomed in **and started**. When clicking again on one of the zoom buttons, it is stopped.

**Environment Information**
OS: Windows 10 20H2
Browser: Chrome 92.0.4515.131 (Official Build) (64-bit) || Firefox 90.0.2 (64-Bit)

**Comment by gregorydlogan** [comment]
This sounds like a [Paella](https://github.com/polimediaupv/paella) to me, can you file it over there please?

**Comment by saraheee** [comment]
Thanks for your comment and the link, I moved it to the Paella repo: https://github.com/polimediaupv/paella/issues/760
