### ISSUE TITLE
Admin interface event details shows a maximum of 20 workflows

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2966]
In the admin interface's event details, the workflow tab shows a maximum of 20 workflows with no indication that more workflows exist due to an (probably unwanted) internal limit being set when querying the workflow service:

Note the message saying a workflow is running, while all workflows here have already succeeded:

![Screenshot from 2021-08-27 11-12-50](https://user-images.githubusercontent.com/1008395/131146920-54d81998-8094-4f8d-a5d6-1b4058e01df0.png)

**Comment by Arnei** [comment]
Fixed by #2982, closing
