### ISSUE TITLE
Seems lost this worked merge and also lost the feature.

### ISSUE THREAD

**Issue by fishfree** [opencast/opencast#2981]
Seems lost this merge [MH-13090: Added support for blacklisting languages from the admin UI](https://github.com/opencast/opencast/pull/420).

**Comment by lkiesow** [comment]
This is still in the current version of Opencast:

- https://github.com/gregorydlogan/opencast/blob/develop/etc/org.opencastproject.adminui.endpoint.LanguageServiceEndpoint.cfg

**Comment by fishfree** [comment]
@lkiesow I tried it before posting this issue, but it didn't work.

`org.opencastproject.adminui.languages.exclude=zh_TW`

**Comment by lkiesow** [comment]
Which version of Opencast are you trying this with?

**Comment by fishfree** [comment]
@lkiesow The latest stable version:  Opencast 10.2.0 - 4663d13 - built on 2021-09-06

**Comment by marwyg** [comment]
I checked out 10.2 and configured "zh_TW", the language still appears. I am looking into it.

**Comment by lkiesow** [comment]
IIRC, this got fixed. If I'm mistaken, please re-open this issue.
