### ISSUE TITLE
Is your email up?

### ISSUE THREAD

**Issue by am0o0** [opencast/opencast#2989]
Hello dear opencast team,
Can I ask you to tell me that receive an email from Huntr.dev on security@opencast.org please?
Best regards, Amammad.

**Comment by lkiesow** [comment]
Yes, we did. We will evaluate the reports and see how to address them.

**Comment by am0o0** [comment]
awsome
Can i ask you just vaidate them until you make a parch for fix as soon as possible please?
after validate them they will reamain hidden from public and I can get my bounty from huntr.dev team otherwise i dont able to get bouny.
best regards, Amammad.

**Comment by am0o0** [comment]
Can you give me any feedback dears?

About Huntr.dev procedure :
there is three step for you as a maintainer or as security team that access to reports on the Huntr platform
1. you see the reports and check them if they are valid or not
2. if they are valid you validate them and I get my bounty from Huntr( the reports still hidden from public )
3. After step 2 you create a fix commit on GitHub them submit it
4. After that you submit the fix on Huntr and the report will be published 

If you are in step 2, you can validate my report as they will remain hidden until you create a fix commit and submit it.
And please validate my reports If you evaluate them as a correct issues.
Best regards, Amammad.

**Comment by gregorydlogan** [comment]
Hi @amammad, we're still talking internally. It's on my list to address shortly.

**Comment by am0o0** [comment]
Thank you dear
I just want to sure that you OK with Huntr.dev procedure.

**Comment by gregorydlogan** [comment]
Hi @amammad, please refrain from discussing security related issues in a public issue tracker.  You filed the issue on Huntr, let's discuss it there.
