### ISSUE TITLE
Ldap authorization only isn't working in opencast 10.x

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#3015]
Before opencast 10.x it was possible to include the ldap configuration file to just enable mapping roles to a user via LDAP.
In opencast 10.x this doesn't work ( as before ? ). The user get's looked up via LDAP but no roles are mapped to the user.
When looking at the diff between 9.x and 10.x it seems that the code responsible for this behaviour was removed from modules/userdirectory-ldap/src/main/java/org/opencastproject/userdirectory/ldap/LdapUserProviderInstance.java . It seems that this role mapping still works when using authentication and authorization via LDAP, but we aren't using this.

I've reverted the code for the userdirectory-ldap to it's 9.x state and then the behaviour is again as I would expect it is.

**Comment by Meridiana** [comment]
Same for me ... we use CAS authentication with LDAP authorization and role mapping or adding of extra roles is not working. 
In former versions the roles where added in loadUserFromLdap(...) but that code is now completely removed and an empty hashset is passed instead: 

User user = new JaxbUser(userDetails.getUsername(), PROVIDER_NAME, jaxbOrganization, new HashSet());

It is in this change:
https://github.com/opencast/opencast/commit/6b8303b2ba5a3d684df36992ec32b73fefd95c5a

I reverted the userdirectory-ldap to 9.x too, and its working again.

**Comment by Meridiana** [comment]
Anything new about this?

**Comment by trueeh** [comment]
Same for 11.x

Very painful to compile the 9.x again and again ...

**Comment by mliradelc** [comment]
Hi, It is just merged #3344 that should fix your problems. Today I will release the new version with this fix.

**Comment by mliradelc** [comment]
@kristofkeppens Because is fixed in 11.x, Should I close this issue?

**Comment by kristofkeppens** [comment]
This can be closed!

**Comment by trueeh** [comment]
Great news, thankyou very much!
