### ISSUE TITLE
Search Service not returning signed URLs

### ISSUE THREAD

**Issue by tkurze** [opencast/opencast#3017]
### Short description
The search service is not returning signed URLs for events even when instructed to do so and stream security has been configured correctly and is working otherwise (/api/events, /sign, e.g.).

#### Example
For example: When calling /search/episode.json?sign=true, a list is returned, but the url(s) are unchanged: no policy, no signature, etc.:
{
  "search-results": {
    "offset": 0,
    "limit": 3,
    "total": 3,
>[...]<
                },
              "url": "http://localhost:8080/static/mh_default_org/engage-player/ecf93214-2d13-4a6e-bf2d-e8d4edb477d2/71b809c1-25d0-4b1e-a48f-95fd7dc57fb3/output.mp4",
              "size": 16145008,
         >[...]<

#### External API (seems) unaffected
A call to /signing/accepts providing the above URL return true, and /signing/sign returns: 
http://localhost:8080/static/mh_default_org/engage-player/ecf93214-2d13-4a6e-bf2d-e8d4edb477d2/71b809c1-25d0-4b1e-a48f-95fd7dc57fb3/output.mp4?policy=eyJTdGF0ZW1lbnQiOnsiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6MH0sIlJlc291cmNlIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwODBcL3N0YXRpY1wvbWhfZGVmYXVsdF9vcmdcL2VuZ2FnZS1wbGF5ZXJcL2VjZjkzMjE0LTJkMTMtNGE2ZS1iZjJkLWU4ZDRlZGI0NzdkMlwvNzFiODA5YzEtMjVkMC00YjFlLWE0OGYtOTVmZDdkYzU3ZmIzXC9vdXRwdXQubXA0In19&keyId=demoKeyOne&signature=339463ca139cda2d721f235ed4786c727c48bf87ff4744209da2a9b5fa372c07

### Impact
This behavior impacts the Media Module when using external web servers to deliver content (Apache, e.g.) as no valid signature (etc.) is provided, Apache does (correctly) deny access to protected resources, rendering the media module, engage, etc. useless.
This bug does *not* concern access through the external API, /api/events, e.g.

### Concerned Opencast Versions
We observed this behavior first, after upgrading our test-system from Opencast 8 to 9.8. There is also a chat on this in the user group: https://groups.google.com/a/opencast.org/g/users/c/dWgckUnxKmc/m/OKUftN0KBAAJ that indicates, that the problem still exists also in Opencast 10. (Probably also in 11?)
I'm seeing the same behavior when building from the sources directly. 

### My investigations
I investigated a little, and i think the problem cause might be linked to changes in org/opencastproject/mediapackage/MediaPackageBuilderImpl.java. 
The org.opencastproject.search.impl.SearchServiceImpl uses SolrRequester to create a search result (by createSearchResult on a solrRequester). During this call a SearchResultItemImpl are generated and their method getMediaPackage is overwritten. In this very method a MediaPackageBuilder is instanciated and a serializer is set *if* signed is set. (Signed is set, if chosen so during the call to /search/episode.)

#### what to blame? (#faf6b8f, ?)
The MediaPackageBuilderImpl has changed (https://github.com/opencast/opencast/compare/faf6b8f..c41dd20?diff=split) and the method loadFromXml now does not account for the serializer set before. Apparently there was some good reason for this (indicated by the comment // FIXME This code runs if *any* serializer is present, regardless of the serializer implementation), but it seams wrong, to ignore a serializer just set before. (Instead LSSerializer is used in valueOf of the same class).

I added some debug code, and indeed – if using the old version of the file (git checkout 17f54e0 [...]/MediaPackageBuilderImpl.java), I can see in my log, that the SigningMediaPackageSerializer is used. But this is not a fix for the bug, as a lot of the output of /search/episode also gets screwed up by this. So there must be some more changes involved and just going back to the old version (inkl. // FIXME) sounds wrong to me.

**Comment by mliradelc** [comment]
Hi Tobias, I'm researching right now this problem, and as you said, it comes from the search service. Yesterday I've got the debbuger working again, and I've found the same! 😄 . 
I was not sure because for some reason my local system wasn't making the publications like our clusters (But the media endpoints were the same from the search service).

**Comment by tkurze** [comment]
Hi Maximiliano, I'm happy that I'm not the only one investigating :-) I've already browsed quite a few times through the Opencast code base; but this is the first time I'm actually modifying it (though only for debugging). I'm not yet familiar how all the bits and pieces work together (and why the above mentioned code should apparently not run for some serializers, etc.) So glad that you are researching this as well :-) Thanks a lot!

**Comment by mliradelc** [comment]
From the commit that changed that part I remember for what was, but from the other part @lkiesow  wrote another serializer, I will try to insert that serializer into that part, I hope that will work.

The complicated is, that bug is deep into the code, the common packages are very critical.

**Comment by tkurze** [comment]
OK. Good that you remember the cause. I'll continue next week. Also if there is something specific you want me to check out – let me know :-)

**Comment by mliradelc** [comment]
Thanks to you for posting this. I was wasting time fixing some annoyances in my test setup only to confirm it was the real cause. 

That commit was because sometimes there are multi-byte characters in the mediapackages, and opencast explodes because of a faulty serialization. That commit was to fix that.

**Comment by mliradelc** [comment]
Update: I'm working actively on this, I tried to retreat this PR but opencast totally exploded (Because this code is from a Core part of Opencast). 

I think that I have "sort of" a solution, but I hope to have it soon for release.


In another discovery, there is a patch that was made by another university that is not in the signing service, I thought that was merged in opencast 8.x or 9.x, but I was wrong, I will contact them if it is possible to submit it before the feature freeze of OC 11. (Allows Wowza to sign http / https streams with the OC signing service).

**Comment by tkurze** [comment]
That sounds very good (except for the explosion part ;-) ). Sadly I haven't had a lot of time to continue my investigation myself, and probably I won't have soon. But you are way more experienced (and able to find a solution) then me anyways. So: thanks again :-) and let me know if there is something specific I could/should checkout.

**Comment by mliradelc** [comment]
Hi @tkurze , Can you try the PR I made?

Thanks!

**Comment by tkurze** [comment]
Hi Maximiliano,
as soon as I'm back to work I certainly will. For private reasons I
probably won't be able to try the PR before mid-November.

Tobias

**Comment by tkurze** [comment]
Hi @mliradelc , 
I just checked your PR (10.x-stream-sec-fix) and it fixes the mentioned problem: The search service now returns signed URLs. 
Thanks a lot!
Tobias

As there is still a discussion going on regarding the PR, I' haven't closed the issue atm.

**Comment by gregorydlogan** [comment]
Merged into r/10.x.  Will be present in 10.6 and 11.0.
