### ISSUE TITLE
At least one role with Read and Write permissions is required!

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#3118]
**Describe the bug**

*When I click on an Event details icon in the Admin UI I get a warning message 'At least one role with Read and Write permissions is required!' in spite of such a role being present.*

https://user-images.githubusercontent.com/2311611/139686597-21a0f67e-3342-43ec-aac6-bae735800284.mp4

**To Reproduce**
1. https://legacy.opencast.org/admin-ng/index.html and sign in
2. Click on a blue "event details" icon
3. Notice the warning "At least one role with Read and Write permissions is required!"

**Environment Information**
 - OS: Demo installation
 - Browser: Firefox 93.0 (64-bit)
 - Opencast version with minor release Opencast 9.0.0.SNAPSHOT - a1cef0e - built on 2021-11-01

**Comment by Rillke** [comment]
I can't see this in our production, yet.

**Comment by lkiesow** [comment]
IIRC, this got fixed in 10.x. I at least can't reproduce this on develop.opencast.org. If it's important, let's reopen this but since 9.x is the legacy version, I suggest closing this issue and ignoring this on the legacy version. Any opinion?

**Comment by Rillke** [comment]
@lkiesow Thanks for testing this on stable.
