### ISSUE TITLE
Media Module only lists one creator

### ISSUE THREAD

**Issue by scharnkn** [opencast/opencast#3165]
**Describe the bug**
After publishing a video with multiple creators, the media module only lists one single creator.
I found that there was a [pull-request ](https://github.com/opencast/opencast/pull/2501)that was supposed to change that behaviour to show a short list with "...", but it does not seem to happen in current versions of Opencast.

**To Reproduce**
Use e.g. one of the test servers (e.g. https://legacy.opencast.org/) and upload a video with more than one creator (I used the "Process upon upload and schedule" workflow). 
Wait until the event is published.
Open the media module at https://legacy.opencast.org/engage/theodul/ui/core.html?id=XXX
Below the video, only one creator is listed, even when there are more.

**Environment Information**
 - Could be reproduced with Opencast version 9.x, 10.x

**Comment by ziegenberg** [comment]
PR #2501 fixed it for https://legacy.opencast.org/engage/ui/index.html, not the theodul player. You are looking for a fix in the theodul player.

**Comment by ziegenberg** [comment]
theodul requests data from `search/episode.json` and goes for `search-results.result.dcCreator` which only contains one entry.

I guess, for a fix it should use `search-results.result.mediapackage.creators` instead, like the PR #2501 does it.
