### ISSUE TITLE
Extend Metadata Extraction in Inbox

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#3239]
Opencast's inbox allows you to add zipped media packages which may contain arbitrary metadata but are very complex or to add simple files, which file names will end up as the new event's title. It would be nice if it would be possible to extract a few more basic metadata from the filename.

File names like these are commonly generated by capture devices:
```
2020-02-07-hs1-Introduction to Biology.mp4
 |    |  |  |  |                     |
year  |  |  |  +----------+----------+
   month |  |             |
        day |           title
        location
```

To improve the situation, and to be as flexible as necessary, we would like to allow for specifying regular expressions as matchers for a few basic metadata.

**Comment by llttugraz** [comment]
For example, we use Epiphan recorders to automatically upload recordings via (s)FTP to the Opencast inbox folder. In the Epiphan settings you can set a prefix for the recording file names (normally one per recorder). We use a short venue code for this. The rest of the file name consist of the start date/time of the recording (standard Epiphan setting).
eg:
hs1_Oct13_12-02-15.mp4

You could use eg regex to extract this info and insert it to the corresponding metadata fields:
(hs1)_(Oct13_12-02-15).mp4

where
$1 = location
and
$2 = startdate (with respective parsing; note: year is missing)


https://www.epiphan.com/userguides/pdfs/Epiphan-PearlMini-UserGuide.pdf
<img width="820" alt="image" src="https://user-images.githubusercontent.com/28404082/145210301-9cef4104-2a74-46f4-8218-a4b15bfd0118.png">
