### ISSUE TITLE
Match inbox events against schedule

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#3240]
This is based on an implementation for #3239.

Capture agents often record files to file names containing metadata which allows us to identify an event by looking at a specific time in the schedule of a certain location (capture agent).

It would be nice if the inbox could use this to identify an event and extend the metadata of ingested media.
This needs to be an optional setting and should be turned off by default.

**Comment by llttugraz** [comment]
By evaluating the location and timestamp of a recording, it should be possible to assign it to a scheduled recording (from the registered calendar data) without the need to know its specific ID. This would allow the planning and scheduling of recordings from arbitrary sources (non-CA) and their automatic assignment to their respective series, workflows, etc. at ingest
