### ISSUE TITLE
Run authentication logic as soon as HTTP headers are received and don't wait for the body

### ISSUE THREAD

**Issue by LukasKalbertodt** [opencast/opencast#3245]
Currently, the authentication logic (e.g. JWT validation) only runs once the full HTTP request is received. This is usually not a problem, but has disadvantages when the request is huge, e.g. for `/ingest/addTrack`. In those cases, there might be a significant time difference between "header received" and "full body received". For authentication schemes that have expiring tokens, like JWT, this is a problem. 

For example, JWTs in many cases should be valid only for a very short time (in the order of a few minutes). If some user tries to upload a video via `/ingest/addTrack` with JWT authentication, the JWT needs to be valid until the upload is complete. Of course, that could take a long time (in the order of hours). Making JWTs valid for that long is usually a big security risk. So in this case, it would be very beneficial to check the JWT once the HTTP headers are received.

Background: this came up when implementing a video uploader for Tobira. The Tobira JS code running in the user's browser communicates directly with Opencast (cross origin). Right before each request to Opencast, a new JWT is request from the Tobira backend and used in the Opencast request.

**Comment by JulianKniephoff** [comment]
Our bad. This is already exactly how the system works. Our reverse proxy was just buffering the request. :sweat_smile: 

It's interesting to note, though, that the situation is rather fragile if I understand everything correctly: If some part of the system (e.g. some filter in the authentication filter chain) touches the body of the request (for example to parse form parameters) before it arrives at the JWT filter we are back to the situation described in the OP.
