### ISSUE TITLE
Mass action support for resource entries of courses

### ISSUE THREAD

**Issue by colradectug** [opencast/opencast#3246]
Opencast allows to set the visibility of each Video by clicking on the "eye" icon. However, it is not possible to select multiple videos at once. 

![image](https://user-images.githubusercontent.com/95869793/145433601-8600d555-bc1d-4b5e-9cd4-7e7b9d41fd71.png)

One could consider checkboxes with the action to be chosen from a drop-down menu at the bottom of the table (to be done with mass-actions) in addition to the existing columns.

**Comment by lkiesow** [comment]
Hi @colradectug, I have no idea where you found this, but the screenshot is not from any Opencast user interface. Maybe you are using one of the LMS plugins? If you do, you should report the issue there.

**Comment by mtneug** [comment]
This is from the Moodle LMS plugin.

@colradectug: the plugin already started moving away from LTI and managing viewer specific ALCs in Opencast. Using the new activity plugin, you no longer need to set visibility in the block and can simply use the Moodle internal mechanisms for controlling access to activities.
