### ISSUE TITLE
Choose visibility in resource upload form

### ISSUE THREAD

**Issue by colradectug** [opencast/opencast#3247]
When uploading resources, the visibility of those are automatically set to visible. A checkbox for choosing the visibility of the resource manually before uploading would be helpful for many users. This checkboxes (advcheckbox) default value could be set with admin_settings to be either default_visible or default_hidden.

**Comment by lkiesow** [comment]
I'm somewhat confused. Can you explain which upload form you are talking about? Event visibility is always controlled via the event's ACL which you can set.

**Comment by lkiesow** [comment]
Based on your other request not being about opencast, I assume this one is about one of the Opencast plugins as well. That's why I'm closing this. In case this is actually about Opencast, don't hesitate to re-open the issue and explain which UI you mean.

**Comment by mtneug** [comment]
This is probably Moodle again and the change in design to letting Moodle handle access internally opens up the host of mechanisms of Moodle to handle this.
