### ISSUE TITLE
Add *.trec/Camtasia files to known mimetypes / how to handle unknown file types?

### ISSUE THREAD

**Issue by scharnkn** [opencast/opencast#3349]
Currently it is not possible to upload Camtasia/*.trec video files to Opencast. The reason seems to be that the file extension does not have a mimetype defined in the [MimeTypes.xml](https://github.com/opencast/opencast/blob/develop/modules/common/src/main/resources/org/opencastproject/util/MimeTypes.xml) resource. This causes Opencast to reject the file although ffmpeg could re-encode it in theory.

The current work around is to rename the file and change the file extension to another video format like e.g. mp4 and upload the renamed file. ffmpeg will correctly recognize the filetype/codecs regardless of the file ending.

As suggested on the mailing list, this poses the general question of how unknown filetypes should be handled.

In my opinion, it is be justified for a file extension to be added to the mimetypes resource, if the ffmpeg version shipped with all supported OS's (Debian, Fedora, CentOS) can handle the codecs. 

For the video codec used by Camtasia (tscc2) it is supported at least on ffmpeg shipped with Debian 11/stable.

**Environment Information**
 - OS: Debian 11
 - Opencast version with minor release: 10.5.0

**Comment by gregorydlogan** [comment]
We definitely should add `trec` into the mimetypes file - Camtasia is well known and other users are likely to run into this.

Adding *all* of the supported file extensions however, might be a bit too far.  That's both a long list, and a maintenance nightmare where we now have to be both *very* sure that all of our ffmpeg releases are the same version across Debian, RedHat, and Docker, as well as keeping the list itself up to date.  On top of that, at least for Debian, I don't enforce anything ffmpeg related aside from the presence of a `ffmpeg` package, or a `ffmpeg-dist` package.  If your Ubuntu box comes preinstalled with ffmpeg, then when you install Opencast you'll be using whatever version of ffmpeg came shipped with your Ubuntu distribution, *not* the version I package.

I would prefer to handle this on a per-filetype basis - if you're running into an issue complain and we can add support.  I feel like going forward, aside from some very unusual edge cases the vast majority of incoming files are going to be mp4, mkv, or whatever Apple's newest filetype is.

**Comment by scharnkn** [comment]
That sounds sensible. I agree that it would be way too much work to maintain a full list of all possible file types.
Maybe another way to deal with this issue would be to allow users to define their own mimetypes via config files.

**Comment by gregorydlogan** [comment]
It would also make this less painful when this inevitably happens again :)

We'll see what kind of time I can scare up.
