### ISSUE TITLE
User gets removed from groups after Shibboleth login (since OC11)

### ISSUE THREAD

**Issue by jduehring** [opencast/opencast#3509]
I am working with a customer who uses Shibboleth to Login into the Opencast Admin-UI and who has described the following behaviour: 

1. Enable the bootstrap user and use it to add some user xy to some group, for example the `Default System Administrator` group.
2. Disable bootstrap user and check whether user xy has entered the group and has gotten the new admin roles.
Now...
2.1 If the user xy was already logged in and one just refreshed the admin-ui, one could see that everything seemed to have worked.
2.2 But if the user needed to login, he got removed from the group and the respective roles.
3. Same happens after user xy logs out and in again after 2.1

-> So basically every time a user is logging in, he gets removed from all assigned groups. 

Since this behaviour came up after upgrading to OC 11, I checked and found [this](https://github.com/opencast/opencast/pull/3157) merge/commit, which we confirmed led to the new behaviour. 

Then I started looking into the code and got a bit confused.
This method:
https://github.com/opencast/opencast/blob/9035e7bbfe1ca294dbad783388d41eeb174fd0b0/modules/userdirectory/src/main/java/org/opencastproject/userdirectory/JpaUserReferenceProvider.java#L376-L394
is called each time a user is logging in. The aim of this method seems to be to check the assigned roles of a user and with the next call compare them with the groups the user is part of. If a role does not match with the primary group role, the user get removed from the respective group. 

But after some debugging it seems like the call `user.getRoles()` only gets the actual roles of the user, not the primary role from a group (the one typically starting with `ROLE_GROUP`). My assumtion is that this leads to an empty `internalGroupRoles` / `rolelist` and therefore the user gets removed from the group in each case. 

Before the mentioned commit, this check didn't even take place, since it was restricted to groups with a specific prefix.

It would be great, if someone can reproduce this behaviour to confirm it has nothing to do with any false configurations or just give some more insight. It is hard to test any changes for this module in my local enviroment. 

**Environment Information**
 - OS: [Rocky Linux 8.5]
 - Opencast version [11.3]

**Comment by lkiesow** [comment]
Initial thoughts after reading this:

```java
(Role.Type.GROUP.equals(role.getType()) || (Role.Type.INTERNAL.equals(role.getType())
```

Do the roles exist at all on the users? If so, could they have a different type?

> it seems like the call user.getRoles() only gets the actual roles of the user, not the primary role from a group (the one typically starting with `ROLE_GROUP`).

My guess is that adding a user via the user interface only adds it to the database table `oc_group_member` and we have some code looking for users in there. This means, we likely assume that users do not need to have the primary role (`ROLE_GROUP_XY`) but could be member without having that. If that assumption is correct, we should never remove any groups based on their primary roles not being present in the list of a user's roles.

If we say, having a primary role defines group membership, then we need to make sure we always add the primary group role to users when we add them to a group. Though, I'm then kind of wondering what the `oc_group_member` table is used for.

All this is guesswork, though, and I don't really know the code well. But maybe it helps as a starting point for investigating.

**Comment by AL-THD** [comment]
We are currently working to update to Opencast 11.4 and can reproduce this on our test – environment.

<br>
<b>System Information:</b>

Cluster: 1 admin VM, 1 worker vm, 1 engage vm

Opencast Version 11.4

OS: CentOS 7 (Red Hat 4.85-39)

MariaDB Server V 10.7.3

Shibboleth Authentication

<br>
Our current workaround is to use a bootstrap user, but this is barely workable even in our test – environment.

For production, this bug makes Opencast for us absolutely unworkable.

<br>

As we need to update our System as soon as possible, and with the new Semester looming above our heads, we would greatly appreciate a fast fix for this bug.

**Comment by AL-THD** [comment]
I will update to 11.5 and try if this bug is still around.

**Comment by AL-THD** [comment]
Opencast 11.5 did <b>not</b> solve this issue.

<b>Reproduce:</b>
1. Use Opencast with Shibboleth login
2. in the admin UI open Groups
3. create an Admin - Group
4. add an accout to this Admin - Group
5. as soon as this account logs into the Opencast Admin UI using Shibboleth Authentification, the user gets removed from this group

If you want I can provide Error Logs too. 

<b>More Tests:</b>

<b>OC_group_member</b>
I dug some more into the code.
As you asked what the `oc_group_member` table is used for, these are my observations:

After creating a group in the admin UI, I can add users to this group.
These users get put into `oc_group_member` with `group_id`and `member (=user name)`.
If I put members in a control - group, they get the same `group_id` and everything is written into the Database correctly.
Now, if the user logs uses shibboleth for authentification, the session gets created. - But at the same time, the user gets deleted from the `oc_group_member` table.


![THD-mariaDB-oc_group_member-Ansicht](https://user-images.githubusercontent.com/101559361/160410222-4a2d71a0-d143-4757-8ee7-ad6985cfa6a7.png)

**Comment by uniwuerz-mf** [comment]
Hi there. We are having the exact same problem with our OpenCast 11.4 installation. 

We would also greatly appreciate a fast fix for this bug. Hopefully before our Semester starts. If you need we can provide some additional information.

Greetings University of Wuerzburg.

**Comment by jduehring** [comment]
I'm on it now!

**Comment by jduehring** [comment]
@uniwuerz-mf @AL-THD I wrote a patch that was already tested by the University if Vienna. We'll probably discuss this again on the technical meeting next tuesday and then hopefully merge it right away!

**Comment by uniwuerz-mf** [comment]
Do you know in which release this bug will be fixed? Still there in OC 11.7.

**Comment by lkiesow** [comment]
Pull request #3672 is still open. It will be in the next release once it has been reviewed and merged.
There is at least one open issue with the current patch, and Jonas is off work for the next two weeks.
Feel free to jump in and help if you want to.

**Comment by mliradelc** [comment]
The PR #3672 is merged, I will close this issue, if persists, please open it again.
