### ISSUE TITLE
Create Series Script - Certificate Error

### ISSUE THREAD

**Issue by sigapb** [opencast/opencast#3515]
I ran the recommended create- series.sh script and got the certificate error below

Curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server u
sesc uar lc:e r(t6i0f)i cPaeteer 'ssi gCneerdt ibfyi caa tCeA  irsespureers einsendo ti nr
e ctohgen ibzuendd.l
eM,o rteh ed ectearitlisf ihceartee:  vhetrtipf:i/c/actuiroln. hparxoxb.asbel/ydfcasi/lsesdl cdeuret st.oh tam
l
p
rcoubrlle mp ewriftohr mtsh eS ScLe rcteirftiicfaitcea t(ei tv emriigfhitc abteienx pbiyr edde,f aourl tt,h eu snianmge  am i"gbhutn
d lneo"t
  moaft cChe rtthief idcoamtaei nA untahmoer iitny  t(hCeA )U RpLu)b.l
iIcf  kyeoyus' d( ClAi kcee rttos )t.u rInf  otfhfe  cduerfla'usl tv
e rbiufnidclaet ifoinl eo fi stnh'et  caedretqiufaitcea,t ey,o uu scea
n  tshpee c-ikf y( oarn  -a-litnesrencautree )f iolpet
i ouns.i
ng the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by sigapb** [comment]
Added the -k and the test series was created. Thanks

**Comment by gregorydlogan** [comment]
@sigapb I'm not entirely sure what happened to the middle of that error message, but the gist of what it's trying to say is that your server's SSL certificate can't be verified by the client (ie, curl).  So either your server is misconfigured (or has a bad cert), or your client is missing some intermediate certificate(s) in the chain.  `-k` will work fine for testing, but if your users have the same issue it's generally a better idea to fix the server :)
