### ISSUE TITLE
Admin UI: Metadata editing in editor not working

### ISSUE THREAD

**Issue by CGreweling** [opencast/opencast#3529]
since OC11 you can not edit metadate in the OC Video Editor.
The metadate fields are not shown.

**To Reproduce**
1. Go to 'admin ui'
2. Click on 'editor for event'
3. got to tab 'metadata'
4. no metadata is shown

**Environment Information**
 - OS: [fedora 34]
 - Browser [Chrome]
 - Opencast version with minor release [11.x, develop]

**Comment by narickmann** [comment]
Metadata fields are now shown, but not saved. I have no clue why. 
If anyone has an idea I would be greatful to let me know.

**Comment by stefanosgeo** [comment]
@naweidner which version are you using? I our dev servers with version 11.5.0 problem is still present..as well as in stable.opencast.org.  I think is not fixed yet.

**Comment by Rillke** [comment]
https://github.com/naweidner/opencast/commit/7e3f3af3817460a41294599b051ea9fa7a828583 is not requested to be pulled and therefore not merged, yet.

With "are now shown" @naweidner referred to their custom build of Opencast with the linked patch applied.

**Comment by mliradelc** [comment]
@naweidner Can you make a PR with your fix?, I will gladly review it.

**Comment by Rillke** [comment]
@mliradelc I'm testing currently a patch based on @naweidner's work. Will submit as soon as build completed and test is successful.

**Comment by mliradelc** [comment]
Thanks, @Rillke, I was waiting for @naweidner answer, and if she didn't answer, I would like to make it with the comments you left in her branch.

Please tag me to review it.
