### ISSUE TITLE
Lti series tools: edit doesn't work in distributed installs

### ISSUE THREAD

**Issue by kristofkeppens** [opencast/opencast#3556]
The edit form returns the error that the metadata can't be retrieved ( from the lti-service-gui/***/metadata endpoint ). This does work from the admin node however, but not from the presentation node. The series tool on the other hand only works from the presentation node, so running this on admin is not possible. This used to work however.

**Comment by mtneug** [comment]
@kristofkeppens is this fixed now?

**Comment by kristofkeppens** [comment]
This was fixed, forgot to close the issue.
