### ISSUE TITLE
Missing tags when encoding multiple qualities with the encode WOH

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#3639]
**Describe the bug**
When encoding multiple qualities using the encode WOH the media created is not tagged with the suffix. This is a regression introduced beteween Opencast 9 and Opencast 11.

**To Reproduce**
1. Go to https://stable.opencast.org/admin-ng/index.html#!/events/events
2. Login as admin
3. Start the Process upon Upload and Schedule WF on any media you like, and send the file straight to publishing
4. Multiple Qualities are created in one encode WO. [[1]](https://github.com/opencast/opencast/blob/r/11.x/etc/workflows/partial-publish.xml#L218) [[2]](https://github.com/opencast/opencast/blob/r/11.x/etc/encoding/opencast.properties#L34L38) but none of them are tagged as `480p-quality` or similar.

![image](https://user-images.githubusercontent.com/2311611/162213713-b6f0d132-24ac-4066-b63a-de6063782ba4.png)

**Environment Information**
 - Opencast version with minor release Opencast 11.0.0.SNAPSHOT - 1c5fa68 - built on 2022-04-07, 11.4

**Comment by lkiesow** [comment]
Likely caused by this change in `ComposerServiceImpl.java` between Opencast 10 and 11:

```diff
-      List<String> tags = profile.getTags();                                                                                                                                                                                                 
-      for (String tag : tags) {                                                                                                                                                                                                              
-        if (encodingOutput.getName().endsWith(profile.getSuffix(tag)))                                                                                                                                                                       
+      for (final String tag : tags) {                                                                                                                                                                                                        
+        if (inspectedTrack.getURI().getPath().endsWith(profile.getSuffix(tag))) {                                                                                                                                                            
           inspectedTrack.addTag(tag);                                                                                                                                                                                                        
+        }                                                                                                                                                                                                                                    
+      } 
```

**Comment by Rillke** [comment]
In the line `inspectedTrack.getURI().getPath().endsWith(profile.getSuffix(tag))` Opencast set the following values:

* `tag`=`mp3`
* `inspectedTrack.getURI().getPath()`=`/files/collection/composer/248581_0.mp3`
* `profile.getSuffix(tag)`=`-audio.mp3`

So essentially, the `inspectedTrack.getURI().getPath()` will never end with `profile.getSuffix(tag)`.

----

Encoding profile used:

```
profile.parallel.http-audio.name = parallel audio encoding
...
profile.parallel.http-audio.suffix.mp3 = -audio.mp3
...
profile.parallel.http-audio.ffmpeg.command = ...
```
