### ISSUE TITLE
Inbox Scanner assignment of scheduled events: issue when ingesting >1 recordings for same scheduled event

### ISSUE THREAD

**Issue by ypatios** [opencast/opencast#3649]
**Describe the bug**
If more that one recordings are sequentially copied in the inbox folder for the same scheduled event, there are issues with ingesting (usually eg in case of 2 files, the second one hangs in the inbox).
This is a frequent case as lecturers often take a break or they run a short test recording at the beginning of a lecture.

Probably this issue is related to this one:
https://github.com/opencast/opencast/issues/2276

**To Reproduce**
1. Schedule an event that lasts 2 hours
2. copy a file that corresponds to the first part of this event to the inbox folder
3. copy a second file that corresponds to the second half of the same scheduled event to the inbox folder

**Suggested solution**
Automatic ingesting of scheduled events should allow for more than one parts of the same event to be ingested; this could be done by:
– before ingesting, check status of respective media package (maybe wf running?)
– if status "scheduled" then ingest as usual
– if status eg "running" then copy the event to a new media package and ingest the new media to this new media package (named as "... – part 2", "...–part n", for example

**Comment by lkiesow** [comment]
To complete that list, right now if you ingest a second file for the first event, it would overwrite the first one. Would you generally expect new ingests to always create new events if there is one already in the system? Or just if the existing event has a running workflow?

**Comment by ypatios** [comment]
I guess it would be safer to always create a new (copy) of the respective media package with the new media. Manual adjustments can be done by admins. Maybe in a next version we can make the algorithm more intelligent, so that it can decide according to the metadata if the new ingest should be regarded as a replacement to the first one or as an additional part of the same event
