### ISSUE TITLE
Red check mark when editing metadata is ambigious

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#3738]
**Describe the bug**
A clear and concise description of what you see:
When editing meta data in the admin UI, a red check mark is shown on changed (dirty/unwritten) fields. Red is not distinguishable from green for some people, and the check mark as an indicator for unsaved changes is not obvious.

![image](https://user-images.githubusercontent.com/2311611/166655501-6068e617-aa50-472d-b55c-95e8e5ebe9e7.png)

**To Reproduce**
1. Go to https://stable.opencast.org/
2. Click on an episode's metadata icon ![image](https://user-images.githubusercontent.com/2311611/166658219-c8f255a8-21c0-4eab-8419-b873ad18b093.png)
3. Edit a metadata field
4. See red check mark ![image](https://user-images.githubusercontent.com/2311611/166658725-9ddd2ca4-fd52-4e24-adcf-d22de578f6a9.png)

**Environment Information**
 - Opencast version with minor release Opencast 12.0.0.SNAPSHOT - 2ce87d6 - built on 2022-05-04

**Comment by lkiesow** [comment]
We had a discussion about checkmarks like these in the new editor as well and agreed that they are really confusing. The editor ended up not showing these at all, but just showing an error icon if something went wrong.
