### ISSUE TITLE
Removing activemq in Ubuntu also removes opencast-12-allinone

### ISSUE THREAD

**Issue by insad** [opencast/opencast#3884]
Installing opencast-12-allinone on Ubuntu also installs activemq. If you want to try to remove activemq, also opencast-12-allinone is being removed.
But documentation says activemq is not used anymore, and can be removed.

**Comment by gregorydlogan** [comment]
Whoops, forgot about that. Will address on Monday.

**Comment by gregorydlogan** [comment]
This is fixed in 12.0-2, which is uploading now.
