### ISSUE TITLE
Can't build from source, can't build frontend

### ISSUE THREAD

**Issue by xx1182** [opencast/opencast#3982]
**Describe the bug**
*Can't compile front-end component*

**To Reproduce**
1. Git clone '...'
2. Mvn clean install '....'
3. See error

**Environment Information**
 - OS: Debian on Termux
 - Browser: None, headless server
 - lastest commit

The error:

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.3:grunt (grunt build) on project opencast-admin-ui-frontend: Failed to run task: 'grunt build --skipTests=false' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 3 (Exit value: 3) -> [Help 1]               org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.3:grunt (grunt build) on project opencast-admin-ui-frontend: Failed to run task                        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)              at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                            at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                          at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                              at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                               at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                             at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                     at java.lang.reflect.Method.invoke (Method.java:566)                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                              at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)         Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task                   at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100)                        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                  at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)              at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                            at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                          at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                              at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                               at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                             at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                     at java.lang.reflect.Method.invoke (Method.java:566)                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                              at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)         Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'grunt build --skipTests=false' failed.                     at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:63)                                  at com.github.eirslett.maven.plugins.frontend.mojo.GruntMojo.execute (GruntMojo.java:64)                                               at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)                         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                  at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)              at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                            at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                          at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                              at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                               at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                             at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                     at java.lang.reflect.Method.invoke (Method.java:566)                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                              at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)         Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: org.apache.commons.exec.ExecuteException: Process exited with an error: 3 (Exit value: 3)          at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:82)                                    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64)                   at com.github.eirslett.maven.plugins.frontend.lib.NodeExecutor.executeAndRedirectOutput (NodeExecutor.java:29)                         at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:58)                                  at com.github.eirslett.maven.plugins.frontend.mojo.GruntMojo.execute (GruntMojo.java:64)                                               at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)                         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                  at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)              at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                            at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                          at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                              at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                               at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                             at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                     at java.lang.reflect.Method.invoke (Method.java:566)                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                              at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)         Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 3 (Exit value: 3)                                       at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)             at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:74)                                    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64)                   at com.github.eirslett.maven.plugins.frontend.lib.NodeExecutor.executeAndRedirectOutput (NodeExecutor.java:29)                         at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:58)                                  at com.github.eirslett.maven.plugins.frontend.mojo.GruntMojo.execute (GruntMojo.java:64)                                               at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)                         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                  at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)       at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)              at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                            at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                          at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                              at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                               at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                             at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                     at java.lang.reflect.Method.invoke (Method.java:566)                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                              at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)         [ERROR]                                      [ERROR]                                      [ERROR] For more information about the errors and possible solutions, please read the following articles:                              [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException    [ERROR]                                      [ERROR] After correcting the problems, you can resume the build with the command          [ERROR]   mvn <args> -rf :opencast-admin-ui-frontend        `root@localhost:~/opencast#`

**Comment by lkiesow** [comment]
The stack trace you posted only tells us that `grunt build --skipTests=false` failed, not why. That's probably in some of the other logs. But if you say that you do not have a browser installed, then that's likely already the reason. Since you are building with tests, Opencast will try running some front-end tests which require Firefox or Chrome for their execution. Try installing one of the browsers, or skip the tests with `mvn clean install -DskipTests …`

**Comment by mtneug** [comment]
Closing for now.
