### ISSUE TITLE
Can not specify access policy template for videos recorded with Opencast Studio

### ISSUE THREAD

**Issue by fishfree** [opencast/opencast#4050]
We cannot apply access policy template the way Adding Event in the admin UI as below:
![image](https://user-images.githubusercontent.com/1741341/182744168-0f1eb27f-b1b2-462a-bbf8-6a43015d2caf.png)

**Comment by gregorydlogan** [comment]
Which version of Opencast are you using here?

**Comment by lkiesow** [comment]
Studio has no such user interface, and that's a deliberate choice to keep things simple.
What you can do is to configure the default ACL used in Studio or even pass that to studio via your integration.
For details, take a look at https://github.com/elan-ev/opencast-studio/blob/master/CONFIGURATION.md

**Comment by fishfree** [comment]
@lkiesow Thank you for your tip!
