### ISSUE TITLE
Can't delete scheduled events

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#4084]
**Describe the bug**
In Opencast 12, if you schedule an event, then try to delete, the event it will be deleted, but it will stay in the search service. If you try to delete again, the admin ui it will show the message `The event(s) could not be deleted, because you don't have the permission to do so.` even if you are the admin.

This problem was verified on stable.opencast.org

**To Reproduce**
1. Schedule a new event*
2. Delete it

The event will be `Finished` instead of being deleted

\* You need first a capture agent registered in opencast to schedule first. The easiest way to do it is registering a dummy capture agent through the API.
    1. Go to the API panel
    2. In the `/capture-admin` endpoint register a dummy with `POST /agents/{name}/configuration` add a name and configuration
        You can copy/paste this JSON to register the dummy:
        ```json
        {
        "key": "capture.device.names",
        "value": "presentation,presenter"
        }
        ```

**Workaround**

Reindexing removes the entry from Elasticsearch

**Environment Information**
 - OS: [Mac OS
 - Browser [Chrome]
 - Opencast version with minor release [12.x]

**Comment by mliradelc** [comment]
Adding more information:

Specifically, when through the Admin UI the endpoint `DELETE /admin-ng/event/{event-id}` this gives `Error 401 (Unauthorizided)` and changes the state to `Finished`

**Comment by mtneug** [comment]
Is this also happening for events that were recorded and then deleted?

**Comment by mliradelc** [comment]
Hi Mathias, only happens with scheduled events.

I've updated the first post on how to easily create a dummy CA to try it.

**Comment by mliradelc** [comment]
I've made more testing and debbuging, and the error triggers in `WorkflowServiceImpl.java:1137`
```java
  protected boolean assertMediaPackagePermission(String mediaPackageId, String action) {
    Opt<MediaPackage> assetMediaPackage = assetManager.getMediaPackage(mediaPackageId);
    if (assetMediaPackage.isSome()) {
      var currentUser = securityService.getUser();
      var mediaPackage = assetMediaPackage.get();
      return currentUser.hasRole(GLOBAL_ADMIN_ROLE)
          || currentUser.hasRole(securityService.getOrganization().getAdminRole())
          || authorizationService.hasPermission(mediaPackage, action);
    }
    return false;
  }
```

Specifically, the `assetMediaPackage` gets empty, thus can't enter to the logic. If I force entering to the If bracket, I get error getting the media package, because there is no one.

**Comment by lkiesow** [comment]
> the event it will be deleted, but it will stay in the search service.

Are you sure, it stays in the search service (the Solr-based service behind player, media module, …)? If it's only scheduled, it shouldn't be in there in the first place. Or do you mean Elasticsearch?

**Comment by mliradelc** [comment]
I mean Elasticsearch.

**Comment by mliradelc** [comment]
Ok, this is being more interesting I enabled the debug mode for the Asset Manager, the index service and the Workflow service, here are the logs from a deletion the first time trying to delete a schedule event and clicking the second time.


 The first time, the Asset manager calls the event handlers and announces that the event was deleted from the index service. The second time only there are queries to the DB.

```
2022-08-23T15:34:45,859 | DEBUG | (Database:104) -
---
DELETE [delete episode] [main]
delete from Snapshot snapshotDto
where snapshotDto.owner = ?1 and (snapshotDto.organizationId = ?2 and snapshotDto.mediaPackageId = ?3)
---
2022-08-23T15:34:45,873 | DEBUG | (AbstractADeleteQuery:103) - Pure query ms 15
2022-08-23T15:34:45,891 | INFO  | (AssetManagerImpl:870) - Firing event handlers for event b1c42a68-c9b8-42b8-a6de-335a56a35e8c, snapshot 0
2022-08-23T15:34:45,907 | INFO  | (AssetManagerImpl:870) - Firing event handlers for event b1c42a68-c9b8-42b8-a6de-335a56a35e8c, snapshot 1
2022-08-23T15:34:45,928 | INFO  | (AssetManagerImpl:870) - Firing event handlers for event b1c42a68-c9b8-42b8-a6de-335a56a35e8c, snapshot 2
2022-08-23T15:34:45,928 | INFO  | (AssetManagerImpl:876) - Firing event handlers for event b1c42a68-c9b8-42b8-a6de-335a56a35e8c
2022-08-23T15:34:45,971 | DEBUG | (AssetManagerImpl:544) - Received AssetManager delete episode message b1c42a68-c9b8-42b8-a6de-335a56a35e8c
2022-08-23T15:34:46,078 | DEBUG | (AssetManagerImpl:558) - Event b1c42a68-c9b8-42b8-a6de-335a56a35e8c removed from the Elasticsearch index
2022-08-23T15:34:46,078 | DEBUG | (AbstractADeleteQuery:121) - Complete query ms 220
2022-08-23T15:34:46,233 | DEBUG | (Database:100) -
---
QUERY
select distinct snapshotDto
from Snapshot snapshotDto
where snapshotDto.mediaPackageId = ?1 and snapshotDto.version = (select max(s.version)
from Snapshot s
where s.mediaPackageId = snapshotDto.mediaPackageId)
---
2022-08-23T15:34:46,235 | DEBUG | (AbstractASelectQuery:203) - Pure query ms 2
2022-08-23T15:34:46,235 | DEBUG | (AbstractASelectQuery:269) - Complete query ms 2
2022-08-23T15:34:46,236 | DEBUG | (Database:100) -
---
QUERY
select distinct snapshotDto
from Snapshot snapshotDto
where snapshotDto.organizationId = ?1 and snapshotDto.mediaPackageId = ?2
---
2022-08-23T15:34:46,237 | DEBUG | (AbstractASelectQuery:203) - Pure query ms 1
2022-08-23T15:34:46,237 | DEBUG | (AbstractASelectQuery:269) - Complete query ms 1
```

Second time with the same event trying to delete:
```
2022-08-23T15:38:49,301 | DEBUG | (Database:104) -
---
DELETE [delete episode] [main]
delete from Snapshot snapshotDto
where snapshotDto.owner = ?1 and (snapshotDto.organizationId = ?2 and snapshotDto.mediaPackageId = ?3)
---
2022-08-23T15:38:49,308 | DEBUG | (AbstractADeleteQuery:103) - Pure query ms 8
2022-08-23T15:38:49,308 | DEBUG | (AbstractADeleteQuery:121) - Complete query ms 8
2022-08-23T15:38:49,476 | DEBUG | (Database:100) -
---
QUERY
select distinct snapshotDto
from Snapshot snapshotDto
where snapshotDto.mediaPackageId = ?1 and snapshotDto.version = (select max(s.version)
from Snapshot s
where s.mediaPackageId = snapshotDto.mediaPackageId)
---
2022-08-23T15:38:49,477 | DEBUG | (AbstractASelectQuery:203) - Pure query ms 1
2022-08-23T15:38:49,477 | DEBUG | (AbstractASelectQuery:269) - Complete query ms 1
2022-08-23T15:38:49,478 | DEBUG | (Database:100) -
---
QUERY
select distinct snapshotDto
from Snapshot snapshotDto
where snapshotDto.organizationId = ?1 and snapshotDto.mediaPackageId = ?2
---
2022-08-23T15:38:49,479 | DEBUG | (AbstractASelectQuery:203) - Pure query ms 1
2022-08-23T15:38:49,479 | DEBUG | (AbstractASelectQuery:269) - Complete query ms 1
```

**Comment by mliradelc** [comment]
Found the Commit where the bug started, https://github.com/opencast/opencast/commit/4cf50103f550ebfc225 . Is a very big commit

**Comment by mliradelc** [comment]
@Arnei can you look into this issue? In the DB, if you change the owner in the from org.opencastproject.scheduler to the normal default, you can delete it.

**Comment by wsmirnow** [comment]
@mliradelc can you review PR #4137 please?

**Comment by mliradelc** [comment]
Natürlich ;)

**Comment by KatrinIhler** [comment]
Okay, my understanding of this bug and how it came to be:

The deletion order has been broken for quite a while now (as Waldemar noticed correctly, the scheduler service deletion needs to happen after the workflow service since that also triggers a deletion of the media package from the asset manager, and apparently it's done so for quite a while now). 

However, it still worked until Arne introduced the new permission check for all workflow instances of a media package, which expects the media package to be there. The old permission check for a single workflow instance, which is still invoked a number of times, falls back to the media package contained in the workflow itself it the asset manager can't find it, so it doesn't have the same problem.

With Waldemar's pull request, the deletion should now work correctly. Additionally, I introduced a change which will allow global admins to delete the workflow instances even if the asset manager no longer has the media package. This should help with the cleanup of events broken by this bug. (Unfortunately I couldn't get this to work for org admins, since we can't ensure that the user organization and the media package organization is the same.)

Hope that makes things clearer. :)

**Comment by mliradelc** [comment]
Thanks @KatrinIhler and @wsmirnow for their Patches, they solved the issue. 

Now checking the DB to see if all is deleted, I made a test, where a scheduled event was deleted, and later I searched on the entire DB if there were some entries using the event-id.

I've found that there is remaining a lot of redundant information, and the media package XML still exists! I don't know if this comes from design, or it's another bug. Here is a table with the DB tables that still have entries of the event ID

| DB-table                   | coincidences | description                                                                                                                                           |
|-------------------------|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| oc_assets_properties    | 14           | ACLs from the Event, each coincidence is a ACL for a user                                                                                                                                        |
| oc_assets_version_claim | 1            | Only contains the id  |
| oc_job                  | 2            | Historic log of jobs run in the cluster, one entry it was distribution (Because it was a live event scheduled), and the another one is the retraction job |
| oc_job_argument         | 4            | XMLs from the above table      |
| oc_search               | 1            | shows that the event was deleted (With the column deletion date) and has a copy of the ACLs and Mediapackage ACLs.   |


One of the things that is interesting that `oc_assets_properties` saves the same information (regarding ACLs) as `oc_search`. What is the meaning of `oc_assets_version_claim`?

**Comment by mliradelc** [comment]
I will create a new issue for the last comment, since this bug it is solved.
