### ISSUE TITLE
Creation of new series results in DB errors in OC 12.2

### ISSUE THREAD

**Issue by DZenker** [opencast/opencast#4136]
Creation of a new series in 12.2 results in DB-related errors in admin log. Problem occurs since 10.x -> 12.2 upgrade.
Error messages are similar described in #3914, but we don't use any "extended metadata", just the default ones.

**To Reproduce**
1. Go to series tab in Admin UI
2. Click on 'Add series'
3. Fill out all required metadata 
4. Continue until last step and click "Create"
5. The new series has been created correctly.
6. Error messages are generated (log attached) which are related to the newly created series

_2022-08-31T12:25:26,891 | ERROR | (ConfigurableSeriesDCCatalogUIAdapter:104) - Error while loading DublinCore catalog of series 'SERIES_ID_OF_NEWLY_CREATED_SERIES': {}
..._

**Environment Information**
 - OS: CentOS 7, MariaDB 10.3
 - Opencast 12.2 in multi-tenancy setting 

[opencast_admin.log](https://github.com/opencast/opencast/files/9460831/opencast_admin.log)

**Comment by gregorydlogan** [comment]
I can't reproduce this on stable.opencast.org.  Can you try this with the latest 12.x and see if it happens for you?  I'm wondering if this has been fixed since 12.2.

**Comment by DZenker** [comment]
Hi Greg,

I am using the latest 12.2 version (sorry for wrong version info in "Environment Information" above). 
This also happens in our test cluster which is a multi-tenancy system, too. Maybe only multi-tenant systems are affected?

**Comment by mliradelc** [comment]
Hi Dietmar, can you check if the DB upgrade script from 11 to 12 was the latest one you tried? Because the PR #4101 fixes a mistake, where the upgrade was never done. The latest script in r/12.x branch works.

**Comment by DZenker** [comment]
Hi,

as I have used the 8.0.29 version of the mysql-connector-python module, I did not run into any issues and the update has been finished successfully. Furthermore,  this script updates workflow-related tables in the DB, which should be independent with the problem described above and in #3914. I did some further tests: the errors messages also show up if I retrieve the metadata of formerly generated series in Admin UI.

Though I am no developer, but if I understand the error messages correctly, there seems to be a problem with transferring the metadata stored in DB into corresponding Java objects/vars?

**Comment by gregorydlogan** [comment]
Yes, it's definitely having issues converting what it's getting from the database into something in Java (and vice versa).  Can you give us the table structure, and the column values for an affected series?

**Comment by DZenker** [comment]
I've investigated this issue further: I've set up a new OC 12.2 installation with fresh database, thus the DB structure has been generated from scratch by Opencast itself. Indeed, the table schemes and fields of the series-related tables differ between the newly generated DB and the existing DB of our production and test system which have been updated several times during OC upgrades in the past years (parts of both SQL dump files are attached).
[oc12_production_scheme.txt](https://github.com/opencast/opencast/files/9476845/oc12_production_scheme.txt)
[oc12_new_scheme.txt](https://github.com/opencast/opencast/files/9476849/oc12_new_scheme.txt)

My tests have additionally shown that ALL series are affected by this issue which are listed in the oc_series_elements table (i.e. retrieving metadata in Admin UI will generate these errors). Series that have been created before 2018 which are only listed in oc_series but missing in the oc_series_elements table are not affected.
Thus, maybe the problem is caused by the deviating BLOB field in this table?

Honestly, I do not understand why there are two different tables which contain almost similar data. What's the reason for this?

**Comment by DZenker** [comment]
As suspected, the wrong data type of the field "data" in the table _oc_series_elements_ was the cause of the error. I could fix this by altering this:
_ALTER TABLE oc_series_elements MODIFY COLUMN data longblob ;_

Issue could be closed now, but maybe other adopters have the same problem.

**Comment by mtneug** [comment]
This probably depends on the database. PostgreSQL doesn't have this data type. The DDL schema in OC 8 just used `BLOB`. JPA probably always uses `LONGBLOB` for binary data and MySQL. In #4076 I didn't look into the table fields, but maybe this should be done as well.

**Comment by DZenker** [comment]
IMO it is an increasing problem that the DB schema and structure of an freshly installed Opencast differs from the DBs of longer existing installations where the DBs will be updated by scripts during major release upgrades which not cover all changes. 
In addition, there are some inconsistencies: for example, the OC 11 mysql update script introduced two new fields in table oc_series - "deletion_date" and "modification_date" - with data type "timestamp". BUT: in OC 12, the data type of this fields in a _de novo_ created DB is "datetime" instead.

BTW: where can I find further information about the DB and tables schemata which is currently used by Opencast 12?

**Comment by mtneug** [comment]
The schema is created automatically by Opencast when tables are first used. There is no longer a single file containing the schema definition. Instead, each entity corresponding to a table has annotations describing the schema.

**Comment by gregorydlogan** [comment]
I'm wondering how many adopters are going to run into this as they upgrade to 12.x. Perhaps we need to amend the upgrade script?

**Comment by DZenker** [comment]
Should we run a query on this in the Google group?

**Comment by gregorydlogan** [comment]
I think that's probably a good idea, I'll send an email in the morning.

**Comment by mliradelc** [comment]
> I think that's probably a good idea, I'll send an email in the morning.

Here is the Google Groups discussion 

https://groups.google.com/a/opencast.org/g/users/c/U-1fZoq1Hi8
