### ISSUE TITLE
Uploading multiple tracks with same flavor when event is created does not work anymore

### ISSUE THREAD

**Issue by rute-santos** [opencast/opencast#4170]
**Describe the bug**
We upload video assist files that consist of several parts when creating an event. We then concatenate them using our workflow.
This is not working anymore. The configuration _multiple=true_ available in _etc/listproviders/event.upload.asset.options.properties_ has no effect.

**To Reproduce**
1. In etc/listproviders/event.upload.asset.options.properties, add a source track with multiple=true e.g. EVENTS.EVENTS.NEW.SOURCE.UPLOAD.MULTIPLE_PARTS={"id": "track_parts","type":"track", "flavorType": "presenter","flavorSubType": "source", **"multiple":true**, "displayOrder":11, "accept": ".avi,.flv,.m4v,.mkv,.mov,.mp4,.mpeg,.mpg,.ogv,.webm,.wmv,.flac,.m4a,.mp3,.ogg,.wav,.wma"}
2. Select multiple files when uploading presenter
3. Only the last track is added to the media package.

**Environment Information**
 - Opencast 11

**Comment by mtneug** [comment]
@rute-santos this is fixed right?

**Comment by rute-santos** [comment]
Yes, the fix has already been merged.
