### ISSUE TITLE
S3 asset storage does not release http connections

### ISSUE THREAD

**Issue by rute-santos** [opencast/opencast#4184]
**Describe the bug**

When downloading files archived to S3, the S3 asset storage does not release http connections. After downloading several files, the following error appears in the Opencast log:
```
"Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request:
 Timeout waiting for connection from pool"
```

The same code works fine in 5.x using an older version of the AWS Java sdk but, in 11.x, if the S3 object is not closed, it does not release the http connection.

**To Reproduce**

1. Set maximum number of connections to a very low number in /etc/org.opencastproject.assetmanager.aws.s3.AwsS3AssetStore.cfg: org.opencastproject.assetmanager.aws.s3.max.connections=N
2. Use the /assets REST endpoint to download N+1 files that were archived to S3 e.g. /assets/assets/{mediaPackageID}/{mediaPackageElementID}/{version}/{filename}
3. The N+1 download will hang and then time out, and you will see the above error in the log.

To debug, you can enable AWS metrics and log them:

1. Add -Dcom.amazonaws.sdk.enableDefaultMetrics as extra java opts.
2. Add logging:
- log4j2.logger.awssdk.name = com.amazonaws
- log4j2.logger.awssdk.level = DEBUG (It's recommended to leave it at WARN later)

And look at the Opencast log, you will see something like:
`(AWSRequestMetricsFullSupport:204) - ServiceName=[Amazon S3], StatusCode=[200], ServiceEndpoint=[https://<ARCHIVE_BUCKET>.s3.amazonaws.com], RequestType=[GetObjectRequest], AWSRequestID=[DAXTCH4KKE9X3TDA], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=0, RequestCount=1, HttpClientPoolLeasedCount=0, ResponseProcessingTime=[4.206], ClientExecuteTime=[322.684], HttpClientSendRequestTime=[5.119], HttpRequestTime=[222.462], ApiCallLatency=[248.446], RequestSigningTime=[3.972], CredentialsRequestTime=[55.228, 0.028], HttpClientReceiveResponseTime=[107.072], `

where _HttpClientPoolLeasedCount_ only increases and never goes down.

**Environment Information**

 - Opencast 11

**Comment by gregorydlogan** [comment]
How to tell if your aws bits aren't getting enough testing...

Are you seeing this with the default config? Or only if you set a limit manually?

**Comment by rute-santos** [comment]
Hi Greg,
Both. The default config is 50. We have a process where we "republish" old courses as new courses so downloading files from S3 is a common occurrence for us. We noticed that we could "repub" a few lectures and then no more. Decreasing the setting was only a way to debug the issue. This worked fine with our 5.x code base so I believe it was a change in the sdk. The aws documentation is clear in that you need to close the S3 object to release resources, but it's possible that it behaved differently in previous versions.

**Comment by mtneug** [comment]
@rute-santos is this fixed?

**Comment by rute-santos** [comment]
Yes, the fix has already been merged.
