### ISSUE TITLE
Increase number of terms returned by ES getTermsForField

### ISSUE THREAD

**Issue by rute-santos** [opencast/opencast#4199]
**Describe the bug**
When filtering events by some fields where getTermsForField() is used e.g. publisher, contributor, only the top 10 terms with the most documents are returned (this is the ES default).

**To Reproduce**
1. Go to stable.opencast.org
2. Add more than 10 events, all with distinct 'Location'
3. Filter events by 'Location'
4. The drop down shows only 10 values

**Environment Information**
 - Opencast 11.x, 12.x, develop

**Comment by mtneug** [comment]
@rute-santos again fixed?

**Comment by rute-santos** [comment]
Sorry, I thought those were closed automatically with the merge :)

**Comment by mtneug** [comment]
I guess the `Fixes #...` text needs to be part of the PR description and not a comment? Thanks for confirming!
