### ISSUE TITLE
Paella player 7 compatibility issue with safari

### ISSUE THREAD

**Issue by yokoul** [opencast/opencast#4241]
This issue is only visible with multiple audio channel. 

![image](https://user-images.githubusercontent.com/630213/192122063-2677b8b4-4f98-48b3-a2d4-357f639cbabf.jpeg)

**Comment by mliradelc** [comment]
Hi, have you tried with Paella player 7?

Change the route from `../paella/..` to `../paella7/..` if that works.

**Comment by yokoul** [comment]
Hi Maximiliano, this error come only with paella7, paella 6 don't display any error. At this time we fallback to paella6 if safari is detected.

**Comment by yokoul** [comment]
On safari for macOS, with paella7 an "Unhandled Promise Rejection: not implemented on this platform" make the player never loading. 
The screen capture come from safari on iOS.

**Comment by mtneug** [comment]
@yokoul, thanks for reporting. This should be reported to the [upstream Paella repo](https://github.com/polimediaupv/paella-core). Not sure if Opencast can fix this. I will leave this open for now.

**Comment by miesgre** [comment]
> @yokoul, thanks for reporting. This should be reported to the [upstream Paella repo](https://github.com/polimediaupv/paella-core). Not sure if Opencast can fix this. I will leave this open for now.

I reported it to Paella repo. See https://github.com/polimediaupv/paella-core/issues/133

**Comment by miesgre** [comment]
https://github.com/polimediaupv/paella-core/issues/133 was solved. @yokoul Is this issue fixed? Can we close it?

**Comment by yokoul** [comment]
Hi Miguel, We tested few days ago the latest 13.x (.7 I think, not in front of it)  without success, but pushing the latest player configuration from Github into it solved the issue. Champagne ! :-) Thank you for this resolution.
