### ISSUE TITLE
Adopter Registration: Preview Data before submission

### ISSUE THREAD

**Issue by AndreasUrra** [opencast/opencast#4254]
**Description of Feature Request / Enhancement**

_Location: Admin UI > "?" > Adopter Registration_

In the registration dialogue it would be great to be able to get precise information about what will be sent. In addition to the more general descritpion within the "privacy policy and terms of use" it would be valuable to see e.g.

a) a JSON "sceleton" file that shows the data fields
or better yet:
b) the exact statistical data that would be sent at the time of registration

This could be offered as downloadable JSON file in the dialogue.

**Comment by Rillke** [comment]
Making the submission client-side (i.e. load the data from Opencast into the browser and then send a cross-site XHR to the registration server, which could be also a plain form submission) would also allow you to bypass firewall restrictions between Opencast servers and the world.

**Comment by gregorydlogan** [comment]
The major issue with that is a lack of automation, and part of the point of this is to keep the adopter registration data up to date.

See #4321

**Comment by gregorydlogan** [comment]
This got done a while back.
