### ISSUE TITLE
Make sure Opencast works with Node.js 18

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4268]
Right now, Opencast (`12.x`, `develop`) only works with the current Node.js LTS (16.x). We know that the current stable version (18.x) causes problems. We need to address those problems eventually.

To update the version of Node in Opencast, either update the main `pom.xml` file, which will make Opencast download that specific version:

https://github.com/opencast/opencast/blob/c3a76e37a7d42d62eb639b76fb74550217bd49a0/pom.xml#L46

…or build Opencast using your local `node` and `npm` with the `frontend-no-prebuilt` profile:

```
❯ mvn clean install -Pdev,frontend-no-prebuilt -DtrimStackTrace=false
```

**Comment by bhumirao** [comment]
https://github.com/bhumirao/opencast/pull/1

**Comment by lkiesow** [comment]
You should run into errors that need fixing once you try building Opencast with Node 18.

**Comment by lkiesow** [comment]
The End-of-Life Date for Node.js 16 [has been moved up to September 11th, 2023](https://nodejs.org/ar/blog/announcements/nodejs16-eol/). We need to look at this soon.

**Comment by Dhananjay-12** [comment]
Hi @lkiesow  is this issue still open? I would like to work on this

**Comment by gregorydlogan** [comment]
@Dhananjay-12 yep sure is. Go ahead and get started!

**Comment by lkiesow** [comment]
That would be awesome. If you want to try a build with a new Node version, you have two options:

1. Install the node version you want to use on your system, try try building Opencast with the system Node.js using:
    ```
    ❯ mvn clean install -Pdev,frontend-no-prebuilt
    ```
3. Let Opencast handle the Node version and update the version [in the main pom.xml file](https://github.com/opencast/opencast/blob/develop/pom.xml#L46). Then build Opencast as usual:
    ```
    ❯ mvn clean install -Pdev
    ```

**Comment by lkiesow** [comment]
That would be awesome. If you want to try a build with a new Node version, you have two options:

1. Install the node version you want to use on your system, try try building Opencast with the system Node.js using:
    ```
    ❯ mvn clean install -Pdev,frontend-no-prebuilt
    ```
3. Let Opencast handle the Node version and update the version [in the main pom.xml file](https://github.com/opencast/opencast/blob/develop/pom.xml#L46). Then build Opencast as usual:
    ```
    ❯ mvn clean install -Pdev
    ```
 
I'm not sure how many problems you will still see. We have already updated a significant number of dependencies since I've created this issue. But I fear that some problems still remain.

**Comment by Dhananjay-12** [comment]
### 1 -- Hii , I'm recieving this issue while running the command 2
<img width="707" alt="mvn install" src="https://user-images.githubusercontent.com/86868676/218490664-6b0df603-0dd0-4cea-a00f-a5f7ec48eb85.png">


### 2-- When I run the first command what parameters I should pass?
<img width="503" alt="mvn i 1" src="https://user-images.githubusercontent.com/86868676/218492669-a98109bb-e107-4f43-bb57-ebf351581009.png">

 
### 3-- and for `npm i` I could not locate the package.json

**Comment by lkiesow** [comment]
Only some modules use Node. Maven calls `npm` during the build process. 
You can also switch to the module folder and then use `npm` directly.

For your Maven issues… well… you have to install Maven.
Also, it seems like you are trying to do that from a Windows shell. I don't think that will work.
I suggest building Opencast on Linux macOS or to use the WSL on Windows.

**Comment by Dhananjay-12** [comment]
Hi @lkiesow  , I am in Kali Linux OS now but I am receiving these errors

![Screenshot_2023-02-18_19-24-54](https://user-images.githubusercontent.com/86868676/219869665-9b8220db-5bd8-45b5-8de4-4f3179fafe7d.png)

**Comment by gregorydlogan** [comment]
Yep, it's telling you to install Maven.

You will need a bunch of things. Try `$ apt install -y git openjdk-11-jdk maven gcc g++ build-essential cmake curl sox hunspell synfig ffmpeg`

Docs for installing a dev environment at https://docs.opencast.org/develop/developer/#installation/source-linux/#install-packages-via-apt

**Comment by Dhananjay-12** [comment]
## I followed the steps from the docs and installed node here with 18 version. 
![edit1](https://user-images.githubusercontent.com/86868676/219875469-62af0731-d010-44df-9fc0-30216282e2a0.png)

![edit 2](https://user-images.githubusercontent.com/86868676/219875480-2709142b-dea4-4268-b855-a1d6057c5611.png)
## Am I going in correct direction ??

**Comment by gregorydlogan** [comment]
Unclear.  You want to run `mvn clean install` inside of the `admin-ui-frontend` module to test if the build succeeds.  This will, if necessary, install a self-contained node install, although IIRC a system node can override that.  The `frontend-maven-plugin` plugin in the `admin-ui-frontend` module is what's doing that, and I believe it's running `npm ci` once it has things installed.  If you can get `npm ci` working with Node 18 that would be an awesome first step - then we modify the main pom's `node.version` field to make sure `mvn` is grabbing the right version of node.

**Comment by Dhananjay-12** [comment]
Hii @gregorydlogan  , it installed with node 16  😐, I found the node.version field. But i have no idea where to change it to 18 . Can you help me please. 
![Screenshot_2023-02-27_23_39_03](https://user-images.githubusercontent.com/86868676/221650575-9fda5ce8-a9c9-41a3-a008-e87e042688d9.png)

**Comment by gregorydlogan** [comment]
That looks like you've got it building with 16, awesome. So to test 18 you would change the value in the main pom file, specifically [here](https://github.com/opencast/opencast/blob/develop/pom.xml#L46), then rebuild the module. Once you have that building, you can either try and build the whole system, or let me know and I can get you a pre-built version and some instructions on how to test.

**Comment by Dhananjay-12** [comment]
HI @gregorydlogan , Updated the `node.version` field and then in `admin-ui-frontend` directory .I rebuild it using
   `mvn clean install -Pdev,frontend-no-prebuilt -DtrimStackTrace=false` . 😄 I think only the testing part is left.  😄





![Screenshot_2023-02-28_19_06_24](https://user-images.githubusercontent.com/86868676/221870358-da55a169-d293-4574-89b2-669340a9696c.png)

**Comment by gregorydlogan** [comment]
Ok, great. So the next step would probably be building Opencast as a whole. Feel like setting up the full dev env? :)

Alternatively file a pull request and I can see about packing a testing build with your changes so it's easier.

**Comment by Dhananjay-12** [comment]
HI @gregorydlogan , I made the PR 😄
