### ISSUE TITLE
Wrong placeholder in editor error message for non-existing event

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4318]
When you try opening the new editor win an identifier from a non-existing event, you get an wrror message like this:
```
Status 404: Event '{123}' not Found
```
The inner `{}` shouldn't be there.
The error message is generated by Opencast's backend.

![Screenshot from 2022-10-13 17-08-28](https://user-images.githubusercontent.com/1008395/195636255-186a1b17-b36b-4715-ac51-1a560773fa88.png)

**Comment by Adityageek** [comment]
Hello @lkiesow Can you please assign this issue to me. I would like to work on that.

**Comment by lkiesow** [comment]
Go ahead. Thanks for taking this on. If you can, please base your work on the `r/12.x` branch. This can certainly go into the stable branch directly.

**Comment by lkiesow** [comment]
The relevant code for this should be somewhere in here:
- https://github.com/opencast/opencast/tree/b49d0b146791224283a8d16c4976610f25352846/modules/editor-service/src/main/java/org/opencastproject/editor

**Comment by Adityageek** [comment]
Okay @lkiesow Thanks for the above info!

**Comment by lkiesow** [comment]
Hi @Adityageek, since Hacktoberfest is over and my guess is that you picked this up as part of it, do you still plan to work on this now that the event is over?
