### ISSUE TITLE
Fix hostname in adopter registration information

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4323]
This is the statistical information being sent from the adopter registration:

![Screenshot from 2022-10-15 00-20-44](https://user-images.githubusercontent.com/1008395/195952766-23043e14-1936-442a-9c38-5dfe296d2372.png)

The `hostname` being sent is actually the `nodename` configuration from the `custom.properties`:
https://github.com/opencast/opencast/blob/5437fcdb377759a1e9ad061172d123116573e27b/etc/custom.properties#L26-L29

This should rarely have any useful information and will typically just be the default value.

Sending the actual `hostname` from the `server.url` configuration should be far more useful:
https://github.com/opencast/opencast/blob/5437fcdb377759a1e9ad061172d123116573e27b/etc/custom.properties#L19

**Comment by kirsteend** [comment]
@lkiesow I'd like to work on this if you are still looking for contributors

**Comment by lkiesow** [comment]
Sure, please do. The relevant code should be around this:

https://github.com/opencast/opencast/blob/5437fcdb377759a1e9ad061172d123116573e27b/modules/adopter-registration-impl/src/main/java/org/opencastproject/adopter/statistic/dto/Host.java#L56
