### ISSUE TITLE
Publish Captions by Default

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4326]
Similar to the patch applied to the testing workflow (#4307), we should automatically publish captions in the default production workflows. But here we need to update a few more places.

In general, check all `publish-engage` and `snapshot` operations.
Here is what I think needs adjustments (I deleted the lines I think we can ignore):

```
❯ grep -rn publish-engage etc/workflows 
etc/workflows/partial-publish.xml:278:      id="publish-engage"
```

```
❯ grep -rn snapshot etc/workflows     
etc/workflows/schedule-and-upload.xml:65:      id="snapshot"
etc/workflows/schedule-and-upload.xml:85:      id="snapshot"
etc/workflows/schedule-and-upload.xml:131:      id="snapshot"
etc/workflows/publish.xml:58:      id="snapshot"
etc/workflows/partial-error.xml:11:      id="snapshot"
```

**Comment by KAIMonmoy** [comment]
Hey, @lkiesow !
I have made a pull request (https://github.com/opencast/opencast/pull/4415) that should close this issue. Can you please review that PR?
