### ISSUE TITLE
Directly show publication if there is just one

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4331]
The admin interface has a pop-up for listing the publications. That's very flexible as you can list as many as you want, but most installations will only have a single publication and in that case, this is a nuisance. It would be better if we could show the publication link directly.

To satisfy both needs, we should:

- List the publication directly, if there is only one
- Provide a dropdown showing something like `▼ Publications` if there are more than one
  - This is basically what we have now, just with the `Yes` replaced with something sensible

This is how the publication drop-down currently looks like:

![Screenshot from 2022-10-16 13-45-56](https://user-images.githubusercontent.com/1008395/196034712-f429f210-f8ae-4dac-a583-36a2fd9272bc.png)

This is what we should do:

![Screenshot from 2022-10-16 13-55-37](https://user-images.githubusercontent.com/1008395/196034730-d4c8c63c-89d1-4a44-960e-5fd506568eee.png)

The relevant code lives in the [admin interface frontend](https://github.com/opencast/opencast/tree/develop/modules/admin-ui-frontend).
For development, you can run the interface with mocked data via `npm`:

```
❯ cd modules/admin-ui-frontend
❯ npm ci
❯ npm run build
```

**Comment by CalArcher** [comment]
I would like to work on this, can you assign it to me?

**Comment by lkiesow** [comment]
Sure, done. Thanks for taking this on.

**Comment by CalArcher** [comment]
Sorry @lkiesow, it's a bit too much for me to take on right now.

**Comment by lkiesow** [comment]
Hi @CalArcher, no problem. Thanks for trying and thanks for letting us know that you won't continue to work on this.

**Comment by mliradelc** [comment]
Well, we have this here in cologne some time ago, I can make a PR with our code to do that. But our solution is to show the icons only (No need to put text)

**Comment by mtneug** [comment]
I like the icon-only solution more than the dropdown.

Also, @mliradelc, if you are working on this, there is currently a "bug" where publications are always rendered as links. However, you can have publications that do not have a publication URL. It is no real issue, as the link will direct you to the current page, but maybe the link can be removed altogether?

**Comment by mliradelc** [comment]
@mtneug  our solution looks like this:
![image](https://user-images.githubusercontent.com/8040628/196624416-04931184-2022-4fa3-9085-5c5c814a8758.png)

The icons from left to right are: Paella Player, External Player, Download Page (A self generated external page that allows to download all the assets), and the annotation tool. We have also another icon for the livestream (Not shown).

@CalArcher  Fell free to make the PR, as the solution I stated is different from the one is requesting lars.


About the "Bug" I've never seen that case, how I can trigger it?

**Comment by mtneug** [comment]
publish-configure without setting a URL ;)

**Comment by Noothan-am** [comment]
hi @lkiesow is this issue still open ?
i want to contibute to this issue

**Comment by FarzamMohammadi** [comment]
Hey @lkiesow @mliradelc, is this up for grabs? I'd love to give this a go.

To reiterate: We're displaying the icon in the 'Published' column without the text, correct? 
Also, If there is any existing logic for displaying the original icon and text, should I reimplement it when I attempt the icon-only solution?

**Comment by mliradelc** [comment]
Hi @FarzamMohammadi

To be honest, I don't know if we had them in a public repo, but I will ask about. 

If there is no repo, I will post the code here, and you can easily integrate to your opencast.

**Comment by lkiesow** [comment]
Will be fixed by https://github.com/opencast/opencast-admin-interface/pull/846
