### ISSUE TITLE
Paella 7 does not authenticate the user when it tries to watch a protected video.

### ISSUE THREAD

**Issue by miesgre** [opencast/opencast#4338]
**Describe the bug**
When you play a protected video while not logged in, paella 7 returns an error instead of trying to authenticate the user.
Paella 7 should authenticate the user and try to view the video again.

**To Reproduce**
1. Upload a restricted video
2. Try to play it while not logged in.

**Comment by mliradelc** [comment]
my colleague @reiferschris has another  issue related, this is the situation:

>Video is released for ROLE_ANONYMOUS and I don't need to log in. Currently, however, even if the UI is released for Anonymous, the UI files are not delivered.

The Spring file is as default in Opencast

**Comment by miesgre** [comment]
> my colleague @reiferschris has another issue related, this is the situation:
> 
> > Video is released for ROLE_ANONYMOUS and I don't need to log in. Currently, however, even if the UI is released for Anonymous, the UI files are not delivered.
> 
> The Spring file is as default in Opencast

I think it is a different issue.
security files should have these lines https://github.com/opencast/opencast/blob/develop/etc/security/mh_default_org.xml#L278-L280

I can test it If you can provide an example.

**Comment by miesgre** [comment]
Fixed in PR https://github.com/opencast/opencast/pull/4339.
