### ISSUE TITLE
How subtitles should work in Opencast

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4407]
As a more interactive version, I've also added this to a HackMD where you can add comments on certain lines. Use whatever you prefer to add comments:

- [@lkiesow/oc-subtitles](https://hackmd.io/@lkiesow/oc-subtitles)

---

We have a lot of implicit and often slightly different assumptions of how we handle subtitles. In here, I'll try to document a best-practice approach. After some discussion, we can maybe add this to the Opencast documentation and make it the official approach.

I'll try to suggest common ways of storing and identifying the subtitles from upload, through processing and finally for showing them in the player.

## TL;DR

Let's make subtitles a first-class citizen in Opencast, storing them as tracks alongside audio and video streams and letting workflows handle them by default.

Let us use flavors of the form `captions/<processing>`, e.g. `captions/source` and `captions/delivery`. This makes it easy to identify subtitles and also easy to publish everything ready for publication.

Let us specify tags holding additional information of the form `lang:<lang>`, `generator:<type>[:<id>]` and `type:<caption-type>` to each subtitle track.

## History

While there are many components in the history of Opencast dealing with subtitles (Matterhorn admin interface, Engage player, …), the most relevant ones are Opencast's HTML5 players: Theodul and Paella.

> Since it is still beta, I leave Paella Player 7 out of the historical consideration.

### Theodul

Theodul supports WebVTT files and considers both tracks and attachments when loading subtitles. It only supports a single subtitle stream. If both exist, it prefers tracks over attachments. The only selection criteria is, that the media package element must have the mime type `text/vtt`.

Examples:

- type `track`, flavor `captions/delivery`, no tags, mime type `text/vtt`
    - will be selected for the player
- type `track`, flavor `captions/vtt`, tag `lang:en`, mime type `text/plain`
    - will __not__ be selected

See `loadAndAppendCaptions(…)` in `engage-theodul-plugin-video-videojs/src/main/resources/static/main.js` for more details.

### Paella

Paella supports dxfp, WebVTT and SubRip files (not entirely sure). It supports loading subtitles from attachments, catalogs and (since ≥ 12.x) tracks. It supports multiple subtitle streams. Subtitles selection happens by selecting all media package elements (only attachments in Opencast ≤ 11) with main flavor `caption`.

The sub-flavor is split at the first `+` character. The first part is used as the format identifier, the second part, if present, as a language identifier. If no language was detected, the Paella player looks for a tag of the form`lang:<language>` to use as language identifier. The language identifier is also the language description.

Examples:

- flavor `captions/vtt+de`, tag `lang:fr` becomes:
    - format: `vtt`
    - language identifier: `de`
    - language description: `de`
- flavor `captions/vtt`, tag `lang:en` becomes:
    - format: `vtt`
    - language identifier: `en`
    - language description: `en`
- flavor `captions/delivery`, no tags, mime type `text/vtt`
    - will cause problems since `delivery` is detected as format

See `getCaptions(…)` in `engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.loader/03_oc_search_converter.js` for more details.

## Components

Going forward, we need to support subtitles not only in players, but in several components to help users working with subtitles:

- Creating subtitles
    - **Upload**
      Components which allow uploading media should also allow uploading subtitles by default. This includes the admin interface, LMS integrations and the video portal.
    - **Autogenerate subtitles**
      Opencast should offer to auto-generate subtitles out of the box, leveraging Vosk, Subtitle2go and/or whisper. It should also provide further integration with SaaS providers like IBM, Google or AmberScript.
- Modifying subtitles
    - **Opencast Editor**
      Opencast's editor should allow users to download, create, upload and modify subtitles easily
    - **Update Publications**
      It should be easy for users to update publications after modifying a subtitle in the editor.
    - **Editor Backend**
      Cutting parts from video streams should also effect subtitle tracks.
- Presenting subtitles
    - **Default Workflows**
      All of Opencast's workflows should treat subtitles as a first-class citizen and handle them by default, including cutting and publication.
    - **Players**
      Players should offer to display published subtitles.

## Subtitle Formats

Now let's talk about how things should work in the future.

The [Web Video Text Tracks Format (WebCTT)](https://www.w3.org/TR/webvtt1/) is a widely adopted W3C standard for subtitles/captions in the World Wide Web. In this context, it has completely replaced all competitor formats by now. We do not need to support any other formats.

> For simplicity, I suggest to support WebVTT only.

If other formats still exist in its archive, Opencast can convert many formats to WebVTT using FFmpeg.

## Media Package: How to store subtitles

In the past, two media package categories have been used to store subtitles: Tracks and attachments.

- __Attachments__ are static files associated with the event represented by the media package. They usually do not have a temporal aspect and are not commonly used for further processing.
- __Tracks__ usually have a temporal aspect and represent the entire, or at least a part of the overall event. They are commonly used for further processing.

Since Opencast allows cutting of events, and with the trend to push this task more and more towards end-users, we cannot control the order of generating subtitles versus cutting the event.

Therefore, it is important that subtitles are treated similar to other tracks, since that allows us to cut the subtitle along video and audio whenever that becomes necessary.

> To allow for this, I suggest to always store subtitles in the **tracks** section of media packages.

  
Using tracks also allows us to easily use tools like FFmpeg to convert subtitles between different formats, in the same way we convert audio and video using the `encode` operation.

## Flavors

With auto-generated and archived subtitles, as well as with editing in user's hands, we need to be able to distinguish uncut and cut subtitles. That is why using `captions/vtt` for everything doesn't really work.

More than that, we may have several different subtitle streams. They can differ because they are generated differently, they can be in different languages, or they can be either closed captions or subtitles.

Containing all information in a two (arguably three) component flavor is hard, and we should consider putting most of these additional information in more flexible places instead.

With video and audio streams, the main flavor describes the kind of video (`presenter`, `presentation`, …) while the sub-flavor expresses the processing state (`source`, `work`, `delivery`). Having unrelated captions would mean that we also have unrelated audio streams in a media package. That is unlikely. We can hopefully assume that just supporting one stream is enough, and we can always stick to `captions` as main flavor, to make the set of captions easily identifiable.

As sub-flavor, we should use the processing state similar to what we use for video and audio streams. This makes it easy for us to distinguish between source material and material which has been processed (e.g. cut).

> I suggest always using `captions` as flavor while using the processing state as sub-flavor, similar to other media package tracks. For example, a caption could be flavored `captions/source` when ingesting and `captions/delivery` when it is ready for publication.

Previously, the language was sometimes attached to the sub-flavor in the form `captions/source+en`. I suggest moving this information to tags instead, since they are more flexible and this makes generic handling of media package tracks harder. For example, it's no longer possible to publish `*/delivery` if captions are flavored `captions/delivery+en`.

## Tags

Tags are very flexible and can hold all sorts of additional information about media package elements. I suggest defining common tags to specify:

- language of the subtitle track
- generator (auto-generated, manually generated)
- type (closed captions, subtitles)

All tags should be optional and components should work without them being present, falling back to generic displays, or not showing information at all.

When processing subtitles, Opencast's components should either keep these tags as is, or adjust them accordingly.

To specify the language of a subtitle track, we can use tags of the form `lang:<language>` where `language` is a 3-letter [ISO 639 language code](https://en.wikipedia.org/wiki/ISO_639-3). Adding multiple tags in case multiple languages are used is possible.

> Just using 3-letter ISO language codes does not allow us to specify regions. For example, we cannot distinguish between British English (`en-GB`) and American English (`en-US`). Do we need that? If so, we could use [RFC 3066 language codes](https://www.ietf.org/rfc/rfc3066.txt) instead.

Specifying how subtitles are generated, in partcular, if they are automatically generated, can help users. Therefore, I suggest adding tags of the form `generator:<id>` and `generator-type:<type>`, where type should be either `manual` or `auto` and the generator `id` may be added to specify the system generating the subtitle.

For example, a manually generated subtitle should be tagged `generator:manual` while an auto-generated subtitle should be tagged `generator:auto` and one generated by Vosk may even be tagged `generator:auto:vosk` to be more specific.

If no `generator` is specified, components should make no claims about how this may be generated.

For accessibility in particular, it is important to know if a subtitle track is actually a subtitle or a closed caption (e.g. including additional information for deaf people). If we have this information, we should include it with a tag of the form `type:<tyle>`, either `type:subtitle` or `type:closed-caption`.

> I suggest including additional information about subtitles with tags of the form `lang:<language-code>`, `generator:<type>[:<id>]` and `type:<captions-type>`.

## Mime Type

Since the format of subtitle tracks should always be WebVTT, the mime type [should always be `text/vtt`](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#webvtt_files).

This also makes selecting all subtitles easier and could also be an alternative to using `captions` as main flavor, although no operations in Opencast let you select tracks by mime type.

## Fallbacks

For internal components, no fallbacks should be necessary, unless adopters want to reprocess already generated and/or published subtitles. We already have the means to [access published media package elements](https://docs.opencast.org/r/12.x/admin/#workflowoperationhandlers/publication-to-workspace-woh/). If we provide a simple operation to move attachments flavored `captions/vtt+lang` to the new track-based format, we should be good to go.

For already published media, it would be great if we could still have a fallback in players, so that old media are still displayed correctly. That is why I suggest players to implement the following fallback mechanism:

- If no subtitle tracks are present, look for attachments with flavor `captions`. This should already give us a list of all old subtitles.
- If the sub-flavor is of the form `…+<lang>`, treat it as if a tag of the form `lang:<lang>` were present.

> Let players fall back to attachments if no subtitle tracks are present.

---

Not that this is an open discussion and a few minor changes will likely result from this.

**Comment by cgruber-uos** [comment]
Many thanks for this write-up Lars / @lkiesow! 

+1 for WebVTT (*.vtt) and 
+1 for tracks 

In case it is not too complex, supporting SubRip (*.srt) as input / uploading format would not be bad because it is a often used format atm. But auto generating subtitles should be the way for the future, not using other (external) tools. 

In case someone is interested why WebVTT (*.vtt) instead of SubRip (*.srt) have a look at: 
https://www.checksub.com/de/untertitel/webvtt-untertiteldatei-alles-was-sie-wissen-mussen-um-sie-zu-benutzen/ (German article)

**Comment by mliradelc** [comment]
+1 Vtt subtitles.
I just [read this document](https://jbilocalization.com/the-difference-between-srt-and-webvtt-in-captioning-subtitling/), and I found that you can add metadata to the subtitles. It would be nice to have a WoH that can read and write that metadata into the `.vtt` files. I don't like to have a `+<language>` appended to the flavor, but a tag is much better.

Plus the metadata is in the standard, and I hope that any player can read that it.


Edit: also that should be add in the roadmap for the subtitle editor (If is not yet contemplated) is the ability to add styling to the subtitles, to identify each speaker.

**Comment by AndreasUrra** [comment]
Regarding language codes, AFAIK there is no ISO 639 code for Swiss German, is there? That could be helpful to be able to distinguish ; )

**Comment by AndreasUrra** [comment]
Regarding language codes, I think being able to distinguish between "de" and "de-CH" could be helpful ; )

**Comment by ziegenberg** [comment]
Language codes should follow what Dublin Core specifies for language metadata. We should be consistent across all code bases and it makes automated processing much easier if you do not have to convert it.

https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/language/

**Comment by lkiesow** [comment]
> Language codes should follow what Dublin Core specifies for language metadata

All content follows the DC requirements, since it only makes recommendations.
But both options I listed above are within the recommendations.

**Comment by mwuttke** [comment]
I have a question of understanding, as we already use software for subtitles and these are available as attachments.

What actually happens with these already existing videos with attachments? Are they displayed in the new OC (subtitles) editor and can the subtitles be edited there? If not, is it or will it be possible in the future to convert the attachments into tracks so that they can then be edited?

**Comment by lkiesow** [comment]
Right now, the subtitle editor, the cutting, … completely ignore subtitle attachments. That was the reason I suggested to not use attachments for the Moodle integration.

Having an operation to move them from attachment to track would be quite easy, though. What's more complex is managing if they should be displayed or not in the sense that the editor shows media and subtitles before cutting and subtitle attachments are often in the state after cutting.

For displaying them in the player, my suggestion would definitely be a fallback to attachments if no subtitle tracks are present.

**Comment by geichelberger** [comment]
Regarding the language code we use for subtitles, wouldn't it make sense to use the same for the metadata and anywhere else?
Otherwise, we would have to translate between the different codes, and it wouldn't be easy to derive the tag from the metadata.

That means opencast uses one language code to rule them all and only has to translate the language codes if an external system requires a different format.

The Paella Player should display the codes in a readable form (e.g., en-GB: English (UK), ...)

**Comment by Arnei** [comment]
We've written a bunch of pull requests that should make the vision described here a reality. As far as I am aware, they cover all the different places in Opencast that require changes. If you feel like there's anything missing please do mention it. And PR reviews are very welcome of course :)

List of Pull Requests (Should all be tagged with `subtitles-rework`)
- #4622 
- #4623 
- #4624 
- #4626 
- opencast/opencast-editor#958
- #4627
- #4711 
- #4842
- #4844 

You may find "TODO"s in some of the pull requests. Those will usually mean that I was not quite sure on how to approach a problem and any input would be appreciated :)

Thanks to the University of Bern for helping in sponsoring this.

----------

One thing not covered pertains to subtitles generated on cut versions of the source video tracks. To elaborate:
The common Opencast approach to tracks is to store the original tracks in a mediapckage as `*/source`, and then change the flavor when the workflow modifies them. However, subtitles may be created on the basis of modified tracks (e.g. cut tracks) to save on resources, meaning the "length" of these created subtitles will not match the length of the other tracks in `*/source`. 

This may be a problem with the editor WOH, which expects tracks to be of the same duration and will cut subtitles wrongly if they're cut together with source tracks. It's also a problem in the editor frontend, which display such subtitles wrongly, see https://github.com/opencast/opencast-editor/issues/1008. 

---------

External plugins that make use of Opencast subtitles (e.g. the Moodle Opencast plugin, Tobira) will likely have to adapt their implementation.

**Comment by mliradelc** [comment]
Thanks Arnei for your work!, I will review it in the next days. 
Because my work with Whisper is entangled with yours, can you review #4738 and #4770 ?

**Comment by Arnei** [comment]
> Thanks Arnei for your work!, I will review it in the next days. Because my work with Whisper is entangled with yours, can you review #4738 and #4770 ?

Haven't worked with whisper myself yet, but I'll see what I can do :)

**Comment by Arnei** [comment]
I'll go ahead and close this, because all the PRs are mentioned have since been merged. If someone thinks that's too hasty, we can just reopen it :)
