### ISSUE TITLE
Adopter information send Error

### ISSUE THREAD

**Issue by poffensand** [opencast/opencast#4588]
**Describe the bug**

The Adopter information is not being sent and instead throws an Error when trying to. Additionally, the UI shows no preview of the data being sent:
![grafik](https://user-images.githubusercontent.com/74779273/210988840-66f3db3f-ab66-4b0c-8461-62e6806573aa.png)

**To Reproduce**

1. In the Opencast Admin UI, enter all information in the registration panel and follow the steps
2. See no preview of the data to be sent
4. Wait for for the server to try and send the data
5.  See error in the logs

**Expected behavior**

Adopter information being sent without errors.

**Stack trace**

```
2023-01-06T10:12:44,547 | ERROR | (ScheduledDataCollector:224) - Error occurred while processing adopter general data.                                                                                                                     
java.lang.RuntimeException: HttpStatus: 400, HttpResponse: <!doctype html><html lang=en><title>400 Bad Request</title><h1>Bad Request</h1><p>The browser (or proxy) sent a request that this server could not understand.</p>              
        at org.opencastproject.adopter.statistic.Sender.send(Sender.java:156) ~[!/:?]
        at org.opencastproject.adopter.statistic.Sender.send(Sender.java:120) ~[!/:?]
        at org.opencastproject.adopter.statistic.Sender.sendGeneralData(Sender.java:82) ~[!/:?]
        at org.opencastproject.adopter.statistic.ScheduledDataCollector.run(ScheduledDataCollector.java:220) [!/:?]
        at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
        at java.util.TimerThread.run(Timer.java:506) [?:?]

```

**Server environment:**
 - OS: RHEL 8, SELinux set to permissive
 - Distribution: admin+presentation+worker
- Installation method: RPM packages
 - Version 13.0

**Additional context**

Adopter Information was entered while the Re-Indexing was running after an upgrade from Opencast 9 to Opencast 13. Client used to enter adopter registration info is running Fedora 37 with Browser Firefox 107.0.1

**Comment by gregorydlogan** [comment]
This reminds me of #4310, but I suspect there's something else going on too since the preview is blank. No error messages when the preview is generated I'm assuming?

**Comment by poffensand** [comment]
None popping up in the admin logs,no

**Comment by gregorydlogan** [comment]
@poffensand, that's very odd.  Have you by any chance removed the default organization?  If you're not sure what I'm talking about, then you probably haven't :)

Let's try upping the logging level.  Try adding this to your admin server's logging config:
```
log4j2.logger.adopter.name = org.opencastproject.adopter
log4j2.logger.adopter.level = DEBUG
```

Then open the summary UI again.  That will trigger at least at a partial trace of what's going on internally which will give me something to get started with.

**Comment by phioffen** [comment]
Hi,
sorry it took me so long to respond, a lot stopped me from looking closer. Though I finally got to it, and even with the extra Debug lines, no further messages were logged regarding the issue. Though good news now nonetheless: When going through the adopter registration again and being interrupted externally at the last step, when I got back to it, the adopter information was filled in and no error was logged upon completing registration.

**Comment by gregorydlogan** [comment]
Well, it's good that it's working at least...

How large is your install?  Could this have been that the queries it needed to run to generate the preview were not executing in reasonable time?  We haven't had any other reports of this kind of thing, but without a large system to test performance on it's hard to know if we're being too slow with things.

**Comment by phioffen** [comment]
Series 5123
Events 56984
Workflows 248427

It could be that the system did not allocate enough RAM. I had forgotten to adapt the `setenv` file after the upgrade; after setting memory usage there trying to solve other performance problems I could also create the adopter info.

**Comment by gregorydlogan** [comment]
That could conceivably be the reason.  Regardless, you appear to be registered now and without being able to reproduce it then there's not much left to do.  Feel free to reopen if this reoccurs.
