### ISSUE TITLE
/api/series.json does not work properly/very poorly

### ISSUE THREAD

**Issue by thet0ast3r** [opencast/opencast#4749]
**Describe the bug**

Using the /api/series.json endpoint fails with internal error (5xx) among other things.

* using braces "[]" in series titles and then querying the results gives an internal error. 
* searching for parts of words ( e.g. words in the tile) does not return any results. An empty list is returned.
* Search in general on this endpoint works worse than something like e.g. .contains() method.

**To Reproduce**

1. go to https://stable.opencast.org
2. log in & create a new event with title "[test] hello"
3. go to the rest api docs and test /api/series.json endpoint with e.g. "[test" in the free text search, everything else default.
4. See error -> takes a long time, then returns 504

**Expected behavior**

Fast response, good matching on free text search. No internal errors on queries. 

**Stack trace**

From the OC log, when performing a query: 
```
(SeriesEndpoint:1287) - Could not perform search query: null

2023-03-01T12:36:46,337 | ERROR | (AbstractElasticsearchIndex:619) - Could not query documents from index Elasticsearch because of Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed], not retrying.
2023-03-01T12:36:46,337 | ERROR | (SeriesEndpoint:1448) - Failed to execute search query: Error querying series index
2023-03-01T12:36:46,337 | WARN  | (SeriesEndpoint:1287) - Could not perform search query: org.opencastproject.elasticsearch.api.SearchIndexException: Error querying series index

```

**Server environment:**
stable.opencast.org's environment as of today, 2022-03-09

**Additional context**

Due to the removal of other api tools, this is the only option left to filter and search for events and its titles.

**Comment by aliyevTU** [comment]
This really needs to be fixed. Removal of old api endpoint which worked with SOLR, left us no choice to but use this new endpoint, and it is not behaving as expected for us.

**Comment by gregorydlogan** [comment]
While I can't guarantee anything wrt to accuracy of free text search the STR above do not cause any errors anymore.  I'm going to close this, please reopen if this is still a problem.
