### ISSUE TITLE
reference-users need to be removed via API endpoint

### ISSUE THREAD

**Issue by aliyevTU** [opencast/opencast#4789]
We can remove users with "opencast" provider, but the same option does not exist for users with "matterhorn-reference" on Admin UI, or on API endpoints. We need it because of GDPR, since some users are not part of organization anymore, and we are legally obliged to remove them from Opencast.

**Comment by JulianKniephoff** [comment]
@aliyevTU is this possible now or why did you close it? 👀  We (ELAN) were about to start looking into this.

**Comment by aliyevTU** [comment]
Re-opened it. Nothing has changed, the issue is still actual.

**Comment by JulianKniephoff** [comment]
Since #5058 is now merged, and @aliyevTU even tested it themselves, we can now close this! 🎉
