### ISSUE TITLE
ACL template selection has empty options

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#4910]
**Describe the bug**

Opencast 13.x has a new ACL editor which always offers some empty ACL templates to the user. I would expect the configured templates and only the configured templates to be shown:

![Screenshot from 2023-04-25 18-01-37](https://user-images.githubusercontent.com/1008395/234338703-05eda5bc-f46b-427c-b66f-ef40f5ea8957.png)

**To Reproduce**

1. Go to admin interface
2. Click on add event
3. Follow the wizard to the acl templates

**Comment by lkiesow** [comment]
For development, you can reproduce this with the local mock build:

```
❯ cd modules/admin-ui-frontend
❯ node --version
v16.18.1
❯ npm ci
…
❯ npm run build
…
```

…then navigate to `Add Event` (see above)

**Comment by mtneug** [comment]
@lkiesow is this fixed?

**Comment by lkiesow** [comment]
It should be
