### ISSUE TITLE
Problem after installation opencast 14.0 from testing repo ubuntu - Error in logfile containing Elasticsearch

### ISSUE THREAD

**Issue by FalkSwolinski** [opencast/opencast#5059]
**Describe the bug**

There is a problem with the installation package on Ubuntu. I used the testing repository for this installation.
After starting opencast an error regarding elasticsearch is thrown in the opencastlog:

2023-06-28T11:17:02,765 | ERROR | (ScrLogManager$ScrLoggerFacade:206) - bundle opencast-elasticsearch-index:14.0.0 (107)[org.opencastproject.elasticsearch.index.ElasticsearchIndex(117)] : The activate method has thrown an exception
org.osgi.service.component.ComponentException: Error initializing elastic search index
        at org.opencastproject.elasticsearch.index.ElasticsearchIndex.activate(ElasticsearchIndex.java:135) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

**To Reproduce**

1. Follow the instruction on https://docs.opencast.org/r/14.x/admin/#installation/debs/

**Server environment:**
 - OS: [Ubuntu 22.04 LTS]
 - Distribution: [allinoner]
- Installation method: [e.g. apt packages (Ubuntu)]
 - Version [14.00]

**Additional context**

Problem refers to elasticsearch even it is not installed anymore.

**Comment by gregorydlogan** [comment]
What you're likely seeing here is that Elastic/Opensearch is not running, or not configured correctly in the Opencast side.

The debian packages do not explicitly depend on either, and both ES 7.10(.2) and OS 1.x are supported and mirrored in our repository.  The Opencast side of our integration is currently named after Elastic, but it is wireline compatible with Opensearch 1.x.  When we drop Elastic support in the future we will likely rename the config + classes, but we did not do that for 14 for compatibility reasons.

**Comment by Sebastinus-Schulze** [comment]
Hello Greg,
Thanks for the hint, thats a good starting point to investigate our configurtion.
Best regards
Sebastian

**Comment by lkiesow** [comment]
This is most likely due to the incorrect documentation for the Debian packages. OpenSearch needs more set-up than just installing the package compared to Elasticsearch.

I ran into this a few days back myself. From Matrix:

> **Lars Kiesow**
>Greg Logan: I just tested an installation on Debian 11 with your packages and the documented installation of OpenSearch. That didn't work. Opencast fails to connect to the default OpenSearch installation. But the default configuration should be enough according to the documentation. Installing elasticsearch-oss instead works just fine. People might run into that problem when trying to install Opencast on Debian, Ubuntu, … and end up with a non-functional system. That's not great. I had no time to dig deeper, but my guess would be that some configuration needs to be adjusted.

> **Matthias Neugebauer**
> Probably this problem: https://groups.google.com/a/opencast.org/g/users/c/uBb2LZBFfqc

I guess the three solutions are:

- Install `elasticsearch-oss` instead
- Remove the security plugin (see link above)
- Set-up proper credentials

@gregorydlogan, can you take care of updating the Debian/Ubuntu docs?
RPMs still list ES and therefor do not suffer from that problem yet.

**Comment by gregorydlogan** [comment]
Will do. Hopefully by end of week.

**Comment by KatrinIhler** [comment]
@gregorydlogan Should this issue be closed?

**Comment by gregorydlogan** [comment]
Yep, Ty!
