### ISSUE TITLE
Crowdin V1 Integration Sunsetting

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#5098]
Crowdin is sunsetting their v1
API end of November 2023. We need to upgrade to v2 prior to that. 

Per @lkiesow, there is likely a config we can crib from inside the editor.

**Comment by gregorydlogan** [comment]
This is in my backlog. If anyone else has the cycles to do it prior to me feel free.

**Comment by lkiesow** [comment]
This should be fixed by #5114
