### ISSUE TITLE
Feature request: Endpoint to get Licenses & Languages in metadata

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast#5099]
**Description**
So far all major Opencast Plugins in LMSes provide available licenses and languages themselves (Hardcoded) and basically is a copy and paste of those in Opencast server, which is not a good practice.

**Feature**
That would be really great, if we could have a listing endpoint under `/api` to get the list of listables like languages and licenses.

**Expected**
I should be able to call to an endpoint like `/api/listing/{value}` where possible values could be `languages` or `licenses` and get the exact listing as provided in adminUI.
Of course in `key:value` pairs

**Nice to have**
Would be much nicer if it could handle the localization as well
E.g. passing 'de' returns the list in Germen.

**Comment by mtneug** [comment]
@Arnei can this be closed?

**Comment by Arnei** [comment]
Yup, can be closed
