### ISSUE TITLE
The default player should gracefully handle multiple streams

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#5107]
Ingesting multiple streams or streams with unknown flavors, the player shouldn't just give up, but try to nicely render the existing streams. Right now. Paella will just show a massive error.

### Example

Ingest a new event like this:

```
SERVER=https://develop.opencast.org

curl -u admin:opencast "${SERVER}/ingest/addMediaPackage/fast" \
        -F 'flavor=a/source' \
        -F mediaUri=https://data.lkiesow.io/opencast/test-media/goat.mp4 \
        -F 'flavor=b/source' \
        -F mediaUri=https://data.lkiesow.io/opencast/test-media/goat.mp4 \
        -F 'flavor=c/source' \
        -F mediaUri=https://data.lkiesow.io/opencast/test-media/goat.mp4 \
        -F title="Three Video Streams" \
        -F creator="Test"
```

Wait for it to be processed and go to the player. You get nothing but a big error message:

![Screenshot from 2023-07-12 14-31-38](https://github.com/opencast/opencast/assets/1008395/a16fb519-3007-41aa-8fe7-7271f5cd5cb4)

The player does that even though valid video streams are published:

```
❯ curl -s -u admin:opencast 'https://develop.opencast.org/search/episode.json?id=0660c600-78cd-43a9-a771-cc4e7770353c' | jq -r '.["search-results"].result.mediapackage.media.track[] | .type + "  ->  " + .url'
c/preview  ->  https://develop.opencast.org/static/mh_default_org/engage-player/0660c600-78cd-43a9-a771-cc4e7770353c/a73fabaf-9f44-4877-8399-7a07a1ffa2e6/goat.mp4
b/preview  ->  https://develop.opencast.org/static/mh_default_org/engage-player/0660c600-78cd-43a9-a771-cc4e7770353c/96aa5320-7f3f-4179-918b-05d6fb6f229a/goat.mp4
a/preview  ->  https://develop.opencast.org/static/mh_default_org/engage-player/0660c600-78cd-43a9-a771-cc4e7770353c/9208f55d-88e9-411c-93a7-59b07354c559/goat.mp4
```

### Improvement

As a last resort, before giving up, the player should engage an auto mode:

- Get all tracks
- Filter our audio-only tracks
- Group tracks by flavor/type
- Show one video of each flavor in the player

Long term, we might even make this the default

**Comment by dennis531** [comment]
![image](https://github.com/opencast/opencast/assets/44410838/55d30ee0-5c66-4dd4-8d5b-6f2ce956d0ee)

The videos are displayed in a dynamic layout, i.e. in one row. Would that be enough or should we split the videos across multiple rows?

The layout shown can handle any number of streams.

**Comment by lkiesow** [comment]
While there could be a better layout in some cases (e.g. a grid would certainly be better for four videos), having one or two videos is the default (the layout works great for that on a landscape mode display) and having three videos occurs sometimes (the layout is okay for that). So, I think that's a good start.

If you want to do some improvements (vertical layout for portrait mode, grid layout with 4 (3?) or more videos), sure, but that can also be a separate pull request.

**Comment by dennis531** [comment]
![image](https://github.com/opencast/opencast/assets/44410838/b1e0ae46-aa88-4c82-855f-ec32ef0b0094)

Thankfully, [dynamic layouts](https://paellaplayer.upv.es/#/doc/video_layout.md) already support vertical layout in portrait mode.
