### ISSUE TITLE
Paella7: Vertically stretched thumbnails in audio transcriptions plugin

### ISSUE THREAD

**Issue by scharnkn** [opencast/opencast#5186]
**Describe the bug**

Thumbnails in the audio transcriptions plugin in Paella Player 7 are vertically stretched to the size of the textbox next to it. Naturally the problem becomes more appearent if a slide contains a lot of text.

**To Reproduce**

- Upload a video containing a lot of text using a workflow that uses the segmentation and extract text operations
- Open the video in paella Player 7 and look at the audio transciptions submenu.

**Expected behavior**

The aspect ratio of the original image should be used to display the thumbnails.

**Screenshots**

![screenshot_bug](https://github.com/opencast/opencast/assets/44021701/6a309118-a989-424c-9d7f-405b514f634e)

**User environment:**

 - Device: PC
 - OS: Debian 12
 - Browser: Chrome
 - Version: 116.0.5845.110

**Comment by mliradelc** [comment]
@miesgre Maybe you want to check this.

**Comment by miesgre** [comment]
@scharnkn Do you have a small video to test it?

**Comment by scharnkn** [comment]
@miesgre I attached the video I used in the screenshot. It had to compress/modify the video a little bit decrease the size, I hope OCR still works well enough for testing. Let me know if I should provide a better quality.

[test_ocr.zip](https://github.com/opencast/opencast/files/12574871/test_ocr.zip)

**Comment by mliradelc** [comment]
Fixed on `r/14.x`
