### ISSUE TITLE
Matomo integration for Paella lacks documentation

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#5244]
The [current documentation](https://docs.opencast.org/develop/admin/#modules/paella.player/plugins/es.upv.paella.opencast.userTrackingSaverPlugIn/) for the tracking module only refers to the old, busted tracking system.  We should be directing people to use Matomo, and documentation how to configure it.

@miesgre if I assign this to you, can you guys handle this?

**Comment by miesgre** [comment]
This documentation is for paella 6. Assign to me and I will add the plugins documentation to paella 7
