### ISSUE TITLE
Drop unused internal logger

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#5261]
We still have a separate internal logger implementation which has some problems (see #5240) and which can likely be removed completely. See https://github.com/opencast/opencast/pull/5240#pullrequestreview-1615380222

We should investigate if we can remove the logger in question:
https://github.com/opencast/opencast/blob/fcb7f122d0f7977455933be8ccbb3f293827a4ca/modules/common/src/main/java/org/opencastproject/util/Log.java#L45

…and replace it with our default logger:
https://github.com/opencast/opencast/blob/fcb7f122d0f7977455933be8ccbb3f293827a4ca/modules/crop-ffmpeg/src/main/java/org/opencastproject/crop/impl/CropServiceImpl.java#L180

**Comment by amritagg** [comment]
Hi, @lkiesow can I work on this issue?

**Comment by lkiesow** [comment]
Sure, go ahead. Let me know if you have any questions.
I've assigned the issue to you.
If you don't want to work this after all, please unasign yourself and/or let us know so that someone else can work on this.
Thanks for taking this on!

**Comment by amritagg** [comment]
Thanks for assigning me for the issue. Just wanted to clarify that I do need to replace **Log** type logger with **Logger** type logger in complete project or only in CropServiceImpl.java class?

**Comment by lkiesow** [comment]
I think the class Log can be completely removed and all usage replaced
with the default Logger. But if it turns out that there is still a
valid use-case somewhere and we just cut down the overall usage, that
is fine as well.

**Comment by amritagg** [comment]
I wasn't able to complete remove usage of Log class because of one method  **getHumanReadableTimeString** was getting used multiple locations.
