### ISSUE TITLE
Configure dispatch interval in milliseconds

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#5300]
It would be nice to be more precise when configuring the main dispatch interval:

https://github.com/opencast/opencast/blob/4970c798a3f25783f40d9b7b5196a7673bdf5ec2/etc/org.opencastproject.serviceregistry.impl.JobDispatcher.cfg#L8

But right now, this value is read as an integer and interpreted as seconds:

https://github.com/opencast/opencast/blob/4970c798a3f25783f40d9b7b5196a7673bdf5ec2/modules/serviceregistry/src/main/java/org/opencastproject/serviceregistry/impl/JobDispatcher.java#L206-L236

It would be great if we could interpret the configuration as float and then configure the scheduler with millisecond precision.

**Comment by shohan2001** [comment]
Can you please assign this to me?

**Comment by lkiesow** [comment]
Sure. Done. If you want to pick this up, that's great.
If you have any further questions, please ask.

If you don't want to work on this after all, please unassign yourself and/or let us know so that someone else can pick this up.

**Comment by shohan2001** [comment]
Thanks for assigning

**Comment by gregorydlogan** [comment]
This was originally scheduled in MS, but we couldn't guarantee accuracy, rememeber? Sub-second dispatching can be too quick in loaded situations.

**Comment by lkiesow** [comment]
@gregorydlogan, you are misremembering. You are right, that this was defined in milliseconds once upon a time, but as you described in #1117, we wanted this to be changed to not have one setting in seconds and one in milliseconds. The change was made in pull request #1120.

An unfortunate side effect of this change was that you can no longer set a dispatch interval of, for example, 1.5 seconds. The configuration value is interpreted as an integer and then used for scheduling with seconds as time unit. Switching this to a float, passing `dispatchInterval * 1000` with milliseconds as time unit to the scheduler makes this possible again while keeping all units as seconds in the configuration.

As for things being too fast, the service still enforces a minimum dispatch interval of 1 second. I'm not suggesting to change that.

**Comment by debanjanc01** [comment]
Hey @lkiesow is this still being worked on? I have a fix ready if needed.
Additionally, line 216 mentions **ms** in the log line `logger.warn("Dispatch interval {} ms too low, adjusting to {}", dispatchInterval, MIN_DISPATCH_INTERVAL);` . This should be **seconds** as well.

**Comment by debanjanc01** [comment]
Hey, @lkiesow could you please assign this to me? I'll raise the PR.

**Comment by debanjanc01** [comment]
Hey, I've raised the PR.
