### ISSUE TITLE
Update or remove axios from LTI tools

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#5304]
Opencast's LTI tools require the axios JavaScript library in an old version and simply updating does not seem to work:
See #5288

We should take a look into updating axios or, even better, removing it and replacing it with [JavaScript's native Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

You can run the LTI tools separately from Opencast like this:
```
❯ cd modules/lti/
❯ npm ci
❯ ./copy-translations.sh
❯ npm run start
```

**Comment by Lyx52** [comment]
@lkiesow I can try to refactor it to fetch if you can assign it to me
