### ISSUE TITLE
Listproviders API endpoints do NOT work with Accept header containing API version

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast#5308]
**Describe the bug**
The new api listprovider endpoints only work when the `Accept` header is not passed with the request: `Accept: application/v1.10.0+json`
And since it has been introduced in v1.10.0, it is somehow mandatory to check that version!
When that Accept header is there, then the result is like:

```
{
  "available": []
}
```

**To Reproduce**

1. Make a GET call to any api/listproviders endpoint but with the above mentioned header like:
![Screenshot 2023-10-04 at 17 24 13](https://github.com/opencast/opencast/assets/53179227/cc22c9c5-10b6-4797-a535-fde0d32523a4)

2. See the result!

**Expected behavior**
The response result must have correct values when `Accept` header is there and should look like:
![Screenshot 2023-10-04 at 17 30 42](https://github.com/opencast/opencast/assets/53179227/dd1d280d-4d24-4a5f-a80c-bc3570b79fbb)

In the image about the Accept is not provided!

**Additional context**
`https://stable.opencast.org` has been used for the tests and images above!

**Comment by JulianKniephoff** [comment]
Something about **at least** the REST docs isn't right here, as well. Compare the following screenshots:

`/api/series` endpoint:

<img width="925" alt="Screenshot 2023-10-18 at 13 42 56" src="https://github.com/opencast/opencast/assets/123272/3aa7edb2-44c9-479d-8c86-29a6474c879f">

`/api/listproviders/providers` endpoint:

<img width="925" alt="image" src="https://github.com/opencast/opencast/assets/123272/ba9cbb77-40d0-4f94-b38a-b1d21c40ad21">


No idea whether this has anything to do with the problem at hand, but it should prolly be fixed as well. Like, the docs should state the admissible versions for these endpoints.
