### ISSUE TITLE
Weird "default" answer from the external API?

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/opencast#5343]
In #5308 we saw a weird answer from a newer external API endpoint when you query it in a certain way:

```json
{
  "available": []
}
```

This response doesn't really seem to have anything to do with that specific endpoint, so I dug around a bit and indeed, you can also get it from other, totally unrelated endpoints, for example

```sh
curl -v -L 'https://develop.opencast.org/api/workflows/1.json' \
  -H 'accept: application/v1.0.0+json' \
  -u admin:opencast
```

Two things to note about that call:

* [The endpoint](https://develop.opencast.org/docs.html?path=/api/workflows#getworkflowinstance-1) doesn't actually end in `.json`,
* and we are querying a version which it is not yet part of.

With both of these, that should also give you the weird response. It seems to be some kind of fallback response? But it's not very useful at that, so I don't think it's intended?

**Comment by Arnei** [comment]
Seems to be somehow related to adding `.json` to the endpoint AND explicitly specifying an external api version header. The specified external api endpoint does not even get called, so the weird response is coming from somewhere else.
