### ISSUE TITLE
API Listproviders endpoint needs a ROLE!

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast#5402]
**Describe the bug**

The API list providers now work fine also with API version attached to the request. However, by passing an Authorization header to that call the response ends up in 401 Forbidden, which means there need to be a `listprovider` specific ROLE (like `ROLE_API_LISTPROVIDERS_VIEW`) for the API user to add. 

**To Reproduce**

1. In a clear—not-logged-in session, try to make the HTTP request to the `/api/listproviders/*`
2. Add the Authorization header, just like with default API username and password
3. Make a GET call to one of the `listproviders` endpoint (i.e. `/api/listproviders/providers.json` or `/api/listproviders/LANGUAGES.json`)
4. See the response, which is always 401 Forbidden!

**Expected behavior**

Either:

1. Having a separated ROLE like `ROLE_API_LISTPROVIDERS_VIEW` to set for the API user.
2. (Recommended) Make it accessible when the API user has `ROLE_API`

The first approach, although it seems to be more practical, is not of the favour from LMS side. Because it forces the admins to edit their API user in opencast and if they don't pay attention to the manual or helper docs (Who reads them 😅). They always end up with forbidden error!

***Previous Work of this topic***
Issue (https://github.com/opencast/opencast/issues/5308) => PR (https://github.com/opencast/opencast/pull/5344)

**Comment by Arnei** [comment]
> 1. Having a separated ROLE like ROLE_API_LISTPROVIDERS_VIEW to set for the API user.
> 2. (Recommended) Make it accessible when the API user has ROLE_API

Going with `1.`, as that is common practice. `ROLE_API` is only used for a few top level paths. And if you don't want to bother with fine grained access control, you can always slap `ROLE_ADMIN` on your LMS user anyway.

**Comment by JulianKniephoff** [comment]
@ferishili this should be fixed in `13.x` now, but not forward merged and obviously also not released, yet. However, the fix is just configuration, so you can just apply it locally on your site as well. See #5404.

**Comment by ferishili** [comment]
Great, thanks a lot
