### ISSUE TITLE
Paella Player is broken for single stream recordings 

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast#5536]
**Describe the bug**

Paella Player is broken for single stream recordings on stable.opencast.org.

**To Reproduce**

1. Go to stable.opencast.org.
2. Click on the event details for any single stream event, then open the engage publication

**Expected behavior**

Paella player should work.

**Screenshots**

![paellabroken](https://github.com/opencast/opencast/assets/14070005/fcb0e1cc-0200-435e-bb6e-194c4f4d2b0a)

**User environment:**

 - OS: Fedora
 - Browser Firefox
 - Version 121.0

**Comment by gregorydlogan** [comment]
Relevant stack traces, in order

![image](https://github.com/opencast/opencast/assets/5639561/cbb34292-d28c-430d-a470-c5a24c528b8b)
![image](https://github.com/opencast/opencast/assets/5639561/38f22b6b-60a0-45fe-ba01-c96c319550e5)

**Comment by KatrinIhler** [comment]
I think it's https://github.com/opencast/opencast/pull/5420, that breaks for videos with only one track (and captions count as tracks, which is why the goat video on stable is unaffected).

**Comment by Arnei** [comment]
Allegedly this was fixed by #5488

**Comment by KatrinIhler** [comment]
> Allegedly this was fixed by #5488

I think it was #5539 (or maybe both), but yeah, agree that this is fixed.
