### ISSUE TITLE
Sign in is not working

### ISSUE THREAD

**Issue by Ankarrr** [opencast/opencast#5585]
**Describe the bug**

Sign in using ethereum wallet is not working

**To Reproduce**

1. Go to https://opencast.stephancill.co.za/login
2. Click on sign in with ethereum
3. Confirm the tx
4. See loading 
5. After the tx is confirmed, it's still loading

**Expected behavior**

After the tx is confirmed, I should sign in successfully

**Screenshots**

<img width="482" alt="截圖 2024-02-02 下午2 45 13" src="https://github.com/opencast/opencast/assets/8311552/6377f4ab-cca8-4371-9c1b-5491d80a262a">

**User environment:**

 - Browser: Chrome

**Additional context**

My tx: https://optimistic.etherscan.io/tx/0xcd15a559ccbf4a467a57f79f0eaa390d420df718e7c64307edd7fdcf4014d07c

**Comment by gregorydlogan** [comment]
You're barking up the wrong tree here @Ankarrr.  [That](https://opencast.stephancill.co.za/login) is not Opencast, or at least not this Opencast :)

No crypto, no social media, we're a video management solution.
