### ISSUE TITLE
Process-smil WOH tag-with-profile configuration does not work depending on the encoding profile suffix configured

### ISSUE THREAD

**Issue by rute-santos** [opencast/opencast#5687]
**Describe the bug**

Process-smil WOH tag-with-profile configuration does not work depending on the encoding profile suffix and the 'safe file name' pattern defined in the WorkingFileRepository configuration.

**To Reproduce**

1. Leave the default regex in the WorkingFileRepository service configuration "filename.forbidden.pattern"
2. Run a workflow using the process-smil WOH having the configuration "tag-with-profile" = true.
3. In the encoding profile used, have a suffix starting with a dash e.g. -presentation-3q-300k-25fps.mp4
4. The resulting tracks are not tagged with the encoding profile name.

**Expected behavior**

Resulting tags should be tagged with the encoding profile name.

**Server environment:**
 - OS: Red Hat Enterprise Linux Server release 7.9
 - Distribution: all
- Installation method: compiled from source
 - Version: develop

**Comment by mtneug** [comment]
Close as #5687 was merged.
