### ISSUE TITLE
Deletion of "matterhorn-reference" Users broken

### ISSUE THREAD

**Issue by llttugraz** [opencast/opencast#5753]
**Describe the bug**

The deletion of AAI-generated users (provider: matterhorn-reference) seems to have been broken since 14.x (could have been one of the minor updates).

This is the PR that introduced that feature:
https://github.com/opencast/opencast/pull/5058

**To Reproduce**

The issue:
In essence, when we run the following (eg by clicking the delete button in the admin-UI)
DELETE https://\<oc-admin-host\>/admin-ng/users/\<userID\>.json

we get a 404 response (although the user does exist) and the deletion is unsuccessful.

1. Go to the users list on the admin-ui and find a "matterhorn-reference" provided user
2. Click on the delete button (red X)
3. See error

**Server environment:**
 - OS: 7CentOS Stream 7
 - Distribution: admin/presentation+3workers]
- Installation method: RPM packages
 - Version: 14.7

**Comment by JulianKniephoff** [comment]
I'm currently looking into this.

**Comment by JulianKniephoff** [comment]
`git bisect` shows that this was probably broken by #5062. 🤔

**Comment by JulianKniephoff** [comment]
[This](https://github.com/opencast/opencast/pull/5062/files#diff-421d3d38688bae087812813c8d8d5dab5bbee4448ba1061d58cae4c12eff65edR442) (probably accidental) change is probably the culprit; we are checking the user and roles provider twice, ignoring the user reference provider.

I'll test this and make a PR shortly. 😊

**Comment by llttugraz** [comment]
Thanks @JulianKniephoff for having a look :)

**Comment by JulianKniephoff** [comment]
There was actually [another place](https://github.com/opencast/opencast/commit/a669969c3a415ae260d20165e1f88629874d8481?diff=unified&w=0#diff-421d3d38688bae087812813c8d8d5dab5bbee4448ba1061d58cae4c12eff65edL170-R181) where the merge went wrong, giving me a `NullPointerException` with my first attempted solution, but that should be fixed as well now. PR incoming!
