### ISSUE TITLE
Dual stream with subtitles track isn't published correctly

### ISSUE THREAD

**Issue by snoesberger** [opencast/opencast#5817]
**Describe the bug**

When I upload a dual stream recording with a subtitle track, only one stream is published and available in the video player.

**To Reproduce**

1. Go to the admin interface and create a new event, add a presenter video, a presentation video and a subtitle file.
2. Select the `schedule-and-upload` workflow with the `straightToPublishing` option set to `true` and start processing.
3. Once processing is complete, only one video will be available in the Video Player.

**Expected behavior**

Both the presenter and the presentation video should be available in the player.

**Server environment:**
Reproducible on [stable.opencast.org](https://stable.opencast.org) (Opencast 15)

**Additional context**

The cause of the error lies in the ‘select-tracks’ workflow step (SelectStreamsWorkflowOperationHandler). This WOH does not seem to handle subtitle tracks correctly.

**Comment by wsmirnow** [comment]
Should be fixed with https://github.com/opencast/opencast/pull/5879

**Comment by wsmirnow** [comment]
fixed by #5829
