### ISSUE TITLE
Provide config to set default workflow in admin ui

### ISSUE THREAD

**Issue by pselsa** [opencast/opencast#6026]
With `org.opencastproject.workflow.default.definition` in `etc/custom.properties` it is possible to set the default workflow for ingested media, but there is no way to set the default workflow for uploads in the admin ui. This is kind of annoying when you have only one workflow to choose from but have to select it every time:

<img width="783" alt="image" src="https://github.com/user-attachments/assets/9cee64ee-3d69-4162-9657-4d59267b5716">

There is no need to adjust anything in the admin-ui since its already utilizing the `default_workflow_id` variable from the endpoint `admin-ng/event/new/processing` - so its just a backend task.

Problem is, that the endpoint `admin-ng/event/new/processing` always returns `"default_workflow_id": null`.

**Comment by KatrinIhler** [comment]
iirc this used to work, if this is broken now, this seems like a bug. (Also we used to have the feature that the workflow would be pre-selected if there was only one iirc.)

**Comment by pselsa** [comment]
@KatrinIhler I wonder if it is enough to just implement the admin ui to pre-select the first item in any case. For our setup that would be fine since we only have one workflow anyway

**Comment by KatrinIhler** [comment]
I'm not certain if I would favor a pre-selection in every case. But if there's only one item in the list and the field is required, pre-selection definitely makes sense. And the old Admin UI at least also used to do that.

**Comment by pselsa** [comment]
Ok then I gonna open a separate ui issue for this :)

**Comment by pselsa** [comment]
https://github.com/opencast/opencast-admin-interface/pull/850
