### ISSUE TITLE
Subtitles out of sync when adding intro bumper theme

### ISSUE THREAD

**Issue by llttugraz** [opencast/opencast#6036]
**Describe the bug**

OC Themes give the option to add a bumper video at the beginning and at the end of a recording (intro/outro). This causes the video duration to change and the first frame of the recording to be shifted from time=0 to time=lengt_of_intro.
The above cause a sync problem with subtitles (which can eg be created, uploaded, edited in the new editor, or directly uploaded with the recording.

**To Reproduce**

1. Create a theme with an intro bumper and enable it for a series
2. Upload a recording and respective subtitles to the above series using the default WF
3. Open the published video

**Expected behavior**

The published recording should have correct sync between video and subtitles.

**Server environment:**
 - OS: Debian12
 - Distribution: all-in-one
- Installation method: Debian packages
 - Version: 15.6

**Additional context**

Possible solution: add a feature to the Theme operation that offsets the timestamps of subtitles according to the length of the intro bumper (if activated).

**Comment by Arnei** [comment]
https://github.com/opencast/opencast/pull/5913 aims at providing a fix/workaround for this.

**Comment by llttugraz** [comment]
> #5913 aims at providing a fix/workaround for this.

Thanks @Arnei! I tried to find an open issue about this but I guess I used the wrong queries :)
