### ISSUE TITLE
Canvas LTI : Refused to display 'https://stable.opencast.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by amg-web** [opencast/opencast#6085]
**Describe the bug**

Integrated stable.opencast.org with Open Canvas LMS, can not test due to error:

> Refused to display 'https://stable.opencast.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**To Reproduce**

add application in Open Canvas LMS with LTI https://stable.opencast.org/lti  with the key CONSUMERKEY and the secret CONSUMERSECRET.

try to create module (screenshot)
![Screenshot from 2024-08-04 10-36-05](https://github.com/user-attachments/assets/af0e3809-4cc3-4642-9b53-c00c1e0828df)

**Expected behavior**

Supposed to test integration.

**User environment:**

 - Device: PC
 - OS: Ubuntu 24.04
 - Browser: Opera
 - Version 112.0.5197.39

**Comment by lkiesow** [comment]
`X-Frame-Options` should no longer be set on the demo machines.
