### ISSUE TITLE
Backport of changes for amberscript from Opencast Version 16 to Opencast Version 15 possible?

### ISSUE THREAD

**Issue by mwuttke** [opencast/opencast#6179]
Is it possible to make the [changes](https://github.com/opencast/opencast/pull/6142/files) made for amberscript in version 16.5 (see also [#6143](https://github.com/opencast/opencast/pull/6143) & [#6141](https://github.com/opencast/opencast/pull/6141)) also available for version 15?

**Comment by gregorydlogan** [comment]
Looking at the commit history @lkiesow, @JulianKniephoff, or @Arnei would probably be most likely to know.

**Comment by Arnei** [comment]
Looks possible at a glance. I personally won't get to backporting this anytime soon though.

**Comment by Arnei** [comment]
Opened a PR with the changes. Just from looking at the code the changes look reasonable, but the real important thing is to actually test them, which I cannot right now. @mwuttke, could you test the PR?

**Comment by mwuttke** [comment]
Sorry, aber im Moment habe ich  keine Zeit den Patch zu testen.
