### ISSUE TITLE
Update documentation on old admin ui and plugin management

### ISSUE THREAD

**Issue by owi92** [opencast/opencast#6231]
The old admin ui was turned into a plugin some months ago, but the docs do not reflect this yet.
- https://docs.opencast.org/develop/admin/#configuration/admin-ui/new-admin-ui/ doesn't mention the need to activate the plugin and
- https://docs.opencast.org/develop/admin/#configuration/plugin-management/ doesn't list the old admin ui as a plugin.

**Comment by gregorydlogan** [comment]
Note that I just removed it completely in `develop`, so work on 16.x and older if you're fixing this.

**Comment by owi92** [comment]
Right, I just wanted to test something in the old admin UI and wondered why it wasn't working anymore. I think there are some institutions that still need or rather want to use the old interface until they're forced to upgrade.
