### ISSUE TITLE
Rest Docs test forms do not open

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast#6383]
**Describe the bug**

Testing forms in the rest docs do not open anymore. Instead, I am send to the top of the page.

**To Reproduce**

1. Go develop.opencast.org or stable.opencast.org
2. Click on the question mark in the top right corner and select rest docs
3. Select any category and find a post request
4. Click on "Testing form (click to reveal)"
5.  You are back at the top of the page

**Expected behavior**

The usual form should open so that the endpoint can actually be tested.

**User environment:**

 - Device: DEsktop
 - OS: Fedora
 - Browser: Firefox
 - Version 133

**Comment by ferishili** [comment]
The console log says:
`The resource from “https://stable.opencast.org/js/jquery/dist/jquery.min.js” was blocked due to MIME type (“application/octet-stream”) mismatch (X-Content-Type-Options: nosniff).`
`Uncaught ReferenceError: $ is not defined`
