### ISSUE TITLE
Add "templates" for reporting issues on github

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#8]
Bug report issues on github would be greatly improved if we use "reporting templates", like opencast version, result of specific commands... Example: https://github.com/moby/moby/issues/new

**Comment by lkiesow** [comment]
For now, we have no of the Github specific templates/files (e.g. contributing.md) but I think we should wait with the work until we have the decision to actually move here

**Comment by lkiesow** [comment]
Closed since we are staying on Bitbucjet…
