### ISSUE TITLE
Opencast may use elasticsearch REST API

### ISSUE THREAD

**Issue by mostolog** [opencast/opencast#9]
It seems current opencast-elasticsearch integration is done using a java library/class, instead of REST API, which is the recommended way.
Furthermore, this implies our own maintenance and a harder to deploy an elasticsearch cluster.

We could locate (in source) where the embebed elastic is created, configured and deployed, and where indexes are uses, in order to change those to use a separate instance and his API.

REST basics:
https://www.elastic.co/guide/en/elasticsearch/reference/master/_exploring_your_cluster.html

**Comment by rrolf** [comment]
I am working on switching to the Rest API for Elasticsearch now for quite some while in my "spare" time. It is more work than I initially expected and still will take quite some time. 

https://opencast.jira.com/browse/MH-12165

Also I don't think that the current setup will make it complicated to setup a cluster, as you can make the build in node to the master and add some more ES nodes. But I have never tried it. And I guess as long as the engage search service is still Solr (one of my follow up tasks), it will not be a huge demand on a ES cluster within the community.

**Comment by mostolog** [comment]
IMHO the first _easy_ step could be setting a separate "elasticsearch.url" property to reference the bundled ES instance.
Once done, migrating to a newer ES version or using an external instance would be another problem, and we could start dealing with it...otherwise it's a blocking item to clusterize admin.

As usual, "I have time to do it, until I haven't", then it will be in spare time. :(

Working on Solr is another task we should take a look to.

**Comment by lkiesow** [comment]
The decision was made to not migrate to Github but stay with Bitbucket and Jira.
If this  issue still persists, can you please open a ticket at
https://opencast.jira.com
